// Code generated by muprotogen; DO NOT EDIT.

package chat

import "testing"

func TestFixedPacketsLayout(t *testing.T) {
	cases := []struct {
		name   string
		size   int
		header byte
		code   byte
		hasSub bool
		sub    byte
		mk     func() []byte
	}{
		{"Authenticate", 16, 0xC1, 0x00, false, 0x00, func() []byte { return NewAuthenticate().Bytes() }},
		{"ChatRoomClientJoined", 15, 0xC1, 0x01, true, 0x00, func() []byte { return NewChatRoomClientJoined().Bytes() }},
		{"LeaveChatRoom", 3, 0xC1, 0x01, false, 0x00, func() []byte { return NewLeaveChatRoom().Bytes() }},
		{"ChatRoomClientLeft", 15, 0xC1, 0x01, true, 0x01, func() []byte { return NewChatRoomClientLeft().Bytes() }},
		{"KeepAlive", 3, 0xC1, 0x05, false, 0x00, func() []byte { return NewKeepAlive().Bytes() }},
	}
	for _, tc := range cases {
		buf := tc.mk()
		if len(buf) != tc.size {
			t.Errorf("%s: got %d bytes, want %d", tc.name, len(buf), tc.size)
		}
		if buf[0] != tc.header {
			t.Errorf("%s: header 0x%02X, want 0x%02X", tc.name, buf[0], tc.header)
		}
		codeIdx := 2
		if tc.header == 0xC2 || tc.header == 0xC4 {
			codeIdx = 3
		}
		if buf[codeIdx] != tc.code {
			t.Errorf("%s: code 0x%02X, want 0x%02X", tc.name, buf[codeIdx], tc.code)
		}
		if tc.hasSub && buf[codeIdx+1] != tc.sub {
			t.Errorf("%s: sub 0x%02X, want 0x%02X", tc.name, buf[codeIdx+1], tc.sub)
		}
	}
}

func TestFixedStructSizes(t *testing.T) {
	cases := []struct {
		name string
		size int
		mk   func() []byte
	}{
		{"ChatClient", 11, func() []byte { b := make([]byte, ChatClientLength); _ = AsChatClient(b); return b }},
	}
	for _, tc := range cases {
		if len(tc.mk()) != tc.size {
			t.Errorf("%s: size mismatch", tc.name)
		}
	}
}
