// Code generated by muprotogen from MUnique.OpenMU.Network.Packets 0.9.10; DO NOT EDIT.

package chat

// Authenticate (C1HeaderWithSubCode 0x00, ClientToServer)
type Authenticate struct{ d []byte }

const AuthenticateHeaderType byte = 0xC1
const AuthenticateCode byte = 0x00
const AuthenticateLength = 16

func NewAuthenticate() *Authenticate {
	p := &Authenticate{d: make([]byte, AuthenticateLength)}
	setHeader(p.d, 0xC1, 0x00, -1)
	return p
}

func AsAuthenticate(buf []byte) *Authenticate { return &Authenticate{d: buf} }
func (p *Authenticate) Bytes() []byte         { return p.d }
func (p *Authenticate) Len() int              { return len(p.d) }

func (p *Authenticate) RoomId() uint16         { return getU16LE(p.d[4:]) }
func (p *Authenticate) SetRoomId(value uint16) { setU16LE(p.d[4:], value) }

func (p *Authenticate) Token() []byte { return p.d[6:16] }

// ChatRoomClientJoined (C1HeaderWithSubCode 0x01 0x00, ServerToClient)
type ChatRoomClientJoined struct{ d []byte }

const ChatRoomClientJoinedHeaderType byte = 0xC1
const ChatRoomClientJoinedCode byte = 0x01
const ChatRoomClientJoinedSubCode byte = 0x00
const ChatRoomClientJoinedLength = 15

func NewChatRoomClientJoined() *ChatRoomClientJoined {
	p := &ChatRoomClientJoined{d: make([]byte, ChatRoomClientJoinedLength)}
	setHeader(p.d, 0xC1, 0x01, 0)
	return p
}

func AsChatRoomClientJoined(buf []byte) *ChatRoomClientJoined { return &ChatRoomClientJoined{d: buf} }
func (p *ChatRoomClientJoined) Bytes() []byte                 { return p.d }
func (p *ChatRoomClientJoined) Len() int                      { return len(p.d) }

func (p *ChatRoomClientJoined) ClientIndex() byte         { return p.d[4] }
func (p *ChatRoomClientJoined) SetClientIndex(value byte) { p.d[4] = byte(value) }

func (p *ChatRoomClientJoined) Name() []byte         { return cstring(p.d[5:15]) }
func (p *ChatRoomClientJoined) NameString() string   { return string(cstring(p.d[5:15])) }
func (p *ChatRoomClientJoined) SetName(value string) { writeCString(p.d[5:15], value) }

// LeaveChatRoom (C1Header 0x01, ClientToServer)
type LeaveChatRoom struct{ d []byte }

const LeaveChatRoomHeaderType byte = 0xC1
const LeaveChatRoomCode byte = 0x01
const LeaveChatRoomLength = 3

func NewLeaveChatRoom() *LeaveChatRoom {
	p := &LeaveChatRoom{d: make([]byte, LeaveChatRoomLength)}
	setHeader(p.d, 0xC1, 0x01, -1)
	return p
}

func AsLeaveChatRoom(buf []byte) *LeaveChatRoom { return &LeaveChatRoom{d: buf} }
func (p *LeaveChatRoom) Bytes() []byte          { return p.d }
func (p *LeaveChatRoom) Len() int               { return len(p.d) }

// ChatRoomClientLeft (C1HeaderWithSubCode 0x01 0x01, ServerToClient)
type ChatRoomClientLeft struct{ d []byte }

const ChatRoomClientLeftHeaderType byte = 0xC1
const ChatRoomClientLeftCode byte = 0x01
const ChatRoomClientLeftSubCode byte = 0x01
const ChatRoomClientLeftLength = 15

func NewChatRoomClientLeft() *ChatRoomClientLeft {
	p := &ChatRoomClientLeft{d: make([]byte, ChatRoomClientLeftLength)}
	setHeader(p.d, 0xC1, 0x01, 1)
	return p
}

func AsChatRoomClientLeft(buf []byte) *ChatRoomClientLeft { return &ChatRoomClientLeft{d: buf} }
func (p *ChatRoomClientLeft) Bytes() []byte               { return p.d }
func (p *ChatRoomClientLeft) Len() int                    { return len(p.d) }

func (p *ChatRoomClientLeft) ClientIndex() byte         { return p.d[4] }
func (p *ChatRoomClientLeft) SetClientIndex(value byte) { p.d[4] = byte(value) }

func (p *ChatRoomClientLeft) Name() []byte         { return cstring(p.d[5:15]) }
func (p *ChatRoomClientLeft) NameString() string   { return string(cstring(p.d[5:15])) }
func (p *ChatRoomClientLeft) SetName(value string) { writeCString(p.d[5:15], value) }

// ChatRoomClients (C2Header 0x02, ServerToClient)
type ChatRoomClients struct{ d []byte }

const ChatRoomClientsHeaderType byte = 0xC2
const ChatRoomClientsCode byte = 0x02

func NewChatRoomClients(size int) *ChatRoomClients {
	p := &ChatRoomClients{d: make([]byte, size)}
	setHeader(p.d, 0xC2, 0x02, -1)
	return p
}

func ChatRoomClientsRequiredSize(count int) int { return count*ChatClientLength + 8 }

func AsChatRoomClients(buf []byte) *ChatRoomClients { return &ChatRoomClients{d: buf} }
func (p *ChatRoomClients) Bytes() []byte            { return p.d }
func (p *ChatRoomClients) Len() int                 { return len(p.d) }

func (p *ChatRoomClients) ClientCount() byte         { return p.d[6] }
func (p *ChatRoomClients) SetClientCount(value byte) { p.d[6] = byte(value) }

func (p *ChatRoomClients) ClientsCount() int { return int(p.ClientCount()) }
func (p *ChatRoomClients) Clients(i int) *ChatClient {
	count := int(p.ClientCount())
	start := 8 + i*ChatClientLength
	if i < 0 || i >= count || start+ChatClientLength > len(p.d) {
		return nil
	}
	return AsChatClient(p.d[start:])
}

// ChatMessage (C1Header 0x04, Bidirectional)
type ChatMessage struct{ d []byte }

const ChatMessageHeaderType byte = 0xC1
const ChatMessageCode byte = 0x04

func NewChatMessage(size int) *ChatMessage {
	p := &ChatMessage{d: make([]byte, size)}
	setHeader(p.d, 0xC1, 0x04, -1)
	return p
}

func ChatMessageRequiredSize(contentLen int) int { return contentLen + 5 }

func AsChatMessage(buf []byte) *ChatMessage { return &ChatMessage{d: buf} }
func (p *ChatMessage) Bytes() []byte        { return p.d }
func (p *ChatMessage) Len() int             { return len(p.d) }

func (p *ChatMessage) SenderIndex() byte         { return p.d[3] }
func (p *ChatMessage) SetSenderIndex(value byte) { p.d[3] = byte(value) }

func (p *ChatMessage) MessageLength() byte         { return p.d[4] }
func (p *ChatMessage) SetMessageLength(value byte) { p.d[4] = byte(value) }

func (p *ChatMessage) Message() []byte { return p.d[5:] }

// KeepAlive (C1Header 0x05, ClientToServer)
type KeepAlive struct{ d []byte }

const KeepAliveHeaderType byte = 0xC1
const KeepAliveCode byte = 0x05
const KeepAliveLength = 3

func NewKeepAlive() *KeepAlive {
	p := &KeepAlive{d: make([]byte, KeepAliveLength)}
	setHeader(p.d, 0xC1, 0x05, -1)
	return p
}

func AsKeepAlive(buf []byte) *KeepAlive { return &KeepAlive{d: buf} }
func (p *KeepAlive) Bytes() []byte      { return p.d }
func (p *KeepAlive) Len() int           { return len(p.d) }
