// Code generated by muprotogen from MUnique.OpenMU.Network.Packets 0.9.10; DO NOT EDIT.

package chat

// RouteKey 是包分发表的键，对应线上帧头。
type RouteKey struct {
	Header byte
	Code   byte
	HasSub bool
	Sub    byte
}

// PacketInfo 描述一个已注册包的静态信息。
type PacketInfo struct {
	Name      string
	Direction string
	Fixed     bool
	Length    int
}

type routeEntry struct {
	Key  RouteKey
	Info PacketInfo
}

var routes = []routeEntry{
	{RouteKey{0xC1, 0x00, false, 0x00}, PacketInfo{"Authenticate", "ClientToServer", true, 16}},
	{RouteKey{0xC1, 0x01, false, 0x00}, PacketInfo{"LeaveChatRoom", "ClientToServer", true, 3}},
	{RouteKey{0xC1, 0x01, true, 0x00}, PacketInfo{"ChatRoomClientJoined", "ServerToClient", true, 15}},
	{RouteKey{0xC1, 0x01, true, 0x01}, PacketInfo{"ChatRoomClientLeft", "ServerToClient", true, 15}},
	{RouteKey{0xC1, 0x04, false, 0x00}, PacketInfo{"ChatMessage", "Bidirectional", false, 0}},
	{RouteKey{0xC1, 0x05, false, 0x00}, PacketInfo{"KeepAlive", "ClientToServer", true, 3}},
	{RouteKey{0xC2, 0x02, false, 0x00}, PacketInfo{"ChatRoomClients", "ServerToClient", false, 0}},
}

// Lookup 按精确键查包；重复键返回最先注册的条目。
func Lookup(key RouteKey) (PacketInfo, bool) {
	for _, e := range routes {
		if e.Key == key {
			return e.Info, true
		}
	}
	return PacketInfo{}, false
}

// LookupPacket 直接从一帧原始字节判定路由（C1/C3 的 Code 在偏移2，C2/C4 在偏移3）。
// 同时存在带/不带 SubCode 的条目时，优先匹配带 SubCode 的精确键。
func LookupPacket(buf []byte) (PacketInfo, bool) {
	if len(buf) < 3 {
		return PacketInfo{}, false
	}
	header := buf[0]
	codeIdx := 2
	if header == 0xC2 || header == 0xC4 {
		codeIdx = 3
	}
	if len(buf) <= codeIdx {
		return PacketInfo{}, false
	}
	code := buf[codeIdx]
	if len(buf) > codeIdx+1 {
		if info, ok := Lookup(RouteKey{header, code, true, buf[codeIdx+1]}); ok {
			return info, true
		}
	}
	return Lookup(RouteKey{header, code, false, 0})
}
