// Code generated by muprotogen from MUnique.OpenMU.Network.Packets 0.9.10; DO NOT EDIT.

package chat

// ChatClient Contains the index and the name of a connected chat client in the room.
type ChatClient struct{ d []byte }

const ChatClientLength = 11

func AsChatClient(buf []byte) *ChatClient { return &ChatClient{d: buf} }
func (s *ChatClient) Bytes() []byte       { return s.d }
func (s *ChatClient) Len() int            { return len(s.d) }

func (s *ChatClient) Index() byte         { return s.d[0] }
func (s *ChatClient) SetIndex(value byte) { s.d[0] = byte(value) }

func (s *ChatClient) Name() []byte         { return cstring(s.d[1:11]) }
func (s *ChatClient) NameString() string   { return string(cstring(s.d[1:11])) }
func (s *ChatClient) SetName(value string) { writeCString(s.d[1:11], value) }
