// Code generated by muprotogen; DO NOT EDIT.

package connect

import "testing"

func TestFixedPacketsLayout(t *testing.T) {
	cases := []struct {
		name   string
		size   int
		header byte
		code   byte
		hasSub bool
		sub    byte
		mk     func() []byte
	}{
		{"ConnectionInfoRequest075", 5, 0xC1, 0xF4, true, 0x03, func() []byte { return NewConnectionInfoRequest075().Bytes() }},
		{"ConnectionInfoRequest", 6, 0xC1, 0xF4, true, 0x03, func() []byte { return NewConnectionInfoRequest().Bytes() }},
		{"ConnectionInfo", 22, 0xC1, 0xF4, true, 0x03, func() []byte { return NewConnectionInfo().Bytes() }},
		{"ServerListRequest", 4, 0xC1, 0xF4, true, 0x06, func() []byte { return NewServerListRequest().Bytes() }},
		{"ServerListRequestOld", 4, 0xC1, 0xF4, true, 0x02, func() []byte { return NewServerListRequestOld().Bytes() }},
		{"Hello", 4, 0xC1, 0x00, true, 0x01, func() []byte { return NewHello().Bytes() }},
		{"PatchCheckRequest", 6, 0xC1, 0x02, false, 0x00, func() []byte { return NewPatchCheckRequest().Bytes() }},
		{"PatchVersionOkay", 4, 0xC1, 0x02, false, 0x00, func() []byte { return NewPatchVersionOkay().Bytes() }},
		{"ClientNeedsPatch", 138, 0xC1, 0x05, true, 0x01, func() []byte { return NewClientNeedsPatch().Bytes() }},
	}
	for _, tc := range cases {
		buf := tc.mk()
		if len(buf) != tc.size {
			t.Errorf("%s: got %d bytes, want %d", tc.name, len(buf), tc.size)
		}
		if buf[0] != tc.header {
			t.Errorf("%s: header 0x%02X, want 0x%02X", tc.name, buf[0], tc.header)
		}
		codeIdx := 2
		if tc.header == 0xC2 || tc.header == 0xC4 {
			codeIdx = 3
		}
		if buf[codeIdx] != tc.code {
			t.Errorf("%s: code 0x%02X, want 0x%02X", tc.name, buf[codeIdx], tc.code)
		}
		if tc.hasSub && buf[codeIdx+1] != tc.sub {
			t.Errorf("%s: sub 0x%02X, want 0x%02X", tc.name, buf[codeIdx+1], tc.sub)
		}
	}
}

func TestFixedStructSizes(t *testing.T) {
	cases := []struct {
		name string
		size int
		mk   func() []byte
	}{
		{"ServerLoadInfo", 4, func() []byte { b := make([]byte, ServerLoadInfoLength); _ = AsServerLoadInfo(b); return b }},
		{"ServerLoadInfo2", 2, func() []byte { b := make([]byte, ServerLoadInfo2Length); _ = AsServerLoadInfo2(b); return b }},
	}
	for _, tc := range cases {
		if len(tc.mk()) != tc.size {
			t.Errorf("%s: size mismatch", tc.name)
		}
	}
}
