// Code generated by muprotogen from MUnique.OpenMU.Network.Packets 0.9.10; DO NOT EDIT.

package connect

// ItemStorageKind Defines from or to which item storage an item is moved.
type ItemStorageKind uint16

const (
	// ItemStorageKind_Inventory The inventory storage.
	ItemStorageKind_Inventory ItemStorageKind = 0
	// ItemStorageKind_Trade The trade storage.
	ItemStorageKind_Trade ItemStorageKind = 1
	// ItemStorageKind_Vault The vault storage.
	ItemStorageKind_Vault ItemStorageKind = 2
	// ItemStorageKind_ChaosMachine The chaos machine storage.
	ItemStorageKind_ChaosMachine ItemStorageKind = 3
	// ItemStorageKind_PlayerShop The player shop storage.
	ItemStorageKind_PlayerShop ItemStorageKind = 4
	// ItemStorageKind_PetTrainer The pet trainer dialog storage.
	ItemStorageKind_PetTrainer ItemStorageKind = 5
	// ItemStorageKind_Refinery The storage of the refinery of the elphis npc.
	ItemStorageKind_Refinery ItemStorageKind = 6
	// ItemStorageKind_Smelting The storage of the smelting dialog of the osbourne npc.
	ItemStorageKind_Smelting ItemStorageKind = 7
	// ItemStorageKind_ItemRestore The storage of the item restore dialog of the jerridon npc.
	ItemStorageKind_ItemRestore ItemStorageKind = 8
	// ItemStorageKind_ChaosCardMaster The storage of the chaos card master dialog.
	ItemStorageKind_ChaosCardMaster ItemStorageKind = 9
	// ItemStorageKind_CherryBlossomSpirit The storage of the cherry blossom spirit dialog.
	ItemStorageKind_CherryBlossomSpirit ItemStorageKind = 10
	// ItemStorageKind_SeedCrafting The storage of the seed crafting dialog.
	ItemStorageKind_SeedCrafting ItemStorageKind = 11
	// ItemStorageKind_SeedSphereCrafting The storage of the seed sphere crafting dialog.
	ItemStorageKind_SeedSphereCrafting ItemStorageKind = 12
	// ItemStorageKind_SeedMountCrafting The storage of the seed sphere mount dialog.
	ItemStorageKind_SeedMountCrafting ItemStorageKind = 13
	// ItemStorageKind_SeedUnmountCrafting The storage of the seed sphere unmount dialog.
	ItemStorageKind_SeedUnmountCrafting ItemStorageKind = 14
)

// LegacyQuestState The quest state for the legacy quest system.
type LegacyQuestState uint16

const (
	// LegacyQuestState_Undefined The state is undefined. This value is used when there is no quest defined for a specific index
	LegacyQuestState_Undefined LegacyQuestState = 0
	// LegacyQuestState_Active The quest is active and in progress.
	LegacyQuestState_Active LegacyQuestState = 1
	// LegacyQuestState_Complete The quest was completed.
	LegacyQuestState_Complete LegacyQuestState = 2
	// LegacyQuestState_Inactive The quest is inactive, that means it isn't active and wasn't completed yet.
	LegacyQuestState_Inactive LegacyQuestState = 3
)

// CharacterClassNumber Defines the values which are used for the character classes on client side.
type CharacterClassNumber uint16

const (
	// CharacterClassNumber_DarkWizard Value for the dark wizard character class.
	CharacterClassNumber_DarkWizard CharacterClassNumber = 0
	// CharacterClassNumber_SoulMaster Value for the soul master character class.
	CharacterClassNumber_SoulMaster CharacterClassNumber = 2
	// CharacterClassNumber_GrandMaster Value for the grand master character class.
	CharacterClassNumber_GrandMaster CharacterClassNumber = 3
	// CharacterClassNumber_DarkKnight Value for the dark knight character class.
	CharacterClassNumber_DarkKnight CharacterClassNumber = 4
	// CharacterClassNumber_BladeKnight Value for the blade knight character class.
	CharacterClassNumber_BladeKnight CharacterClassNumber = 6
	// CharacterClassNumber_BladeMaster Value for the blade master character class.
	CharacterClassNumber_BladeMaster CharacterClassNumber = 7
	// CharacterClassNumber_FairyElf Value for the fairy elf character class.
	CharacterClassNumber_FairyElf CharacterClassNumber = 8
	// CharacterClassNumber_MuseElf Value for the muse elf character class.
	CharacterClassNumber_MuseElf CharacterClassNumber = 10
	// CharacterClassNumber_HighElf Value for the high elf character class.
	CharacterClassNumber_HighElf CharacterClassNumber = 11
	// CharacterClassNumber_MagicGladiator Value for the magic gladiator character class.
	CharacterClassNumber_MagicGladiator CharacterClassNumber = 12
	// CharacterClassNumber_DuelMaster Value for the duel master character class.
	CharacterClassNumber_DuelMaster CharacterClassNumber = 13
	// CharacterClassNumber_DarkLord Value for the dark lord character class.
	CharacterClassNumber_DarkLord CharacterClassNumber = 16
	// CharacterClassNumber_LordEmperor Value for the lord emperor character class.
	CharacterClassNumber_LordEmperor CharacterClassNumber = 17
	// CharacterClassNumber_Summoner Value for the summoner character class.
	CharacterClassNumber_Summoner CharacterClassNumber = 20
	// CharacterClassNumber_BloodySummoner Value for the bloody summoner character class.
	CharacterClassNumber_BloodySummoner CharacterClassNumber = 22
	// CharacterClassNumber_DimensionMaster Value for the dimension master character class.
	CharacterClassNumber_DimensionMaster CharacterClassNumber = 23
	// CharacterClassNumber_RageFighter Value for the rage fighter character class.
	CharacterClassNumber_RageFighter CharacterClassNumber = 24
	// CharacterClassNumber_FistMaster Value for the fist master character class.
	CharacterClassNumber_FistMaster CharacterClassNumber = 25
)

// CharacterStatAttribute Defines the type of a character stat attribute.
type CharacterStatAttribute uint16

const (
	// CharacterStatAttribute_Strength The strength attribute.
	CharacterStatAttribute_Strength CharacterStatAttribute = 0
	// CharacterStatAttribute_Agility The agility attribute.
	CharacterStatAttribute_Agility CharacterStatAttribute = 1
	// CharacterStatAttribute_Vitality The vitality attribute.
	CharacterStatAttribute_Vitality CharacterStatAttribute = 2
	// CharacterStatAttribute_Energy The energy attribute.
	CharacterStatAttribute_Energy CharacterStatAttribute = 3
	// CharacterStatAttribute_Leadership The leadership attribute.
	CharacterStatAttribute_Leadership CharacterStatAttribute = 4
)

// CharacterHeroState Defines the hero state of a character.
type CharacterHeroState uint16

const (
	// CharacterHeroState_New The character is new and has the highest state.
	CharacterHeroState_New CharacterHeroState = 0
	// CharacterHeroState_Hero The character is a hero.
	CharacterHeroState_Hero CharacterHeroState = 1
	// CharacterHeroState_LightHero The character is a hero, but the state is almost gone.
	CharacterHeroState_LightHero CharacterHeroState = 2
	// CharacterHeroState_Normal The character is in a neutral state.
	CharacterHeroState_Normal CharacterHeroState = 3
	// CharacterHeroState_PlayerKillWarning The character killed another character, and has a kill warning.
	CharacterHeroState_PlayerKillWarning CharacterHeroState = 4
	// CharacterHeroState_PlayerKiller1stStage The character killed two characters, and has some restrictions.
	CharacterHeroState_PlayerKiller1stStage CharacterHeroState = 5
	// CharacterHeroState_PlayerKiller2ndStage The character killed more than two characters, and has hard restrictions.
	CharacterHeroState_PlayerKiller2ndStage CharacterHeroState = 6
)

// LogOutType Describes the way how the player wants to leave the current game.
type LogOutType uint16

const (
	// LogOutType_CloseGame The player wants to close the game.
	LogOutType_CloseGame LogOutType = 0
	// LogOutType_BackToCharacterSelection The player wants to go back to the character selection screen.
	LogOutType_BackToCharacterSelection LogOutType = 1
	// LogOutType_BackToServerSelection The player wants to go back to the server selection screen.
	LogOutType_BackToServerSelection LogOutType = 2
)

// MiniGameType Defines the type of the mini game.
type MiniGameType uint16

const (
	// MiniGameType_Undefined Undefined mini game type.
	MiniGameType_Undefined MiniGameType = 0
	// MiniGameType_DevilSquare The devil square mini game.
	MiniGameType_DevilSquare MiniGameType = 1
	// MiniGameType_BloodCastle The blood castle mini game.
	MiniGameType_BloodCastle MiniGameType = 2
	// MiniGameType_CursedTemple The cursed temple mini game.
	MiniGameType_CursedTemple MiniGameType = 3
	// MiniGameType_ChaosCastle The chaos castle mini game.
	MiniGameType_ChaosCastle MiniGameType = 4
	// MiniGameType_IllusionTemple The illusion temple mini game.
	MiniGameType_IllusionTemple MiniGameType = 5
	// MiniGameType_Doppelganger The doppelgänger mini game.
	MiniGameType_Doppelganger MiniGameType = 6
)
