// Code generated by muprotogen from MUnique.OpenMU.Network.Packets 0.9.10; DO NOT EDIT.

package connect

// ConnectionInfoRequest075 (C1HeaderWithSubCode 0xF4 0x03, ClientToServer)
type ConnectionInfoRequest075 struct{ d []byte }

const ConnectionInfoRequest075HeaderType byte = 0xC1
const ConnectionInfoRequest075Code byte = 0xF4
const ConnectionInfoRequest075SubCode byte = 0x03
const ConnectionInfoRequest075Length = 5

func NewConnectionInfoRequest075() *ConnectionInfoRequest075 {
	p := &ConnectionInfoRequest075{d: make([]byte, ConnectionInfoRequest075Length)}
	setHeader(p.d, 0xC1, 0xF4, 3)
	return p
}

func AsConnectionInfoRequest075(buf []byte) *ConnectionInfoRequest075 {
	return &ConnectionInfoRequest075{d: buf}
}
func (p *ConnectionInfoRequest075) Bytes() []byte { return p.d }
func (p *ConnectionInfoRequest075) Len() int      { return len(p.d) }

func (p *ConnectionInfoRequest075) ServerId() byte         { return p.d[4] }
func (p *ConnectionInfoRequest075) SetServerId(value byte) { p.d[4] = byte(value) }

// ConnectionInfoRequest (C1HeaderWithSubCode 0xF4 0x03, ClientToServer)
type ConnectionInfoRequest struct{ d []byte }

const ConnectionInfoRequestHeaderType byte = 0xC1
const ConnectionInfoRequestCode byte = 0xF4
const ConnectionInfoRequestSubCode byte = 0x03
const ConnectionInfoRequestLength = 6

func NewConnectionInfoRequest() *ConnectionInfoRequest {
	p := &ConnectionInfoRequest{d: make([]byte, ConnectionInfoRequestLength)}
	setHeader(p.d, 0xC1, 0xF4, 3)
	return p
}

func AsConnectionInfoRequest(buf []byte) *ConnectionInfoRequest {
	return &ConnectionInfoRequest{d: buf}
}
func (p *ConnectionInfoRequest) Bytes() []byte { return p.d }
func (p *ConnectionInfoRequest) Len() int      { return len(p.d) }

func (p *ConnectionInfoRequest) ServerId() uint16         { return getU16LE(p.d[4:]) }
func (p *ConnectionInfoRequest) SetServerId(value uint16) { setU16LE(p.d[4:], value) }

// ConnectionInfo (C1HeaderWithSubCode 0xF4 0x03, ServerToClient)
type ConnectionInfo struct{ d []byte }

const ConnectionInfoHeaderType byte = 0xC1
const ConnectionInfoCode byte = 0xF4
const ConnectionInfoSubCode byte = 0x03
const ConnectionInfoLength = 22

func NewConnectionInfo() *ConnectionInfo {
	p := &ConnectionInfo{d: make([]byte, ConnectionInfoLength)}
	setHeader(p.d, 0xC1, 0xF4, 3)
	return p
}

func AsConnectionInfo(buf []byte) *ConnectionInfo { return &ConnectionInfo{d: buf} }
func (p *ConnectionInfo) Bytes() []byte           { return p.d }
func (p *ConnectionInfo) Len() int                { return len(p.d) }

func (p *ConnectionInfo) IpAddress() []byte         { return cstring(p.d[4:20]) }
func (p *ConnectionInfo) IpAddressString() string   { return string(cstring(p.d[4:20])) }
func (p *ConnectionInfo) SetIpAddress(value string) { writeCString(p.d[4:20], value) }

func (p *ConnectionInfo) Port() uint16         { return getU16LE(p.d[20:]) }
func (p *ConnectionInfo) SetPort(value uint16) { setU16LE(p.d[20:], value) }

// ServerListRequest (C1HeaderWithSubCode 0xF4 0x06, ClientToServer)
type ServerListRequest struct{ d []byte }

const ServerListRequestHeaderType byte = 0xC1
const ServerListRequestCode byte = 0xF4
const ServerListRequestSubCode byte = 0x06
const ServerListRequestLength = 4

func NewServerListRequest() *ServerListRequest {
	p := &ServerListRequest{d: make([]byte, ServerListRequestLength)}
	setHeader(p.d, 0xC1, 0xF4, 6)
	return p
}

func AsServerListRequest(buf []byte) *ServerListRequest { return &ServerListRequest{d: buf} }
func (p *ServerListRequest) Bytes() []byte              { return p.d }
func (p *ServerListRequest) Len() int                   { return len(p.d) }

// ServerListResponse (C2HeaderWithSubCode 0xF4 0x06, ServerToClient)
type ServerListResponse struct{ d []byte }

const ServerListResponseHeaderType byte = 0xC2
const ServerListResponseCode byte = 0xF4
const ServerListResponseSubCode byte = 0x06

func NewServerListResponse(size int) *ServerListResponse {
	p := &ServerListResponse{d: make([]byte, size)}
	setHeader(p.d, 0xC2, 0xF4, 6)
	return p
}

func ServerListResponseRequiredSize(count int) int { return count*ServerLoadInfoLength + 7 }

func AsServerListResponse(buf []byte) *ServerListResponse { return &ServerListResponse{d: buf} }
func (p *ServerListResponse) Bytes() []byte               { return p.d }
func (p *ServerListResponse) Len() int                    { return len(p.d) }

func (p *ServerListResponse) ServerCount() uint16         { return getU16BE(p.d[5:]) }
func (p *ServerListResponse) SetServerCount(value uint16) { setU16BE(p.d[5:], value) }

func (p *ServerListResponse) ServersCount() int { return (len(p.d) - 7) / ServerLoadInfoLength }
func (p *ServerListResponse) Servers(i int) *ServerLoadInfo {
	count := (len(p.d) - 7) / ServerLoadInfoLength
	start := 7 + i*ServerLoadInfoLength
	if i < 0 || i >= count || start+ServerLoadInfoLength > len(p.d) {
		return nil
	}
	return AsServerLoadInfo(p.d[start:])
}

// ServerListRequestOld (C1HeaderWithSubCode 0xF4 0x02, ClientToServer)
type ServerListRequestOld struct{ d []byte }

const ServerListRequestOldHeaderType byte = 0xC1
const ServerListRequestOldCode byte = 0xF4
const ServerListRequestOldSubCode byte = 0x02
const ServerListRequestOldLength = 4

func NewServerListRequestOld() *ServerListRequestOld {
	p := &ServerListRequestOld{d: make([]byte, ServerListRequestOldLength)}
	setHeader(p.d, 0xC1, 0xF4, 2)
	return p
}

func AsServerListRequestOld(buf []byte) *ServerListRequestOld { return &ServerListRequestOld{d: buf} }
func (p *ServerListRequestOld) Bytes() []byte                 { return p.d }
func (p *ServerListRequestOld) Len() int                      { return len(p.d) }

// ServerListResponseOld (C2HeaderWithSubCode 0xF4 0x02, ServerToClient)
type ServerListResponseOld struct{ d []byte }

const ServerListResponseOldHeaderType byte = 0xC2
const ServerListResponseOldCode byte = 0xF4
const ServerListResponseOldSubCode byte = 0x02

func NewServerListResponseOld(size int) *ServerListResponseOld {
	p := &ServerListResponseOld{d: make([]byte, size)}
	setHeader(p.d, 0xC2, 0xF4, 2)
	return p
}

func ServerListResponseOldRequiredSize(count int) int { return count*ServerLoadInfo2Length + 6 }

func AsServerListResponseOld(buf []byte) *ServerListResponseOld {
	return &ServerListResponseOld{d: buf}
}
func (p *ServerListResponseOld) Bytes() []byte { return p.d }
func (p *ServerListResponseOld) Len() int      { return len(p.d) }

func (p *ServerListResponseOld) ServerCount() byte         { return p.d[5] }
func (p *ServerListResponseOld) SetServerCount(value byte) { p.d[5] = byte(value) }

func (p *ServerListResponseOld) ServersCount() int { return (len(p.d) - 6) / ServerLoadInfo2Length }
func (p *ServerListResponseOld) Servers(i int) *ServerLoadInfo2 {
	count := (len(p.d) - 6) / ServerLoadInfo2Length
	start := 6 + i*ServerLoadInfo2Length
	if i < 0 || i >= count || start+ServerLoadInfo2Length > len(p.d) {
		return nil
	}
	return AsServerLoadInfo2(p.d[start:])
}

// Hello (C1HeaderWithSubCode 0x00 0x01, ServerToClient)
type Hello struct{ d []byte }

const HelloHeaderType byte = 0xC1
const HelloCode byte = 0x00
const HelloSubCode byte = 0x01
const HelloLength = 4

func NewHello() *Hello {
	p := &Hello{d: make([]byte, HelloLength)}
	setHeader(p.d, 0xC1, 0x00, 1)
	return p
}

func AsHello(buf []byte) *Hello { return &Hello{d: buf} }
func (p *Hello) Bytes() []byte  { return p.d }
func (p *Hello) Len() int       { return len(p.d) }

// PatchCheckRequest (C1Header 0x02, ClientToServer)
type PatchCheckRequest struct{ d []byte }

const PatchCheckRequestHeaderType byte = 0xC1
const PatchCheckRequestCode byte = 0x02
const PatchCheckRequestLength = 6

func NewPatchCheckRequest() *PatchCheckRequest {
	p := &PatchCheckRequest{d: make([]byte, PatchCheckRequestLength)}
	setHeader(p.d, 0xC1, 0x02, -1)
	return p
}

func AsPatchCheckRequest(buf []byte) *PatchCheckRequest { return &PatchCheckRequest{d: buf} }
func (p *PatchCheckRequest) Bytes() []byte              { return p.d }
func (p *PatchCheckRequest) Len() int                   { return len(p.d) }

func (p *PatchCheckRequest) MajorVersion() byte         { return p.d[3] }
func (p *PatchCheckRequest) SetMajorVersion(value byte) { p.d[3] = byte(value) }

func (p *PatchCheckRequest) MinorVersion() byte         { return p.d[4] }
func (p *PatchCheckRequest) SetMinorVersion(value byte) { p.d[4] = byte(value) }

func (p *PatchCheckRequest) PatchVersion() byte         { return p.d[5] }
func (p *PatchCheckRequest) SetPatchVersion(value byte) { p.d[5] = byte(value) }

// PatchVersionOkay (C1Header 0x02, ServerToClient)
type PatchVersionOkay struct{ d []byte }

const PatchVersionOkayHeaderType byte = 0xC1
const PatchVersionOkayCode byte = 0x02
const PatchVersionOkayLength = 4

func NewPatchVersionOkay() *PatchVersionOkay {
	p := &PatchVersionOkay{d: make([]byte, PatchVersionOkayLength)}
	setHeader(p.d, 0xC1, 0x02, -1)
	return p
}

func AsPatchVersionOkay(buf []byte) *PatchVersionOkay { return &PatchVersionOkay{d: buf} }
func (p *PatchVersionOkay) Bytes() []byte             { return p.d }
func (p *PatchVersionOkay) Len() int                  { return len(p.d) }

// ClientNeedsPatch (C1HeaderWithSubCode 0x05 0x1, ServerToClient)
type ClientNeedsPatch struct{ d []byte }

const ClientNeedsPatchHeaderType byte = 0xC1
const ClientNeedsPatchCode byte = 0x05
const ClientNeedsPatchSubCode byte = 0x01
const ClientNeedsPatchLength = 138

func NewClientNeedsPatch() *ClientNeedsPatch {
	p := &ClientNeedsPatch{d: make([]byte, ClientNeedsPatchLength)}
	setHeader(p.d, 0xC1, 0x05, 1)
	return p
}

func ClientNeedsPatchRequiredSize(contentBytes int) int { return contentBytes + 1 + 6 }

func AsClientNeedsPatch(buf []byte) *ClientNeedsPatch { return &ClientNeedsPatch{d: buf} }
func (p *ClientNeedsPatch) Bytes() []byte             { return p.d }
func (p *ClientNeedsPatch) Len() int                  { return len(p.d) }

func (p *ClientNeedsPatch) PatchVersion() byte         { return p.d[4] }
func (p *ClientNeedsPatch) SetPatchVersion(value byte) { p.d[4] = byte(value) }

func (p *ClientNeedsPatch) PatchAddress() []byte         { return cstring(p.d[6:]) }
func (p *ClientNeedsPatch) PatchAddressString() string   { return string(cstring(p.d[6:])) }
func (p *ClientNeedsPatch) SetPatchAddress(value string) { writeCString(p.d[6:], value) }
