// Code generated by muprotogen from MUnique.OpenMU.Network.Packets 0.9.10; DO NOT EDIT.

package connect

// ServerLoadInfo Contains the id and the load of a server.
type ServerLoadInfo struct{ d []byte }

const ServerLoadInfoLength = 4

func AsServerLoadInfo(buf []byte) *ServerLoadInfo { return &ServerLoadInfo{d: buf} }
func (s *ServerLoadInfo) Bytes() []byte           { return s.d }
func (s *ServerLoadInfo) Len() int                { return len(s.d) }

func (s *ServerLoadInfo) ServerId() uint16         { return getU16LE(s.d[0:]) }
func (s *ServerLoadInfo) SetServerId(value uint16) { setU16LE(s.d[0:], value) }

func (s *ServerLoadInfo) LoadPercentage() byte         { return s.d[2] }
func (s *ServerLoadInfo) SetLoadPercentage(value byte) { s.d[2] = byte(value) }

// ServerLoadInfo2 Contains the id and the load of a server.
type ServerLoadInfo2 struct{ d []byte }

const ServerLoadInfo2Length = 2

func AsServerLoadInfo2(buf []byte) *ServerLoadInfo2 { return &ServerLoadInfo2{d: buf} }
func (s *ServerLoadInfo2) Bytes() []byte            { return s.d }
func (s *ServerLoadInfo2) Len() int                 { return len(s.d) }

func (s *ServerLoadInfo2) ServerId() byte         { return s.d[0] }
func (s *ServerLoadInfo2) SetServerId(value byte) { s.d[0] = byte(value) }

func (s *ServerLoadInfo2) LoadPercentage() byte         { return s.d[1] }
func (s *ServerLoadInfo2) SetLoadPercentage(value byte) { s.d[1] = byte(value) }
