package main

import (
	"fmt"
	"strings"
)

// emitTests 输出长度/布局断言与代表性行为测试。
func (g *generator) emitTests() (string, error) {
	var b strings.Builder
	b.WriteString("// Code generated by muprotogen; DO NOT EDIT.\n\n")
	b.WriteString("package " + g.target.Package + "\n\n")
	b.WriteString("import \"testing\"\n\n")

	// 定长包：长度、类型、Code（及 SubCode）必须与 XML 声明一致。
	b.WriteString("func TestFixedPacketsLayout(t *testing.T) {\n")
	b.WriteString("\tcases := []struct {\n\t\tname   string\n\t\tsize   int\n\t\theader byte\n\t\tcode   byte\n\t\thasSub bool\n\t\tsub    byte\n\t\tmk     func() []byte\n\t}{\n")
	for _, p := range g.fixedPackets {
		fmt.Fprintf(&b, "\t\t{%q, %d, 0x%02X, 0x%02X, %t, 0x%02X, func() []byte { return New%s().Bytes() }},\n",
			p.goName, p.size, p.header, p.code, p.hasSub, p.sub, p.goName)
	}
	b.WriteString("\t}\n")
	b.WriteString("\tfor _, tc := range cases {\n")
	b.WriteString("\t\tbuf := tc.mk()\n")
	b.WriteString("\t\tif len(buf) != tc.size {\n\t\t\tt.Errorf(\"%s: got %d bytes, want %d\", tc.name, len(buf), tc.size)\n\t\t}\n")
	b.WriteString("\t\tif buf[0] != tc.header {\n\t\t\tt.Errorf(\"%s: header 0x%02X, want 0x%02X\", tc.name, buf[0], tc.header)\n\t\t}\n")
	b.WriteString("\t\tcodeIdx := 2\n\t\tif tc.header == 0xC2 || tc.header == 0xC4 {\n\t\t\tcodeIdx = 3\n\t\t}\n")
	b.WriteString("\t\tif buf[codeIdx] != tc.code {\n\t\t\tt.Errorf(\"%s: code 0x%02X, want 0x%02X\", tc.name, buf[codeIdx], tc.code)\n\t\t}\n")
	b.WriteString("\t\tif tc.hasSub && buf[codeIdx+1] != tc.sub {\n")
	b.WriteString("\t\t\tt.Errorf(\"%s: sub 0x%02X, want 0x%02X\", tc.name, buf[codeIdx+1], tc.sub)\n\t\t}\n")
	b.WriteString("\t}\n}\n\n")

	// 定长结构：const 长度可分配且视图可解析。
	b.WriteString("func TestFixedStructSizes(t *testing.T) {\n")
	b.WriteString("\tcases := []struct {\n\t\tname string\n\t\tsize int\n\t\tmk   func() []byte\n\t}{\n")
	for _, s := range g.fixedStructs {
		fmt.Fprintf(&b, "\t\t{%q, %d, func() []byte { b := make([]byte, %sLength); _ = As%s(b); return b }},\n",
			s.goName, s.size, s.goName, s.goName)
	}
	b.WriteString("\t}\n")
	b.WriteString("\tfor _, tc := range cases {\n")
	b.WriteString("\t\tif len(tc.mk()) != tc.size {\n\t\t\tt.Errorf(\"%s: size mismatch\", tc.name)\n\t\t}\n\t}\n}\n\n")

	// 位压缩代表包：Weather(高4位)/Variation(低4位) 共享偏移3。
	if name, ok := g.packetGo["WeatherStatusUpdate"]; ok {
		fmt.Fprintf(&b, "func Test%sBitPacking(t *testing.T) {\n", name)
		b.WriteString("\tp := New" + name + "()\n")
		b.WriteString("\tp.SetWeather(2)\n")
		b.WriteString("\tp.SetVariation(9)\n")
		b.WriteString("\tif p.d[3] != 0x29 {\n\t\tt.Fatalf(\"packed byte 0x%02X, want 0x29\", p.d[3])\n\t}\n")
		b.WriteString("\tif p.Weather() != 2 || p.Variation() != 9 {\n\t\tt.Fatalf(\"bit fields read back mismatch: %d %d\", p.Weather(), p.Variation())\n\t}\n}\n\n")
	}

	// 变长代表包：（游戏服）ChatMessage 尺寸 = 13 + UTF8字节数 + 1、code 0x00。
	// 聊天服包（target=chat）也有同名 ChatMessage，但布局不同（code 0x04、RequiredSize=content+5），
	// 这套游戏服硬编码断言不适用，故排除 chat 目标。
	if name, ok := g.packetGo["ChatMessage"]; ok && g.target.Package != "chat" {
		fmt.Fprintf(&b, "func Test%sVariableSize(t *testing.T) {\n", name)
		b.WriteString("\tsize := " + name + "RequiredSize(2)\n")
		b.WriteString("\tif size != 16 {\n\t\tt.Fatalf(\"required size %d, want 16\", size)\n\t}\n")
		b.WriteString("\tp := New" + name + "(size)\n")
		b.WriteString("\tif p.Len() != 16 || p.d[0] != 0xC1 || p.d[1] != 16 || p.d[2] != 0x00 {\n")
		b.WriteString("\t\tt.Fatalf(\"variable header mismatch: len=%d c1=%02x lenb=%d code=%02x\", p.Len(), p.d[0], p.d[1], p.d[2])\n\t}\n}\n\n")
	}
	return b.String(), nil
}
