// Code generated by muprotogen from MUnique.OpenMU.Network.Packets 0.9.10; DO NOT EDIT.

package s2c

// ItemStorageKind Defines from or to which item storage an item is moved.
type ItemStorageKind uint16

const (
	// ItemStorageKind_Inventory The inventory storage.
	ItemStorageKind_Inventory ItemStorageKind = 0
	// ItemStorageKind_Trade The trade storage.
	ItemStorageKind_Trade ItemStorageKind = 1
	// ItemStorageKind_Vault The vault storage.
	ItemStorageKind_Vault ItemStorageKind = 2
	// ItemStorageKind_ChaosMachine The chaos machine storage.
	ItemStorageKind_ChaosMachine ItemStorageKind = 3
	// ItemStorageKind_PlayerShop The player shop storage.
	ItemStorageKind_PlayerShop ItemStorageKind = 4
	// ItemStorageKind_PetTrainer The pet trainer dialog storage.
	ItemStorageKind_PetTrainer ItemStorageKind = 5
	// ItemStorageKind_Refinery The storage of the refinery of the elphis npc.
	ItemStorageKind_Refinery ItemStorageKind = 6
	// ItemStorageKind_Smelting The storage of the smelting dialog of the osbourne npc.
	ItemStorageKind_Smelting ItemStorageKind = 7
	// ItemStorageKind_ItemRestore The storage of the item restore dialog of the jerridon npc.
	ItemStorageKind_ItemRestore ItemStorageKind = 8
	// ItemStorageKind_ChaosCardMaster The storage of the chaos card master dialog.
	ItemStorageKind_ChaosCardMaster ItemStorageKind = 9
	// ItemStorageKind_CherryBlossomSpirit The storage of the cherry blossom spirit dialog.
	ItemStorageKind_CherryBlossomSpirit ItemStorageKind = 10
	// ItemStorageKind_SeedCrafting The storage of the seed crafting dialog.
	ItemStorageKind_SeedCrafting ItemStorageKind = 11
	// ItemStorageKind_SeedSphereCrafting The storage of the seed sphere crafting dialog.
	ItemStorageKind_SeedSphereCrafting ItemStorageKind = 12
	// ItemStorageKind_SeedMountCrafting The storage of the seed sphere mount dialog.
	ItemStorageKind_SeedMountCrafting ItemStorageKind = 13
	// ItemStorageKind_SeedUnmountCrafting The storage of the seed sphere unmount dialog.
	ItemStorageKind_SeedUnmountCrafting ItemStorageKind = 14
)

// LegacyQuestState The quest state for the legacy quest system.
type LegacyQuestState uint16

const (
	// LegacyQuestState_Undefined The state is undefined. This value is used when there is no quest defined for a specific index
	LegacyQuestState_Undefined LegacyQuestState = 0
	// LegacyQuestState_Active The quest is active and in progress.
	LegacyQuestState_Active LegacyQuestState = 1
	// LegacyQuestState_Complete The quest was completed.
	LegacyQuestState_Complete LegacyQuestState = 2
	// LegacyQuestState_Inactive The quest is inactive, that means it isn't active and wasn't completed yet.
	LegacyQuestState_Inactive LegacyQuestState = 3
)

// CharacterClassNumber Defines the values which are used for the character classes on client side.
type CharacterClassNumber uint16

const (
	// CharacterClassNumber_DarkWizard Value for the dark wizard character class.
	CharacterClassNumber_DarkWizard CharacterClassNumber = 0
	// CharacterClassNumber_SoulMaster Value for the soul master character class.
	CharacterClassNumber_SoulMaster CharacterClassNumber = 2
	// CharacterClassNumber_GrandMaster Value for the grand master character class.
	CharacterClassNumber_GrandMaster CharacterClassNumber = 3
	// CharacterClassNumber_DarkKnight Value for the dark knight character class.
	CharacterClassNumber_DarkKnight CharacterClassNumber = 4
	// CharacterClassNumber_BladeKnight Value for the blade knight character class.
	CharacterClassNumber_BladeKnight CharacterClassNumber = 6
	// CharacterClassNumber_BladeMaster Value for the blade master character class.
	CharacterClassNumber_BladeMaster CharacterClassNumber = 7
	// CharacterClassNumber_FairyElf Value for the fairy elf character class.
	CharacterClassNumber_FairyElf CharacterClassNumber = 8
	// CharacterClassNumber_MuseElf Value for the muse elf character class.
	CharacterClassNumber_MuseElf CharacterClassNumber = 10
	// CharacterClassNumber_HighElf Value for the high elf character class.
	CharacterClassNumber_HighElf CharacterClassNumber = 11
	// CharacterClassNumber_MagicGladiator Value for the magic gladiator character class.
	CharacterClassNumber_MagicGladiator CharacterClassNumber = 12
	// CharacterClassNumber_DuelMaster Value for the duel master character class.
	CharacterClassNumber_DuelMaster CharacterClassNumber = 13
	// CharacterClassNumber_DarkLord Value for the dark lord character class.
	CharacterClassNumber_DarkLord CharacterClassNumber = 16
	// CharacterClassNumber_LordEmperor Value for the lord emperor character class.
	CharacterClassNumber_LordEmperor CharacterClassNumber = 17
	// CharacterClassNumber_Summoner Value for the summoner character class.
	CharacterClassNumber_Summoner CharacterClassNumber = 20
	// CharacterClassNumber_BloodySummoner Value for the bloody summoner character class.
	CharacterClassNumber_BloodySummoner CharacterClassNumber = 22
	// CharacterClassNumber_DimensionMaster Value for the dimension master character class.
	CharacterClassNumber_DimensionMaster CharacterClassNumber = 23
	// CharacterClassNumber_RageFighter Value for the rage fighter character class.
	CharacterClassNumber_RageFighter CharacterClassNumber = 24
	// CharacterClassNumber_FistMaster Value for the fist master character class.
	CharacterClassNumber_FistMaster CharacterClassNumber = 25
)

// CharacterStatAttribute Defines the type of a character stat attribute.
type CharacterStatAttribute uint16

const (
	// CharacterStatAttribute_Strength The strength attribute.
	CharacterStatAttribute_Strength CharacterStatAttribute = 0
	// CharacterStatAttribute_Agility The agility attribute.
	CharacterStatAttribute_Agility CharacterStatAttribute = 1
	// CharacterStatAttribute_Vitality The vitality attribute.
	CharacterStatAttribute_Vitality CharacterStatAttribute = 2
	// CharacterStatAttribute_Energy The energy attribute.
	CharacterStatAttribute_Energy CharacterStatAttribute = 3
	// CharacterStatAttribute_Leadership The leadership attribute.
	CharacterStatAttribute_Leadership CharacterStatAttribute = 4
)

// CharacterHeroState Defines the hero state of a character.
type CharacterHeroState uint16

const (
	// CharacterHeroState_New The character is new and has the highest state.
	CharacterHeroState_New CharacterHeroState = 0
	// CharacterHeroState_Hero The character is a hero.
	CharacterHeroState_Hero CharacterHeroState = 1
	// CharacterHeroState_LightHero The character is a hero, but the state is almost gone.
	CharacterHeroState_LightHero CharacterHeroState = 2
	// CharacterHeroState_Normal The character is in a neutral state.
	CharacterHeroState_Normal CharacterHeroState = 3
	// CharacterHeroState_PlayerKillWarning The character killed another character, and has a kill warning.
	CharacterHeroState_PlayerKillWarning CharacterHeroState = 4
	// CharacterHeroState_PlayerKiller1stStage The character killed two characters, and has some restrictions.
	CharacterHeroState_PlayerKiller1stStage CharacterHeroState = 5
	// CharacterHeroState_PlayerKiller2ndStage The character killed more than two characters, and has hard restrictions.
	CharacterHeroState_PlayerKiller2ndStage CharacterHeroState = 6
)

// LogOutType Describes the way how the player wants to leave the current game.
type LogOutType uint16

const (
	// LogOutType_CloseGame The player wants to close the game.
	LogOutType_CloseGame LogOutType = 0
	// LogOutType_BackToCharacterSelection The player wants to go back to the character selection screen.
	LogOutType_BackToCharacterSelection LogOutType = 1
	// LogOutType_BackToServerSelection The player wants to go back to the server selection screen.
	LogOutType_BackToServerSelection LogOutType = 2
)

// MiniGameType Defines the type of the mini game.
type MiniGameType uint16

const (
	// MiniGameType_Undefined Undefined mini game type.
	MiniGameType_Undefined MiniGameType = 0
	// MiniGameType_DevilSquare The devil square mini game.
	MiniGameType_DevilSquare MiniGameType = 1
	// MiniGameType_BloodCastle The blood castle mini game.
	MiniGameType_BloodCastle MiniGameType = 2
	// MiniGameType_CursedTemple The cursed temple mini game.
	MiniGameType_CursedTemple MiniGameType = 3
	// MiniGameType_ChaosCastle The chaos castle mini game.
	MiniGameType_ChaosCastle MiniGameType = 4
	// MiniGameType_IllusionTemple The illusion temple mini game.
	MiniGameType_IllusionTemple MiniGameType = 5
	// MiniGameType_Doppelganger The doppelgänger mini game.
	MiniGameType_Doppelganger MiniGameType = 6
)

// ClientToServerTradeButtonState The state of the trade button.
type ClientToServerTradeButtonState uint16

const (
	// ClientToServerTradeButtonState_Unchecked Trade button is not pressed. It means that the trade is not yet accepted by the trader.
	ClientToServerTradeButtonState_Unchecked ClientToServerTradeButtonState = 0
	// ClientToServerTradeButtonState_Checked Trade Button is pressed. It means that the trade is accepted by the trader.
	ClientToServerTradeButtonState_Checked ClientToServerTradeButtonState = 1
	// ClientToServerTradeButtonState_Red This state is only sent to the client. After some seconds the client is changing back to normal Unchecked.
	ClientToServerTradeButtonState_Red ClientToServerTradeButtonState = 2
)

// ClientToServerStorageType Describes the type of storage.
type ClientToServerStorageType uint16

const (
	// ClientToServerStorageType_Inventory The inventory of the player.
	ClientToServerStorageType_Inventory ClientToServerStorageType = 0
	// ClientToServerStorageType_Vault The vault of the player.
	ClientToServerStorageType_Vault ClientToServerStorageType = 1
	// ClientToServerStorageType_TradeOwn The own trading storage.
	ClientToServerStorageType_TradeOwn ClientToServerStorageType = 2
	// ClientToServerStorageType_TradeOther The trading storage of the other player.
	ClientToServerStorageType_TradeOther ClientToServerStorageType = 3
	// ClientToServerStorageType_Crafting The crafting storage of the player.
	ClientToServerStorageType_Crafting ClientToServerStorageType = 4
	// ClientToServerStorageType_PersonalShop The shop storage of another player.
	ClientToServerStorageType_PersonalShop ClientToServerStorageType = 5
	// ClientToServerStorageType_NpcShop The shop storage of an NPC (merchant).
	ClientToServerStorageType_NpcShop ClientToServerStorageType = 6
	// ClientToServerStorageType_InventoryPetSlot The inventory slot of the pet. That's used when a pet leveled up.
	ClientToServerStorageType_InventoryPetSlot ClientToServerStorageType = 254
)

// ClientToServerPetType Describes the type of pet.
type ClientToServerPetType uint16

const (
	// ClientToServerPetType_DarkRaven The dark raven pet.
	ClientToServerPetType_DarkRaven ClientToServerPetType = 0
	// ClientToServerPetType_DarkHorse The dark horse pet.
	ClientToServerPetType_DarkHorse ClientToServerPetType = 1
)

// ClientToServerPetCommandMode Describes the pet command mode.
type ClientToServerPetCommandMode uint16

const (
	// ClientToServerPetCommandMode_Normal The pet is in a normal mode, where it doesn't attack.
	ClientToServerPetCommandMode_Normal ClientToServerPetCommandMode = 0
	// ClientToServerPetCommandMode_AttackRandom The pet attacks random targets.
	ClientToServerPetCommandMode_AttackRandom ClientToServerPetCommandMode = 1
	// ClientToServerPetCommandMode_AttackWithOwner The pet attacks the same targets as the owner.
	ClientToServerPetCommandMode_AttackWithOwner ClientToServerPetCommandMode = 2
	// ClientToServerPetCommandMode_AttackTarget The pet attacks a specific target until it's dead.
	ClientToServerPetCommandMode_AttackTarget ClientToServerPetCommandMode = 3
)

// ClientToServerGensType Describes the gens type.
type ClientToServerGensType uint16

const (
	// ClientToServerGensType_Undefined The undefined gens type.
	ClientToServerGensType_Undefined ClientToServerGensType = 0
	// ClientToServerGensType_Duprian The Duprian gens.
	ClientToServerGensType_Duprian ClientToServerGensType = 1
	// ClientToServerGensType_Vanert The Vanert gens.
	ClientToServerGensType_Vanert ClientToServerGensType = 2
)

// ClientToServerGuildRelationshipType Describes the relationship type between guilds.
type ClientToServerGuildRelationshipType uint16

const (
	// ClientToServerGuildRelationshipType_Undefined The undefined relationship type.
	ClientToServerGuildRelationshipType_Undefined ClientToServerGuildRelationshipType = 0
	// ClientToServerGuildRelationshipType_Alliance The alliance relationship type.
	ClientToServerGuildRelationshipType_Alliance ClientToServerGuildRelationshipType = 1
	// ClientToServerGuildRelationshipType_Hostility The hostility relationship type.
	ClientToServerGuildRelationshipType_Hostility ClientToServerGuildRelationshipType = 2
)

// ClientToServerGuildRequestType Describes the request type.
type ClientToServerGuildRequestType uint16

const (
	// ClientToServerGuildRequestType_Undefined The undefined request type.
	ClientToServerGuildRequestType_Undefined ClientToServerGuildRequestType = 0
	// ClientToServerGuildRequestType_Join The join type.
	ClientToServerGuildRequestType_Join ClientToServerGuildRequestType = 1
	// ClientToServerGuildRequestType_Leave The leave type.
	ClientToServerGuildRequestType_Leave ClientToServerGuildRequestType = 2
)

// GuildMemberRole Defines the role of a guild member.
type GuildMemberRole uint16

const (
	// GuildMemberRole_NormalMember The member is a normal member without special rights.
	GuildMemberRole_NormalMember GuildMemberRole = 0
	// GuildMemberRole_BattleMaster The member is a battle master.
	GuildMemberRole_BattleMaster GuildMemberRole = 32
	// GuildMemberRole_AssistantMaster The member is the assistant guild master.
	GuildMemberRole_AssistantMaster GuildMemberRole = 64
	// GuildMemberRole_GuildMaster The member is the guild master.
	GuildMemberRole_GuildMaster GuildMemberRole = 128
	// GuildMemberRole_Undefined The character is not a member, therefore the role is undefined.
	GuildMemberRole_Undefined GuildMemberRole = 255
)

// GuildWarType Describes the type of the guild war.
type GuildWarType uint16

const (
	// GuildWarType_Normal A normal guild war.
	GuildWarType_Normal GuildWarType = 0
	// GuildWarType_Soccer A guild soccer match.
	GuildWarType_Soccer GuildWarType = 1
)

// GuildRelationshipType Describes the relationship type between guilds.
type GuildRelationshipType uint16

const (
	// GuildRelationshipType_Undefined The undefined relationship type.
	GuildRelationshipType_Undefined GuildRelationshipType = 0
	// GuildRelationshipType_Alliance The alliance relationship type.
	GuildRelationshipType_Alliance GuildRelationshipType = 1
	// GuildRelationshipType_Hostility The hostility relationship type.
	GuildRelationshipType_Hostility GuildRelationshipType = 2
)

// GuildRelationshipRequestType Describes the request type.
type GuildRelationshipRequestType uint16

const (
	// GuildRelationshipRequestType_Undefined The undefined request type.
	GuildRelationshipRequestType_Undefined GuildRelationshipRequestType = 0
	// GuildRelationshipRequestType_Join The join type.
	GuildRelationshipRequestType_Join GuildRelationshipRequestType = 1
	// GuildRelationshipRequestType_Leave The leave type.
	GuildRelationshipRequestType_Leave GuildRelationshipRequestType = 2
)

// CharacterStatus The status of a character.
type CharacterStatus uint16

const (
	// CharacterStatus_Normal The state of the character is normal.
	CharacterStatus_Normal CharacterStatus = 0
	// CharacterStatus_Banned The character is banned from the game.
	CharacterStatus_Banned CharacterStatus = 1
	// CharacterStatus_GameMaster The character is a game master.
	CharacterStatus_GameMaster CharacterStatus = 32
)

// ConditionType Defines the type of the condition.
type ConditionType uint16

const (
	// ConditionType_None No condition is defined.
	ConditionType_None ConditionType = 0
	// ConditionType_MonsterKills The condition is to kill a specified amount of specified monsters.
	ConditionType_MonsterKills ConditionType = 1
	// ConditionType_Skill The condition is to learn a specified skill.
	ConditionType_Skill ConditionType = 2
	// ConditionType_Item The condition is to find a specified item and to have it in the inventory.
	ConditionType_Item ConditionType = 4
	// ConditionType_Level The condition is to reach the specified character level.
	ConditionType_Level ConditionType = 8
	// ConditionType_ClientAction The condition is a client action. For example, this may be the completion of a tutorial.
	ConditionType_ClientAction ConditionType = 16
	// ConditionType_RequestBuff The condition is to request a buff from an NPC.
	ConditionType_RequestBuff ConditionType = 32
	// ConditionType_EventMapPlayerKills The condition is to kill a specific amount of players in an event.
	ConditionType_EventMapPlayerKills ConditionType = 64
	// ConditionType_EventMapMonsterKills The condition is to kill a specific amount of monsters in an event.
	ConditionType_EventMapMonsterKills ConditionType = 65
	// ConditionType_BloodCastleGate The condition is to destroy the blood castle gate.
	ConditionType_BloodCastleGate ConditionType = 66
	// ConditionType_WinBloodCastle The condition is to win the blood castle event.
	ConditionType_WinBloodCastle ConditionType = 256
	// ConditionType_WinChaosCastle The condition is to win the chaos castle.
	ConditionType_WinChaosCastle ConditionType = 257
	// ConditionType_WinDevilSquare The condition is to win the devil square event.
	ConditionType_WinDevilSquare ConditionType = 258
	// ConditionType_WinIllusionTemple The condition is to win the illusion temple event.
	ConditionType_WinIllusionTemple ConditionType = 259
	// ConditionType_DevilSquarePoints The condition is to reach a specific amount of points in the devil square event.
	ConditionType_DevilSquarePoints ConditionType = 260
	// ConditionType_Money The condition is to give a specific amount of zen.
	ConditionType_Money ConditionType = 261
	// ConditionType_PvpPoints The condition is to reach a specific amount of PVP points.
	ConditionType_PvpPoints ConditionType = 262
	// ConditionType_NpcTalk The condition is to talk to a specific NPC.
	ConditionType_NpcTalk ConditionType = 263
)

// ConditionTypeExtended Defines the type of the condition.
type ConditionTypeExtended uint16

const (
	// ConditionTypeExtended_None No condition is defined.
	ConditionTypeExtended_None ConditionTypeExtended = 0
	// ConditionTypeExtended_MonsterKills The condition is to kill a specified amount of specified monsters.
	ConditionTypeExtended_MonsterKills ConditionTypeExtended = 1
	// ConditionTypeExtended_Skill The condition is to learn a specified skill.
	ConditionTypeExtended_Skill ConditionTypeExtended = 2
	// ConditionTypeExtended_Item The condition is to find a specified item and to have it in the inventory.
	ConditionTypeExtended_Item ConditionTypeExtended = 3
	// ConditionTypeExtended_Level The condition is to reach the specified character level.
	ConditionTypeExtended_Level ConditionTypeExtended = 4
	// ConditionTypeExtended_ClientAction The condition is a client action. For example, this may be the completion of a tutorial.
	ConditionTypeExtended_ClientAction ConditionTypeExtended = 5
	// ConditionTypeExtended_RequestBuff The condition is to request a buff from an NPC.
	ConditionTypeExtended_RequestBuff ConditionTypeExtended = 6
	// ConditionTypeExtended_EventMapPlayerKills The condition is to kill a specific amount of players in an event.
	ConditionTypeExtended_EventMapPlayerKills ConditionTypeExtended = 7
	// ConditionTypeExtended_EventMapMonsterKills The condition is to kill a specific amount of monsters in an event.
	ConditionTypeExtended_EventMapMonsterKills ConditionTypeExtended = 8
	// ConditionTypeExtended_BloodCastleGate The condition is to destroy the blood castle gate.
	ConditionTypeExtended_BloodCastleGate ConditionTypeExtended = 9
	// ConditionTypeExtended_WinBloodCastle The condition is to win the blood castle event.
	ConditionTypeExtended_WinBloodCastle ConditionTypeExtended = 10
	// ConditionTypeExtended_WinChaosCastle The condition is to win the chaos castle.
	ConditionTypeExtended_WinChaosCastle ConditionTypeExtended = 11
	// ConditionTypeExtended_WinDevilSquare The condition is to win the devil square event.
	ConditionTypeExtended_WinDevilSquare ConditionTypeExtended = 12
	// ConditionTypeExtended_WinIllusionTemple The condition is to win the illusion temple event.
	ConditionTypeExtended_WinIllusionTemple ConditionTypeExtended = 13
	// ConditionTypeExtended_DevilSquarePoints The condition is to reach a specific amount of points in the devil square event.
	ConditionTypeExtended_DevilSquarePoints ConditionTypeExtended = 14
	// ConditionTypeExtended_Money The condition is to give a specific amount of zen.
	ConditionTypeExtended_Money ConditionTypeExtended = 15
	// ConditionTypeExtended_PvpPoints The condition is to reach a specific amount of PVP points.
	ConditionTypeExtended_PvpPoints ConditionTypeExtended = 16
	// ConditionTypeExtended_NpcTalk The condition is to talk to a specific NPC.
	ConditionTypeExtended_NpcTalk ConditionTypeExtended = 17
)

// RewardType Defines the reward which is given when the quest is completed.
type RewardType uint16

const (
	// RewardType_None No reward is defined.
	RewardType_None RewardType = 0
	// RewardType_Experience The reward is added experience to the character.
	RewardType_Experience RewardType = 1
	// RewardType_Money The reward is added money to the inventory.
	RewardType_Money RewardType = 2
	// RewardType_Item The reward is an item which is added to the inventory.
	RewardType_Item RewardType = 4
	// RewardType_GensContribution The reward is added gens contribution points.
	RewardType_GensContribution RewardType = 16
	// RewardType_Random The reward is random?.
	RewardType_Random RewardType = 32
)

// SocketOption Defines the possible socket options.
type SocketOption uint16

const (
	// SocketOption_FireAttackWizByLevelIncrease Fire((Level type)Attack/Wizardry increase +20)
	SocketOption_FireAttackWizByLevelIncrease SocketOption = 0
	// SocketOption_FireAttackSpeedIncrease Fire(Attack speed increase +7)
	SocketOption_FireAttackSpeedIncrease SocketOption = 1
	// SocketOption_FireMaxDmgIncrease Fire(Maximum attack/Wizardry increase +30)
	SocketOption_FireMaxDmgIncrease SocketOption = 2
	// SocketOption_FireMinDmgIncrease Fire(Minimum attack/Wizardry increase +20)
	SocketOption_FireMinDmgIncrease SocketOption = 3
	// SocketOption_FireAttackWizIncrease Fire(Attack/Wizardry increase +20)
	SocketOption_FireAttackWizIncrease SocketOption = 4
	// SocketOption_FireAgCostDecrease Fire(AG cost decrease +40)
	SocketOption_FireAgCostDecrease SocketOption = 5
	// SocketOption_WaterBlockRateIncrease Water(Block rating increase +10)
	SocketOption_WaterBlockRateIncrease SocketOption = 10
	// SocketOption_WaterDefenseIncrease Water(Defense increase +30)
	SocketOption_WaterDefenseIncrease SocketOption = 11
	// SocketOption_WaterShieldProtectionIncrease Water(Shield protection increase +7)
	SocketOption_WaterShieldProtectionIncrease SocketOption = 12
	// SocketOption_WaterDamageReduction4 Water(Damage reduction +4)
	SocketOption_WaterDamageReduction4 SocketOption = 13
	// SocketOption_WaterDamageReduction5 Water(Damage reduction +5)
	SocketOption_WaterDamageReduction5 SocketOption = 14
	// SocketOption_IceLifeIncrease Ice(Monster destruction for the Life increase +8)
	SocketOption_IceLifeIncrease SocketOption = 16
	// SocketOption_IceManaIncrease Ice(Monster destruction for the Mana increase +8)
	SocketOption_IceManaIncrease SocketOption = 17
	// SocketOption_IceSkillAttackIncrease Ice(Skill attack increase +37)
	SocketOption_IceSkillAttackIncrease SocketOption = 18
	// SocketOption_IceAttackRateIncrease Ice(Attack rating increase +25)
	SocketOption_IceAttackRateIncrease SocketOption = 19
	// SocketOption_IceDurabilityIncrease Ice(Item durability increase +30)
	SocketOption_IceDurabilityIncrease SocketOption = 20
	// SocketOption_WindAutoLifeRecoveryIncrease Wind(Automatic Life recovery increase +8)
	SocketOption_WindAutoLifeRecoveryIncrease SocketOption = 21
	// SocketOption_WindMaxHealthIncrease Wind(Maximum Life increase +4)
	SocketOption_WindMaxHealthIncrease SocketOption = 22
	// SocketOption_WindMaxManaIncrease Wind(Maximum Mana increase +4)
	SocketOption_WindMaxManaIncrease SocketOption = 23
	// SocketOption_WindAutoManaRecoverIncrease Wind(Automatic Mana recovery increase +7)
	SocketOption_WindAutoManaRecoverIncrease SocketOption = 24
	// SocketOption_WindMaxAgIncrease Wind(Maximum AG increase +25)
	SocketOption_WindMaxAgIncrease SocketOption = 25
	// SocketOption_WindAutoAgRecoverIncrease Wind(AG value increase +26)
	SocketOption_WindAutoAgRecoverIncrease SocketOption = 26
	// SocketOption_LightningExcDmgIncrease Lightning(Excellent damage increase +15)
	SocketOption_LightningExcDmgIncrease SocketOption = 29
	// SocketOption_LightningExcDmgRateIncrease Lightning(Excellent damage rate increase +10)
	SocketOption_LightningExcDmgRateIncrease SocketOption = 30
	// SocketOption_LightningCritDmgIncrease Lightning(Critical damage increase +30)
	SocketOption_LightningCritDmgIncrease SocketOption = 31
	// SocketOption_LightningCritDmgRateIncrease Lightning(Critical damage rate increase +8)
	SocketOption_LightningCritDmgRateIncrease SocketOption = 32
	// SocketOption_EarthHealhIncrease Earth(Health increase +30)
	SocketOption_EarthHealhIncrease SocketOption = 36
	// SocketOption_EmptySocket Empty Socket
	SocketOption_EmptySocket SocketOption = 254
	// SocketOption_NoSocket No Socket
	SocketOption_NoSocket SocketOption = 255
)

// CharacterCreationUnlockFlags The flags to unlock the specified character classes for the creation of new characters.
type CharacterCreationUnlockFlags uint16

const (
	// CharacterCreationUnlockFlags_None No unlocked class.
	CharacterCreationUnlockFlags_None CharacterCreationUnlockFlags = 0
	// CharacterCreationUnlockFlags_Summoner Unlocks the summoner class.
	CharacterCreationUnlockFlags_Summoner CharacterCreationUnlockFlags = 1
	// CharacterCreationUnlockFlags_DarkLord Unlocks the dark lord class.
	CharacterCreationUnlockFlags_DarkLord CharacterCreationUnlockFlags = 2
	// CharacterCreationUnlockFlags_MagicGladiator Unlocks the magic gladiator class.
	CharacterCreationUnlockFlags_MagicGladiator CharacterCreationUnlockFlags = 4
	// CharacterCreationUnlockFlags_RageFighter Unlocks the rage fighter class.
	CharacterCreationUnlockFlags_RageFighter CharacterCreationUnlockFlags = 8
)

// DamageKind Defines the kind of the damage.
type DamageKind uint16

const (
	// DamageKind_NormalRed Red color, used by normal damage.
	DamageKind_NormalRed DamageKind = 0
	// DamageKind_IgnoreDefenseCyan Cyan color, usually used by ignore defense damage.
	DamageKind_IgnoreDefenseCyan DamageKind = 1
	// DamageKind_ExcellentLightGreen Light green color, usually used by excellent damage.
	DamageKind_ExcellentLightGreen DamageKind = 2
	// DamageKind_CriticalBlue Blue color, usually used by critical damage.
	DamageKind_CriticalBlue DamageKind = 3
	// DamageKind_ReflectedLightPink Light pink color, usually used by reflected damage.
	DamageKind_ReflectedLightPink DamageKind = 4
	// DamageKind_PoisonDarkGreen Dark green color, usually used by poison damage.
	DamageKind_PoisonDarkGreen DamageKind = 5
	// DamageKind_DarkPink Dark pink color.
	DamageKind_DarkPink DamageKind = 6
	// DamageKind_White White color.
	DamageKind_White DamageKind = 7
)

// ChatCommandParameterType The kind of value which a chat command parameter expects.
type ChatCommandParameterType uint16

const (
	// ChatCommandParameterType_Text The parameter expects a text.
	ChatCommandParameterType_Text ChatCommandParameterType = 0
	// ChatCommandParameterType_Number The parameter expects a number.
	ChatCommandParameterType_Number ChatCommandParameterType = 1
	// ChatCommandParameterType_Boolean The parameter expects a 0 or a 1.
	ChatCommandParameterType_Boolean ChatCommandParameterType = 2
)

// TradeButtonState Defines the state of the trade button.
type TradeButtonState uint16

const (
	// TradeButtonState_Unchecked Trade button is not pressed. It means that the trade is not yet accepted by the trader.
	TradeButtonState_Unchecked TradeButtonState = 0
	// TradeButtonState_Checked Trade Button is pressed. It means that the trade is accepted by the trader.
	TradeButtonState_Checked TradeButtonState = 1
	// TradeButtonState_Red This state is only sent to the client. After some seconds the client is changing back to normal Unchecked.
	TradeButtonState_Red TradeButtonState = 2
)

// TradeResult Defines the result of a finished trade.
type TradeResult uint16

const (
	// TradeResult_Cancelled The trade was cancelled.
	TradeResult_Cancelled TradeResult = 0
	// TradeResult_Success The trade was successful.
	TradeResult_Success TradeResult = 1
	// TradeResult_FailedByFullInventory The trade failed because of a full inventory.
	TradeResult_FailedByFullInventory TradeResult = 2
	// TradeResult_TimedOut The trade failed because the request timed out.
	TradeResult_TimedOut TradeResult = 3
	// TradeResult_FailedByItemsNotAllowedToTrade The trade failed because one or more items were not allowed to trade.
	TradeResult_FailedByItemsNotAllowedToTrade TradeResult = 4
)

// LoginResult The result of a login request.
type LoginResult uint16

const (
	// LoginResult_InvalidPassword The password was wrong.
	LoginResult_InvalidPassword LoginResult = 0
	// LoginResult_Okay The login succeeded.
	LoginResult_Okay LoginResult = 1
	// LoginResult_AccountInvalid The account is invalid.
	LoginResult_AccountInvalid LoginResult = 2
	// LoginResult_AccountAlreadyConnected The account is already connected.
	LoginResult_AccountAlreadyConnected LoginResult = 3
	// LoginResult_ServerIsFull The server is full.
	LoginResult_ServerIsFull LoginResult = 4
	// LoginResult_AccountBlocked The account is blocked.
	LoginResult_AccountBlocked LoginResult = 5
	// LoginResult_WrongVersion The game client has the wrong version.
	LoginResult_WrongVersion LoginResult = 6
	// LoginResult_ConnectionError An internal error occured during connection.
	LoginResult_ConnectionError LoginResult = 7
	// LoginResult_ConnectionClosed3Fails Connection closed because of three failed login requests.
	LoginResult_ConnectionClosed3Fails LoginResult = 8
	// LoginResult_NoChargeInfo There is no payment information.
	LoginResult_NoChargeInfo LoginResult = 9
	// LoginResult_SubscriptionTermOver The subscription term is over.
	LoginResult_SubscriptionTermOver LoginResult = 10
	// LoginResult_SubscriptionTimeOver The subscription time is over.
	LoginResult_SubscriptionTimeOver LoginResult = 11
	// LoginResult_TemporaryBlocked The account is temporarily blocked.
	LoginResult_TemporaryBlocked LoginResult = 14
	// LoginResult_OnlyPlayersOver15Yrs Only players over 15 years are allowed to connect.
	LoginResult_OnlyPlayersOver15Yrs LoginResult = 17
	// LoginResult_BadCountry The client connected from a blocked country.
	LoginResult_BadCountry LoginResult = 210
)

// ChatMessageType Defines the type of a chat message.
type ChatMessageType uint16

const (
	// ChatMessageType_Normal The message is a normal chat message, e.g. public, within a party or guild.
	ChatMessageType_Normal ChatMessageType = 0
	// ChatMessageType_Whisper The message is sent privately to the receiving player.
	ChatMessageType_Whisper ChatMessageType = 2
)

// AddResult Defines the result and type of experience which is added.
type AddResult uint16

const (
	// AddResult_Undefined Undefined, no experience is added.
	AddResult_Undefined AddResult = 0
	// AddResult_Normal The normal experience is added.
	AddResult_Normal AddResult = 1
	// AddResult_Master The master experience is added.
	AddResult_Master AddResult = 2
	// AddResult_MaxLevelReached The maximum level has been reached, no experience is added.
	AddResult_MaxLevelReached AddResult = 16
	// AddResult_MaxMasterLevelReached The maximum master level has been reached, no master experience is added.
	AddResult_MaxMasterLevelReached AddResult = 32
	// AddResult_MonsterLevelTooLowForMasterExperience The monster level is too low for master experience, no master experience is added.
	AddResult_MonsterLevelTooLowForMasterExperience AddResult = 33
)

// ItemPickUpFailReason Defines the possible fail reasons
type ItemPickUpFailReason uint16

const (
	// ItemPickUpFailReason_ItemStacked The picked up item was combined into an existing item of the players inventory. A separate durability update will be sent to the client.
	ItemPickUpFailReason_ItemStacked ItemPickUpFailReason = 253
	// ItemPickUpFailReason___MaximumInventoryMoneyReached The maximum inventory money has been reached, so the money wasn't picked up. Should not be used, because it's used in the InventoryMoneyUpdate message.
	ItemPickUpFailReason___MaximumInventoryMoneyReached ItemPickUpFailReason = 254
	// ItemPickUpFailReason_General The general, non-specific reason. It just failed.
	ItemPickUpFailReason_General ItemPickUpFailReason = 255
)

// ConsumedItemType Defines a consumed item.
type ConsumedItemType uint16

const (
	// ConsumedItemType_Ale The player consumes a bottle of ale, usually 80 seconds effect time.
	ConsumedItemType_Ale ConsumedItemType = 0
	// ConsumedItemType_RedemyOfLove The player consumes a redemy of love, usually 90 seconds effect time.
	ConsumedItemType_RedemyOfLove ConsumedItemType = 1
	// ConsumedItemType_PotionOfSoul The player consumes a potion of soul, usually 60 seconds effect time.
	ConsumedItemType_PotionOfSoul ConsumedItemType = 77
)

// FruitConsumptionResult Defines the result of the fruit consumption request.
type FruitConsumptionResult uint16

const (
	// FruitConsumptionResult_PlusSuccess Consumption to add points was successful.
	FruitConsumptionResult_PlusSuccess FruitConsumptionResult = 0
	// FruitConsumptionResult_PlusFailed Consumption to add points failed.
	FruitConsumptionResult_PlusFailed FruitConsumptionResult = 1
	// FruitConsumptionResult_PlusPrevented Consumption to add points was prevented because some conditions were not correct.
	FruitConsumptionResult_PlusPrevented FruitConsumptionResult = 2
	// FruitConsumptionResult_MinusSuccess Consumption to remove points was successful.
	FruitConsumptionResult_MinusSuccess FruitConsumptionResult = 3
	// FruitConsumptionResult_MinusFailed Consumption to remove points failed.
	FruitConsumptionResult_MinusFailed FruitConsumptionResult = 4
	// FruitConsumptionResult_MinusPrevented Consumption to remove points was prevented because some conditions were not correct.
	FruitConsumptionResult_MinusPrevented FruitConsumptionResult = 5
	// FruitConsumptionResult_MinusSuccessCashShopFruit Consumption to remove points was successful, removed by a fruit acquired through the cash shop.
	FruitConsumptionResult_MinusSuccessCashShopFruit FruitConsumptionResult = 6
	// FruitConsumptionResult_PreventedByEquippedItems Consumption was prevented because an item was equipped.
	FruitConsumptionResult_PreventedByEquippedItems FruitConsumptionResult = 16
	// FruitConsumptionResult_PlusPreventedByMaximum Consumption to add points was prevented because the maximum amount of points have been added.
	FruitConsumptionResult_PlusPreventedByMaximum FruitConsumptionResult = 33
	// FruitConsumptionResult_MinusPreventedByMaximum Consumption to remove points was prevented because the maximum amount of points have been removed.
	FruitConsumptionResult_MinusPreventedByMaximum FruitConsumptionResult = 37
	// FruitConsumptionResult_MinusPreventedByDefault Consumption to remove points was prevented because the base amount of stat points of the character class cannot be undercut.
	FruitConsumptionResult_MinusPreventedByDefault FruitConsumptionResult = 38
)

// FruitStatType Defines the type of stat which the fruit modifies.
type FruitStatType uint16

const (
	// FruitStatType_Energy Fruit which modifies the energy stat.
	FruitStatType_Energy FruitStatType = 0
	// FruitStatType_Vitality Fruit which modifies the vitality stat.
	FruitStatType_Vitality FruitStatType = 1
	// FruitStatType_Agility Fruit which modifies the agility stat.
	FruitStatType_Agility FruitStatType = 2
	// FruitStatType_Strength Fruit which modifies the strength stat.
	FruitStatType_Strength FruitStatType = 3
	// FruitStatType_Leadership Fruit which modifies the leadership stat.
	FruitStatType_Leadership FruitStatType = 4
)

// EffectOrigin Defines the origin of the effect.
type EffectOrigin uint16

const (
	// EffectOrigin_Undefined Not defined.
	EffectOrigin_Undefined EffectOrigin = 0
	// EffectOrigin_HalloweenAndCherryBlossomEvent Options of Halloween and Cherry Blossom Event items.
	EffectOrigin_HalloweenAndCherryBlossomEvent EffectOrigin = 1
	// EffectOrigin_CashShopItem Options of cash shop items, like Seals.
	EffectOrigin_CashShopItem EffectOrigin = 2
)

// EffectAction Defines the effect option.
type EffectAction uint16

const (
	// EffectAction_Add Effect is added.
	EffectAction_Add EffectAction = 0
	// EffectAction_Remove Effect is removed.
	EffectAction_Remove EffectAction = 1
	// EffectAction_Replace Effect is removed, because its getting replaced.
	EffectAction_Replace EffectAction = 2
)

// EffectType Defines the kind of effect which was applied.
type EffectType uint16

const (
	// EffectType_AttackSpeed Attack speed increase.
	EffectType_AttackSpeed EffectType = 1
	// EffectType_Damage Damage increase.
	EffectType_Damage EffectType = 2
	// EffectType_Defense Defense increase.
	EffectType_Defense EffectType = 3
	// EffectType_MaximumHealth Maximum Health increase.
	EffectType_MaximumHealth EffectType = 4
	// EffectType_MaximumMana Maximum Mana increase.
	EffectType_MaximumMana EffectType = 5
	// EffectType_ExperienceRate Experience rate increase.
	EffectType_ExperienceRate EffectType = 6
	// EffectType_DropRate Drop rate increase.
	EffectType_DropRate EffectType = 7
	// EffectType_Sustenance Sustenance effect, means no experience is gained during this effect.
	EffectType_Sustenance EffectType = 8
	// EffectType_Strength Strength stat increase.
	EffectType_Strength EffectType = 9
	// EffectType_Agility Agility stat increase.
	EffectType_Agility EffectType = 10
	// EffectType_Vitality Vitality stat increase.
	EffectType_Vitality EffectType = 11
	// EffectType_Energy Energy stat increase.
	EffectType_Energy EffectType = 12
	// EffectType_Leadership Leadership stat increase.
	EffectType_Leadership EffectType = 13
	// EffectType_PhysicalDamage Physical damage increase.
	EffectType_PhysicalDamage EffectType = 14
	// EffectType_WizardryDamage Wizardry damage increase.
	EffectType_WizardryDamage EffectType = 15
	// EffectType_Mobility Mobility increase.
	EffectType_Mobility EffectType = 16
)

// NpcWindow Defines the kind of npc window which should be shown on the client.
type NpcWindow uint16

const (
	// NpcWindow_Merchant A merchant window.
	NpcWindow_Merchant NpcWindow = 0
	// NpcWindow_Merchant1 Another merchant window.
	NpcWindow_Merchant1 NpcWindow = 1
	// NpcWindow_VaultStorage A vault storage.
	NpcWindow_VaultStorage NpcWindow = 2
	// NpcWindow_ChaosMachine A chaos machine window.
	NpcWindow_ChaosMachine NpcWindow = 3
	// NpcWindow_DevilSquare A devil square window.
	NpcWindow_DevilSquare NpcWindow = 4
	// NpcWindow_BloodCastle A blood castle window.
	NpcWindow_BloodCastle NpcWindow = 6
	// NpcWindow_PetTrainer The pet trainer window.
	NpcWindow_PetTrainer NpcWindow = 7
	// NpcWindow_Lahap The lahap window.
	NpcWindow_Lahap NpcWindow = 9
	// NpcWindow_CastleSeniorNPC The castle senior window.
	NpcWindow_CastleSeniorNPC NpcWindow = 12
	// NpcWindow_ElphisRefinery The elphis refinery window.
	NpcWindow_ElphisRefinery NpcWindow = 17
	// NpcWindow_RefineStoneMaking The refine stone making window.
	NpcWindow_RefineStoneMaking NpcWindow = 18
	// NpcWindow_RemoveJohOption The jewel of harmony option removal window.
	NpcWindow_RemoveJohOption NpcWindow = 19
	// NpcWindow_IllusionTemple The illusion temple window.
	NpcWindow_IllusionTemple NpcWindow = 20
	// NpcWindow_ChaosCardCombination The chaos card combination window.
	NpcWindow_ChaosCardCombination NpcWindow = 21
	// NpcWindow_CherryBlossomBranchesAssembly The cherry blossom branches assembly window.
	NpcWindow_CherryBlossomBranchesAssembly NpcWindow = 22
	// NpcWindow_SeedMaster The seed master window.
	NpcWindow_SeedMaster NpcWindow = 23
	// NpcWindow_SeedResearcher The seed researcher window.
	NpcWindow_SeedResearcher NpcWindow = 24
	// NpcWindow_StatReInitializer The stat reinitializer window.
	NpcWindow_StatReInitializer NpcWindow = 25
	// NpcWindow_DelgadoLuckyCoinRegistration The delgado lucky coin registration window.
	NpcWindow_DelgadoLuckyCoinRegistration NpcWindow = 32
	// NpcWindow_DoorkeeperTitusDuelWatch The doorkeeper titus duel watch window.
	NpcWindow_DoorkeeperTitusDuelWatch NpcWindow = 33
	// NpcWindow_LugardDoppelgangerEntry The lugard doppelganger entry window.
	NpcWindow_LugardDoppelgangerEntry NpcWindow = 35
	// NpcWindow_JerintGaionEvententry The jerint gaion event entry window.
	NpcWindow_JerintGaionEvententry NpcWindow = 36
	// NpcWindow_JuliaWarpMarketServer The julia warp market server window.
	NpcWindow_JuliaWarpMarketServer NpcWindow = 37
	// NpcWindow_CombineLuckyItem The dialog window which allows to exchange or refine Lucky Item. Used by NPC "David".
	NpcWindow_CombineLuckyItem NpcWindow = 38
)

// ItemWindow Defines the kind of npc window which should be shown on the client.
type ItemWindow uint16

const (
	// ItemWindow_Normal A normal window.
	ItemWindow_Normal ItemWindow = 0
	// ItemWindow_ChaosMachine A chaos machine window.
	ItemWindow_ChaosMachine ItemWindow = 3
	// ItemWindow_ResurrectionFailed A failed resurrection (of Dark Horse or Dark Raven) storage dialog.
	ItemWindow_ResurrectionFailed ItemWindow = 5
)

// ItemPriceSetResult Describes the possible results of setting an item price in a player shop.
type ItemPriceSetResult uint16

const (
	// ItemPriceSetResult_Failed Failed, e.g. because the shop feature is deactivated
	ItemPriceSetResult_Failed ItemPriceSetResult = 0
	// ItemPriceSetResult_Success The price has been set successfully
	ItemPriceSetResult_Success ItemPriceSetResult = 1
	// ItemPriceSetResult_ItemSlotOutOfRange Failed because the item slot was out of range
	ItemPriceSetResult_ItemSlotOutOfRange ItemPriceSetResult = 2
	// ItemPriceSetResult_ItemNotFound Failed because the item could not be found
	ItemPriceSetResult_ItemNotFound ItemPriceSetResult = 3
	// ItemPriceSetResult_PriceNegative Failed because the price was negative
	ItemPriceSetResult_PriceNegative ItemPriceSetResult = 4
	// ItemPriceSetResult_ItemIsBlocked Failed because the item is blocked
	ItemPriceSetResult_ItemIsBlocked ItemPriceSetResult = 5
	// ItemPriceSetResult_CharacterLevelTooLow Failed because the character level is too low (below level 6)
	ItemPriceSetResult_CharacterLevelTooLow ItemPriceSetResult = 6
)

// ActionKind The kind of action which led to the list message.
type ActionKind uint16

const (
	// ActionKind_ByRequest The list was requested.
	ActionKind_ByRequest ActionKind = 5
	// ActionKind_UpdateAfterItemChange The list was changed, e.g. because an item was sold.
	ActionKind_UpdateAfterItemChange ActionKind = 19
)

// ResultKind The kind of result.
type ResultKind uint16

const (
	// ResultKind_Undefined Undefined result.
	ResultKind_Undefined ResultKind = 0
	// ResultKind_Success The item has been bought successfully.
	ResultKind_Success ResultKind = 1
	// ResultKind_NotAvailable The seller is not available.
	ResultKind_NotAvailable ResultKind = 2
	// ResultKind_ShopNotOpened The requested player has no open shop.
	ResultKind_ShopNotOpened ResultKind = 3
	// ResultKind_InTransaction The requested player is already in a transaction with another player.
	ResultKind_InTransaction ResultKind = 4
	// ResultKind_InvalidShopSlot The requested item slot is invalid.
	ResultKind_InvalidShopSlot ResultKind = 5
	// ResultKind_NameMismatchOrPriceMissing The requested player with the specified id has a different name or price is missing.
	ResultKind_NameMismatchOrPriceMissing ResultKind = 6
	// ResultKind_LackOfMoney The player has not enough money to buy the item from the seller.
	ResultKind_LackOfMoney ResultKind = 7
	// ResultKind_MoneyOverflowOrNotEnoughSpace The selling player cannot sell the item, because the sale would overflow his money amount in the inventory. Another possibility is that the inventory of the buyer cannot take the item.
	ResultKind_MoneyOverflowOrNotEnoughSpace ResultKind = 8
	// ResultKind_ItemBlock The requested player has item block active.
	ResultKind_ItemBlock ResultKind = 9
)

// ResultKind2 The kind of result.
type ResultKind2 uint16

const (
	// ResultKind2_Undefined Undefined result.
	ResultKind2_Undefined ResultKind2 = 0
	// ResultKind2_Success The item has been bought successfully.
	ResultKind2_Success ResultKind2 = 1
	// ResultKind2_NotAvailable The seller is not available.
	ResultKind2_NotAvailable ResultKind2 = 2
	// ResultKind2_ShopNotOpened The requested player has no open shop.
	ResultKind2_ShopNotOpened ResultKind2 = 3
	// ResultKind2_InTransaction The requested player is already in a transaction with another player.
	ResultKind2_InTransaction ResultKind2 = 4
	// ResultKind2_InvalidShopSlot The requested item slot is invalid.
	ResultKind2_InvalidShopSlot ResultKind2 = 5
	// ResultKind2_NameMismatchOrPriceMissing The requested player with the specified id has a different name or price is missing.
	ResultKind2_NameMismatchOrPriceMissing ResultKind2 = 6
	// ResultKind2_LackOfMoney The player has not enough money to buy the item from the seller.
	ResultKind2_LackOfMoney ResultKind2 = 7
	// ResultKind2_MoneyOverflowOrNotEnoughSpace The selling player cannot sell the item, because the sale would overflow his money amount in the inventory. Another possibility is that the inventory of the buyer cannot take the item.
	ResultKind2_MoneyOverflowOrNotEnoughSpace ResultKind2 = 8
	// ResultKind2_ItemBlock The requested player has item block active.
	ResultKind2_ItemBlock ResultKind2 = 9
)

// ActionKind2 The kind of action which led to the list message.
type ActionKind2 uint16

const (
	// ActionKind2_ByRequest The list was requested.
	ActionKind2_ByRequest ActionKind2 = 5
	// ActionKind2_UpdateAfterItemChange The list was changed, e.g. because an item was sold.
	ActionKind2_UpdateAfterItemChange ActionKind2 = 19
)

// TerrainAttributeType Defines the attribute which should be set/unset. It's a Flags enumeration.
type TerrainAttributeType uint16

const (
	// TerrainAttributeType_Safezone The coordinate is a safezone.
	TerrainAttributeType_Safezone TerrainAttributeType = 1
	// TerrainAttributeType_Character The coordinate is occupied by a character.
	TerrainAttributeType_Character TerrainAttributeType = 2
	// TerrainAttributeType_Blocked The coordinate is blocked and can't be passed by a character.
	TerrainAttributeType_Blocked TerrainAttributeType = 4
	// TerrainAttributeType_NoGround The coordinate is blocked, because there is no ground and can't be passed by a character.
	TerrainAttributeType_NoGround TerrainAttributeType = 8
	// TerrainAttributeType_Water The coordinate is blocked by water and can't be passed by a character.
	TerrainAttributeType_Water TerrainAttributeType = 16
)

// EffectType2 Defines the effect which is shown for the player.
type EffectType2 uint16

const (
	// EffectType2_ShieldPotion The player gained shield by drinking a potion.
	EffectType2_ShieldPotion EffectType2 = 3
	// EffectType2_LevelUp A level up effect is shown for the player.
	EffectType2_LevelUp EffectType2 = 16
	// EffectType2_ShieldLost The players shield depleted.
	EffectType2_ShieldLost EffectType2 = 17
)

// CharacterDeleteResult Result of a character delete request.
type CharacterDeleteResult uint16

const (
	// CharacterDeleteResult_Unsuccessful Deleting was not successful
	CharacterDeleteResult_Unsuccessful CharacterDeleteResult = 0
	// CharacterDeleteResult_Successful Deleting was successful
	CharacterDeleteResult_Successful CharacterDeleteResult = 1
	// CharacterDeleteResult_WrongSecurityCode Deleting was not successful because a wrong security code was entered
	CharacterDeleteResult_WrongSecurityCode CharacterDeleteResult = 2
)

// MessageType Defines a type of a server message.
type MessageType uint16

const (
	// MessageType_GoldenCenter The message is shown as centered golden message in the client.
	MessageType_GoldenCenter MessageType = 0
	// MessageType_BlueNormal The message is shown as a blue system message.
	MessageType_BlueNormal MessageType = 1
	// MessageType_GuildNotice The message is a guild notice, centered in green.
	MessageType_GuildNotice MessageType = 2
)

// GuildJoinRequestResult The result of the guild join request.
type GuildJoinRequestResult uint16

const (
	// GuildJoinRequestResult_Refused Refused by the guild master.
	GuildJoinRequestResult_Refused GuildJoinRequestResult = 0
	// GuildJoinRequestResult_Accepted Accepted by the guild master.
	GuildJoinRequestResult_Accepted GuildJoinRequestResult = 1
	// GuildJoinRequestResult_GuildFull The guild is full.
	GuildJoinRequestResult_GuildFull GuildJoinRequestResult = 2
	// GuildJoinRequestResult_Disconnected The guild master is disconnected.
	GuildJoinRequestResult_Disconnected GuildJoinRequestResult = 3
	// GuildJoinRequestResult_NotTheGuildMaster The requested player is not the guild master of its guild.
	GuildJoinRequestResult_NotTheGuildMaster GuildJoinRequestResult = 4
	// GuildJoinRequestResult_AlreadyHaveGuild The player already has a guild.
	GuildJoinRequestResult_AlreadyHaveGuild GuildJoinRequestResult = 5
	// GuildJoinRequestResult_GuildMasterOrRequesterIsBusy he guild master or the requesting player is busy, e.g. by another request or by an ongoing guild war.
	GuildJoinRequestResult_GuildMasterOrRequesterIsBusy GuildJoinRequestResult = 6
	// GuildJoinRequestResult_MinimumLevel6 The requesting player needs a minimum level of 6.
	GuildJoinRequestResult_MinimumLevel6 GuildJoinRequestResult = 7
)

// GuildKickSuccess The result of the guild kick request.
type GuildKickSuccess uint16

const (
	// GuildKickSuccess_FailedPasswordIncorrect The kick request failed because of an incorrect password.
	GuildKickSuccess_FailedPasswordIncorrect GuildKickSuccess = 0
	// GuildKickSuccess_KickSucceeded The kick request was successful.
	GuildKickSuccess_KickSucceeded GuildKickSuccess = 1
	// GuildKickSuccess_KickFailedBecausePlayerIsNotGuildMaster The kick failed because player is not guild master.
	GuildKickSuccess_KickFailedBecausePlayerIsNotGuildMaster GuildKickSuccess = 2
	// GuildKickSuccess_Failed The kick request failed.
	GuildKickSuccess_Failed GuildKickSuccess = 3
	// GuildKickSuccess_GuildDisband The guild has been disbanded.
	GuildKickSuccess_GuildDisband GuildKickSuccess = 4
	// GuildKickSuccess_GuildMemberWithdrawn The guild member has been withdrawn.
	GuildKickSuccess_GuildMemberWithdrawn GuildKickSuccess = 5
)

// GuildCreationErrorType Defines a guild creation error.
type GuildCreationErrorType uint16

const (
	// GuildCreationErrorType_None No error occured.
	GuildCreationErrorType_None GuildCreationErrorType = 0
	// GuildCreationErrorType_GuildNameAlreadyTaken The requested guild name is already taken.
	GuildCreationErrorType_GuildNameAlreadyTaken GuildCreationErrorType = 179
)

// RequestResult Describes the result of the guild war request.
type RequestResult uint16

const (
	// RequestResult_GuildNotFound Failed, guild not found.
	RequestResult_GuildNotFound RequestResult = 0
	// RequestResult_RequestSentToGuildMaster Request has been sent to the guild master. Waiting for his answer.
	RequestResult_RequestSentToGuildMaster RequestResult = 1
	// RequestResult_GuildMasterOffline Failed, because the guild master is offline.
	RequestResult_GuildMasterOffline RequestResult = 2
	// RequestResult_NotInGuild Failed, because player is not in a guild.
	RequestResult_NotInGuild RequestResult = 3
	// RequestResult_Failed The guild war couldn't be started, e.g. because the soccer arena is already in use.
	RequestResult_Failed RequestResult = 4
	// RequestResult_NotTheGuildMaster Failed, because player is not the guild master.
	RequestResult_NotTheGuildMaster RequestResult = 5
	// RequestResult_AlreadyInWar Failed, because the requested guild is already in a war.
	RequestResult_AlreadyInWar RequestResult = 6
)

// GuildWarResult Describes the result of the guild war.
type GuildWarResult uint16

const (
	// GuildWarResult_Lost The war was lost.
	GuildWarResult_Lost GuildWarResult = 0
	// GuildWarResult_Won The war was won.
	GuildWarResult_Won GuildWarResult = 1
	// GuildWarResult_OtherGuildMasterCancelledWar The war was cancelled by the other guild master.
	GuildWarResult_OtherGuildMasterCancelledWar GuildWarResult = 2
	// GuildWarResult_CancelledWar The war was cancelled by the own guild master.
	GuildWarResult_CancelledWar GuildWarResult = 3
)

// GuildRelationshipChangeResultType Defines the result of a guild relationship change request.
type GuildRelationshipChangeResultType uint16

const (
	// GuildRelationshipChangeResultType_Failed The request failed.
	GuildRelationshipChangeResultType_Failed GuildRelationshipChangeResultType = 0
	// GuildRelationshipChangeResultType_Success The request was successful.
	GuildRelationshipChangeResultType_Success GuildRelationshipChangeResultType = 1
	// GuildRelationshipChangeResultType_GuildNotFound GUILD_ANS_NOTEXIST_GUILD: The guild does not exist.
	GuildRelationshipChangeResultType_GuildNotFound GuildRelationshipChangeResultType = 16
	// GuildRelationshipChangeResultType_FailedDuringCastleSiege GUILD_ANS_UNIONFAIL_BY_CASTLE: Alliance function will be restricted due to the Castle Siege.
	GuildRelationshipChangeResultType_FailedDuringCastleSiege GuildRelationshipChangeResultType = 16
	// GuildRelationshipChangeResultType_NoAuthorization GUILD_ANS_NOTEXIST_PERMISSION: No authorization to perform this action.
	GuildRelationshipChangeResultType_NoAuthorization GuildRelationshipChangeResultType = 17
	// GuildRelationshipChangeResultType_NotExistExtraStatus GUILD_ANS_NOTEXIST_EXTRA_STATUS: The extra status does not exist.
	GuildRelationshipChangeResultType_NotExistExtraStatus GuildRelationshipChangeResultType = 18
	// GuildRelationshipChangeResultType_NotExistExtraType GUILD_ANS_NOTEXIST_EXTRA_TYPE: The extra type does not exist.
	GuildRelationshipChangeResultType_NotExistExtraType GuildRelationshipChangeResultType = 19
	// GuildRelationshipChangeResultType_AlreadyInAlliance GUILD_ANS_EXIST_RELATIONSHIP_UNION: The guild already has an alliance relationship.
	GuildRelationshipChangeResultType_AlreadyInAlliance GuildRelationshipChangeResultType = 21
	// GuildRelationshipChangeResultType_AlreadyInHostility GUILD_ANS_EXIST_RELATIONSHIP_RIVAL: The guild already has a hostility relationship.
	GuildRelationshipChangeResultType_AlreadyInHostility GuildRelationshipChangeResultType = 22
	// GuildRelationshipChangeResultType_GuildAllianceExists GUILD_ANS_EXIST_UNION: A guild alliance already exists.
	GuildRelationshipChangeResultType_GuildAllianceExists GuildRelationshipChangeResultType = 23
	// GuildRelationshipChangeResultType_HostileGuildExists GUILD_ANS_EXIST_RIVAL: A hostile guild already exists.
	GuildRelationshipChangeResultType_HostileGuildExists GuildRelationshipChangeResultType = 24
	// GuildRelationshipChangeResultType_GuildAllianceDoesNotExist GUILD_ANS_NOTEXIST_UNION: The guild alliance does not exist.
	GuildRelationshipChangeResultType_GuildAllianceDoesNotExist GuildRelationshipChangeResultType = 25
	// GuildRelationshipChangeResultType_HostileGuildDoesNotExist GUILD_ANS_NOTEXIST_RIVAL: The hostile guild does not exist.
	GuildRelationshipChangeResultType_HostileGuildDoesNotExist GuildRelationshipChangeResultType = 26
	// GuildRelationshipChangeResultType_NotMasterOfGuildAlliance GUILD_ANS_NOT_UNION_MASTER: The player is not the master of the guild alliance.
	GuildRelationshipChangeResultType_NotMasterOfGuildAlliance GuildRelationshipChangeResultType = 27
	// GuildRelationshipChangeResultType_NotGuildRival GUILD_ANS_NOT_GUILD_RIVAL: The guild is not a rival guild.
	GuildRelationshipChangeResultType_NotGuildRival GuildRelationshipChangeResultType = 28
	// GuildRelationshipChangeResultType_IncompleteRequirementsToCreateAlliance GUILD_ANS_CANNOT_BE_UNION_MASTER_GUILD: The requirements to create an alliance are incomplete.
	GuildRelationshipChangeResultType_IncompleteRequirementsToCreateAlliance GuildRelationshipChangeResultType = 29
	// GuildRelationshipChangeResultType_MaximumNumberOfGuildsInAllianceReached GUILD_ANS_EXCEED_MAX_UNION_MEMBER: The maximum number of guilds in the alliance has been reached.
	GuildRelationshipChangeResultType_MaximumNumberOfGuildsInAllianceReached GuildRelationshipChangeResultType = 30
	// GuildRelationshipChangeResultType_RequestCancelled GUILD_ANS_CANCEL_REQUEST: The request has been cancelled.
	GuildRelationshipChangeResultType_RequestCancelled GuildRelationshipChangeResultType = 32
	// GuildRelationshipChangeResultType_AllianceMasterNotInGens GUILD_ANS_UNION_MASTER_NOT_GENS: The alliance master is not in a Gens.
	GuildRelationshipChangeResultType_AllianceMasterNotInGens GuildRelationshipChangeResultType = 161
	// GuildRelationshipChangeResultType_GuildMasterNotInGens GUILD_ANS_GUILD_MASTER_NOT_GENS: The guild master is not in a Gens.
	GuildRelationshipChangeResultType_GuildMasterNotInGens GuildRelationshipChangeResultType = 162
	// GuildRelationshipChangeResultType_DifferentGens GUILD_ANS_UNION_MASTER_DISAGREE_GENS: The alliance master and guild master belong to different Gens.
	GuildRelationshipChangeResultType_DifferentGens GuildRelationshipChangeResultType = 163
)

// VaultProtectionState Defines the vault protection state.
type VaultProtectionState uint16

const (
	// VaultProtectionState_Unprotected The vault is unprotected.
	VaultProtectionState_Unprotected VaultProtectionState = 0
	// VaultProtectionState_Locked The vault is protected and locked. To move items or money, the player needs to unlock it.
	VaultProtectionState_Locked VaultProtectionState = 1
	// VaultProtectionState_UnlockFailedByWrongPin The vault is protected and locked. The user-requested unlock failed by a wrong pin.
	VaultProtectionState_UnlockFailedByWrongPin VaultProtectionState = 10
	// VaultProtectionState_SetPinFailedBecauseLock The vault is protected and locked and the player-requested pin setting failed because of the lock.
	VaultProtectionState_SetPinFailedBecauseLock VaultProtectionState = 11
	// VaultProtectionState_Unlocked The vault is protected, but was unlocked by the player.
	VaultProtectionState_Unlocked VaultProtectionState = 12
	// VaultProtectionState_RemovePinFailedByWrongPassword The vault is protected and the player-requested pin removal failed by using the wrong password.
	VaultProtectionState_RemovePinFailedByWrongPassword VaultProtectionState = 13
)

// CraftingResult Defines the crafting result.
type CraftingResult uint16

const (
	// CraftingResult_Failed The crafting failed.
	CraftingResult_Failed CraftingResult = 0
	// CraftingResult_Success The crafting succeeded.
	CraftingResult_Success CraftingResult = 1
	// CraftingResult_NotEnoughMoney The crafting wasn't executed because of missing money.
	CraftingResult_NotEnoughMoney CraftingResult = 2
	// CraftingResult_TooManyItems The crafting wasn't executed because of too many items.
	CraftingResult_TooManyItems CraftingResult = 3
	// CraftingResult_CharacterLevelTooLow The crafting wasn't executed because the character level is too low.
	CraftingResult_CharacterLevelTooLow CraftingResult = 4
	// CraftingResult_LackingMixItems The crafting wasn't executed because of missing items.
	CraftingResult_LackingMixItems CraftingResult = 6
	// CraftingResult_IncorrectMixItems The crafting wasn't executed because of incorrect items.
	CraftingResult_IncorrectMixItems CraftingResult = 7
	// CraftingResult_InvalidItemLevel The crafting wasn't executed because of an invalid item level.
	CraftingResult_InvalidItemLevel CraftingResult = 8
	// CraftingResult_CharacterClassTooLow The crafting wasn't executed because the character class is too low.
	CraftingResult_CharacterClassTooLow CraftingResult = 9
	// CraftingResult_IncorrectBloodCastleItems The blood castle ticket crafting wasn't executed because the BloodCastle items are not correct.
	CraftingResult_IncorrectBloodCastleItems CraftingResult = 10
	// CraftingResult_NotEnoughMoneyForBloodCastle The crafting wasn't executed because the player has not enough money for the blood castle ticket crafting.
	CraftingResult_NotEnoughMoneyForBloodCastle CraftingResult = 11
)

// QuestRewardType Defines the reward type in the quest reward message.
type QuestRewardType uint16

const (
	// QuestRewardType_LevelUpPoints The character receives additional points.
	QuestRewardType_LevelUpPoints QuestRewardType = 200
	// QuestRewardType_CharacterEvolutionFirstToSecond The character class changes from the first to the second class.
	QuestRewardType_CharacterEvolutionFirstToSecond QuestRewardType = 201
	// QuestRewardType_LevelUpPointsPerLevelIncrease The character receives additional points per level.
	QuestRewardType_LevelUpPointsPerLevelIncrease QuestRewardType = 202
	// QuestRewardType_ComboSkill The character receives the ability to perform skill combinations.
	QuestRewardType_ComboSkill QuestRewardType = 203
	// QuestRewardType_CharacterEvolutionSecondToThird The character class changes from the second to the third class.
	QuestRewardType_CharacterEvolutionSecondToThird QuestRewardType = 204
)

// PetSkillType Describes the type of the pet attack.
type PetSkillType uint16

const (
	// PetSkillType_SingleTarget A single target attack, used for critical and excellent hits.
	PetSkillType_SingleTarget PetSkillType = 0
	// PetSkillType_Range A range attack for multiple targets, usually up to 3 additional targets which all get their own PetAttack messages with 'SingleTarget' right after the first 'Range' message.
	PetSkillType_Range PetSkillType = 1
)

// DuelStartResultType Describes the type of the duel result.
type DuelStartResultType uint16

const (
	// DuelStartResultType_Success The duel has been started.
	DuelStartResultType_Success DuelStartResultType = 0
	// DuelStartResultType_FailedByTooLowLevel The duel couldn't be started, because one of the players has not the minimum level, usually 30.
	DuelStartResultType_FailedByTooLowLevel DuelStartResultType = 12
	// DuelStartResultType_FailedByError The duel couldn't be started, because of an unexpected error.
	DuelStartResultType_FailedByError DuelStartResultType = 14
	// DuelStartResultType_Refused The duel couldn't be started, because the opponent refused.
	DuelStartResultType_Refused DuelStartResultType = 15
	// DuelStartResultType_FailedByNoFreeRoom The duel couldn't be started, because no duel room is free.
	DuelStartResultType_FailedByNoFreeRoom DuelStartResultType = 16
	// DuelStartResultType_FailedBy_ The duel couldn't be started, because ...
	DuelStartResultType_FailedBy_ DuelStartResultType = 28
	// DuelStartResultType_FailedByNotEnoughMoney The duel couldn't be started, because one of the players has not enough money, usually 30000.
	DuelStartResultType_FailedByNotEnoughMoney DuelStartResultType = 30
)

// LetterSendRequestResult Describes the result of a letter send request.
type LetterSendRequestResult uint16

const (
	// LetterSendRequestResult_TryAgain The letter wasn't sent because there was an internal problem. The user should try again.
	LetterSendRequestResult_TryAgain LetterSendRequestResult = 0
	// LetterSendRequestResult_Success The letter was sent.
	LetterSendRequestResult_Success LetterSendRequestResult = 1
	// LetterSendRequestResult_MailboxFull The mailbox of the recipient is full.
	LetterSendRequestResult_MailboxFull LetterSendRequestResult = 2
	// LetterSendRequestResult_ReceiverNotExists The receiver does not exist.
	LetterSendRequestResult_ReceiverNotExists LetterSendRequestResult = 3
	// LetterSendRequestResult_CantSendToYourself A letter can't be sent to yourself.
	LetterSendRequestResult_CantSendToYourself LetterSendRequestResult = 4
	// LetterSendRequestResult_NotEnoughMoney The sender doesn't have enough money to send a letter.
	LetterSendRequestResult_NotEnoughMoney LetterSendRequestResult = 7
)

// LetterState Describes the state of a letter.
type LetterState uint16

const (
	// LetterState_Read The letter was read before.
	LetterState_Read LetterState = 0
	// LetterState_Unread The letter wasn't read yet.
	LetterState_Unread LetterState = 1
	// LetterState_New The letter is new (= was just sent by the sender) and wasn't read yet. It will notify the user about the received letter.
	LetterState_New LetterState = 2
)

// EnterResult Defines the result of the enter request.
type EnterResult uint16

const (
	// EnterResult_Success The event has been entered.
	EnterResult_Success EnterResult = 0
	// EnterResult_Failed Entering the event failed, e.g. by missing event ticket or level range.
	EnterResult_Failed EnterResult = 1
	// EnterResult_NotOpen Entering the event failed, because it's not opened.
	EnterResult_NotOpen EnterResult = 2
	// EnterResult_CharacterLevelTooHigh Entering the event failed, because the character level is too high for the requested event level.
	EnterResult_CharacterLevelTooHigh EnterResult = 3
	// EnterResult_CharacterLevelTooLow Entering the event failed, because the character level is too low for the requested event level.
	EnterResult_CharacterLevelTooLow EnterResult = 4
	// EnterResult_Full Entering the event failed, because it's full.
	EnterResult_Full EnterResult = 5
)

// MiniGameTypeState The state of the mini games.
type MiniGameTypeState uint16

const (
	// MiniGameTypeState_DevilSquareClosed Is sent when the devil square is currently closed and will be opened. "You will enter Devil Square (x seconds from now)".
	MiniGameTypeState_DevilSquareClosed MiniGameTypeState = 0
	// MiniGameTypeState_DevilSquareOpened Is sent when the devil square game is currently opened for entrance and closing for entrance. "The gate of Devil Square will close down in x seconds".
	MiniGameTypeState_DevilSquareOpened MiniGameTypeState = 1
	// MiniGameTypeState_DevilSquareRunning Is sent when the devil square game is currently running and is about to end. "The gate of Devil Square is closing down (x seconds remaining)".
	MiniGameTypeState_DevilSquareRunning MiniGameTypeState = 2
	// MiniGameTypeState_BloodCastleClosed The blood castle game is closed. "Blood Castle Closing (in x seconds)".
	MiniGameTypeState_BloodCastleClosed MiniGameTypeState = 3
	// MiniGameTypeState_BloodCastleOpened The blood castle game is opened for entrance. "Blood Castle Infiltration (in x seconds)".
	MiniGameTypeState_BloodCastleOpened MiniGameTypeState = 4
	// MiniGameTypeState_BloodCastleEnding The blood castle game is ending. "Blood Castle ends (in x seconds)".
	MiniGameTypeState_BloodCastleEnding MiniGameTypeState = 5
	// MiniGameTypeState_BloodCastleFinished The blood castle game is finished. "Blood Castle Event shuts down (in x seconds)".
	MiniGameTypeState_BloodCastleFinished MiniGameTypeState = 6
	// MiniGameTypeState_BloodCastleCongratulations The blood castle game was finished successfully. "Congratulations".
	MiniGameTypeState_BloodCastleCongratulations MiniGameTypeState = 7
	// MiniGameTypeState_ChaosCastleClosed The chaos castle game is closed. "Chaos Castle Closing (in x seconds)".
	MiniGameTypeState_ChaosCastleClosed MiniGameTypeState = 10
	// MiniGameTypeState_ChaosCastleOpened The chaos castle game is opened for entrance. "Chaos Castle Penetration (in x seconds)".
	MiniGameTypeState_ChaosCastleOpened MiniGameTypeState = 11
	// MiniGameTypeState_ChaosCastleEnding The chaos castle game is ending. "Chaos Castle Event ends (in x seconds)".
	MiniGameTypeState_ChaosCastleEnding MiniGameTypeState = 12
	// MiniGameTypeState_ChaosCastleFinished The chaos castle game is finished. Chaos Castle Event shuts down (in x seconds)".
	MiniGameTypeState_ChaosCastleFinished MiniGameTypeState = 13
)

// EnterResult2 Defines the result of the enter request.
type EnterResult2 uint16

const (
	// EnterResult2_Success The event has been entered.
	EnterResult2_Success EnterResult2 = 0
	// EnterResult2_Failed Entering the event failed, e.g. by missing event ticket or level range.
	EnterResult2_Failed EnterResult2 = 1
	// EnterResult2_NotOpen Entering the event failed, because it's not opened.
	EnterResult2_NotOpen EnterResult2 = 2
	// EnterResult2_CharacterLevelTooHigh Entering the event failed, because the character level is too high for the requested event level.
	EnterResult2_CharacterLevelTooHigh EnterResult2 = 3
	// EnterResult2_CharacterLevelTooLow Entering the event failed, because the character level is too low for the requested event level.
	EnterResult2_CharacterLevelTooLow EnterResult2 = 4
	// EnterResult2_Full Entering the event failed, because it's full.
	EnterResult2_Full EnterResult2 = 5
)

// Status Defines the status of the event.
type Status uint16

const (
	// Status_BloodCastleStarted The blood castle event has just started and is running.
	Status_BloodCastleStarted Status = 0
	// Status_BloodCastleGateNotDestroyed The blood castle event is running, but the gate is not destroyed.
	Status_BloodCastleGateNotDestroyed Status = 1
	// Status_BloodCastleEnded The blood castle event has ended.
	Status_BloodCastleEnded Status = 2
	// Status_BloodCastleGateDestroyed The blood castle event is running and the gate is destroyed.
	Status_BloodCastleGateDestroyed Status = 4
	// Status_ChaosCastleStarted The chaos castle event has just started and is running.
	Status_ChaosCastleStarted Status = 5
	// Status_ChaosCastleRunning The chaos castle event is running.
	Status_ChaosCastleRunning Status = 6
	// Status_ChaosCastleEnded The chaos castle event has ended.
	Status_ChaosCastleEnded Status = 7
	// Status_ChaosCastleStageOne The chaos castle event reached the first stage of map shrinking.
	Status_ChaosCastleStageOne Status = 8
	// Status_ChaosCastleStageTwo The chaos castle event reached the second stage of map shrinking.
	Status_ChaosCastleStageTwo Status = 9
	// Status_ChaosCastleStageThree The chaos castle event reached the third stage of map shrinking.
	Status_ChaosCastleStageThree Status = 10
)

// EnterResult3 Defines the result of the enter request.
type EnterResult3 uint16

const (
	// EnterResult3_Success The event has been entered.
	EnterResult3_Success EnterResult3 = 0
	// EnterResult3_Failed Entering the event failed, e.g. by missing event ticket or level range.
	EnterResult3_Failed EnterResult3 = 1
	// EnterResult3_NotOpen Entering the event failed, because it's not opened.
	EnterResult3_NotOpen EnterResult3 = 2
	// EnterResult3_Full Entering the event failed, because it's full.
	EnterResult3_Full EnterResult3 = 5
	// EnterResult3_NotEnoughMoney Entering the event failed, because the player doesn't have enough money for the entrance fee.
	EnterResult3_NotEnoughMoney EnterResult3 = 7
	// EnterResult3_PlayerKillerCantEnter Entering the event failed, because the player has a pk state.
	EnterResult3_PlayerKillerCantEnter EnterResult3 = 8
)

// Events Defines all events.
type Events uint16

const (
	// Events_RedDragon Red dragon invasion.
	Events_RedDragon Events = 1
	// Events_GoldenDragon Golden dragon invasion.
	Events_GoldenDragon Events = 3
)
