// Code generated by muprotogen from MUnique.OpenMU.Network.Packets 0.9.10; DO NOT EDIT.

package s2c

// RouteKey 是包分发表的键，对应线上帧头。
type RouteKey struct {
	Header byte
	Code   byte
	HasSub bool
	Sub    byte
}

// PacketInfo 描述一个已注册包的静态信息。
type PacketInfo struct {
	Name      string
	Direction string
	Fixed     bool
	Length    int
}

type routeEntry struct {
	Key  RouteKey
	Info PacketInfo
}

var routes = []routeEntry{
	{RouteKey{0xC1, 0x00, false, 0x00}, PacketInfo{"ChatMessage", "ServerToClient", false, 0}},
	{RouteKey{0xC1, 0x01, false, 0x00}, PacketInfo{"ObjectMessage", "ServerToClient", false, 0}},
	{RouteKey{0xC1, 0x07, false, 0x00}, PacketInfo{"MagicEffectStatus", "ServerToClient", true, 7}},
	{RouteKey{0xC1, 0x0B, false, 0x00}, PacketInfo{"MapEventState", "ServerToClient", true, 5}},
	{RouteKey{0xC1, 0x0D, false, 0x00}, PacketInfo{"ServerMessage", "ServerToClient", false, 0}},
	{RouteKey{0xC1, 0x0F, false, 0x00}, PacketInfo{"WeatherStatusUpdate", "ServerToClient", true, 4}},
	{RouteKey{0xC1, 0x10, false, 0x00}, PacketInfo{"ObjectWalked075", "ServerToClient", true, 8}},
	{RouteKey{0xC1, 0x11, false, 0x00}, PacketInfo{"ObjectHit", "ServerToClient", true, 10}},
	{RouteKey{0xC1, 0x11, false, 0x00}, PacketInfo{"ObjectHitExtended", "ServerToClient", true, 16}},
	{RouteKey{0xC1, 0x14, false, 0x00}, PacketInfo{"MapObjectOutOfScope", "ServerToClient", false, 0}},
	{RouteKey{0xC1, 0x15, false, 0x00}, PacketInfo{"ObjectMoved", "ServerToClient", true, 8}},
	{RouteKey{0xC1, 0x17, false, 0x00}, PacketInfo{"ObjectGotKilled", "ServerToClient", true, 9}},
	{RouteKey{0xC1, 0x18, false, 0x00}, PacketInfo{"ObjectAnimation", "ServerToClient", true, 9}},
	{RouteKey{0xC1, 0x19, false, 0x00}, PacketInfo{"SkillAnimation075", "ServerToClient", true, 8}},
	{RouteKey{0xC1, 0x1B, false, 0x00}, PacketInfo{"MagicEffectCancelled", "ServerToClient", true, 7}},
	{RouteKey{0xC1, 0x1B, false, 0x00}, PacketInfo{"MagicEffectCancelled075", "ServerToClient", true, 6}},
	{RouteKey{0xC1, 0x1E, false, 0x00}, PacketInfo{"AreaSkillAnimation075", "ServerToClient", true, 9}},
	{RouteKey{0xC1, 0x23, false, 0x00}, PacketInfo{"ItemDropResponse", "ServerToClient", true, 5}},
	{RouteKey{0xC1, 0x25, false, 0x00}, PacketInfo{"AppearanceChanged", "ServerToClient", false, 0}},
	{RouteKey{0xC1, 0x25, false, 0x00}, PacketInfo{"AppearanceChangedExtended", "ServerToClient", true, 14}},
	{RouteKey{0xC1, 0x26, true, 0xFD}, PacketInfo{"ItemConsumptionFailed", "ServerToClient", true, 9}},
	{RouteKey{0xC1, 0x26, true, 0xFD}, PacketInfo{"ItemConsumptionFailedExtended", "ServerToClient", true, 12}},
	{RouteKey{0xC1, 0x26, true, 0xFE}, PacketInfo{"MaximumHealthAndShield", "ServerToClient", true, 9}},
	{RouteKey{0xC1, 0x26, true, 0xFE}, PacketInfo{"MaximumStatsExtended", "ServerToClient", true, 20}},
	{RouteKey{0xC1, 0x26, true, 0xFF}, PacketInfo{"CurrentHealthAndShield", "ServerToClient", true, 9}},
	{RouteKey{0xC1, 0x26, true, 0xFF}, PacketInfo{"CurrentStatsExtended", "ServerToClient", true, 24}},
	{RouteKey{0xC1, 0x27, true, 0xFE}, PacketInfo{"MaximumManaAndAbility", "ServerToClient", true, 8}},
	{RouteKey{0xC1, 0x27, true, 0xFF}, PacketInfo{"CurrentManaAndAbility", "ServerToClient", true, 8}},
	{RouteKey{0xC1, 0x28, false, 0x00}, PacketInfo{"ItemRemoved", "ServerToClient", true, 5}},
	{RouteKey{0xC1, 0x2A, false, 0x00}, PacketInfo{"ItemDurabilityChanged", "ServerToClient", true, 6}},
	{RouteKey{0xC1, 0x2C, false, 0x00}, PacketInfo{"FruitConsumptionResponse", "ServerToClient", true, 7}},
	{RouteKey{0xC1, 0x2D, false, 0x00}, PacketInfo{"EffectItemConsumption", "ServerToClient", true, 17}},
	{RouteKey{0xC1, 0x2F, false, 0x00}, PacketInfo{"MoneyDroppedExtended", "ServerToClient", true, 12}},
	{RouteKey{0xC1, 0x32, false, 0x00}, PacketInfo{"ItemBought", "ServerToClient", false, 0}},
	{RouteKey{0xC1, 0x32, true, 0xFF}, PacketInfo{"NpcItemBuyFailed", "ServerToClient", true, 4}},
	{RouteKey{0xC1, 0x37, false, 0x00}, PacketInfo{"TradeRequestAnswer", "ServerToClient", true, 20}},
	{RouteKey{0xC1, 0x38, false, 0x00}, PacketInfo{"TradeItemRemoved", "ServerToClient", true, 4}},
	{RouteKey{0xC1, 0x39, false, 0x00}, PacketInfo{"TradeItemAdded", "ServerToClient", false, 0}},
	{RouteKey{0xC1, 0x3A, true, 0x01}, PacketInfo{"TradeMoneySetResponse", "ServerToClient", true, 4}},
	{RouteKey{0xC1, 0x3B, false, 0x00}, PacketInfo{"TradeMoneyUpdate", "ServerToClient", true, 8}},
	{RouteKey{0xC1, 0x3C, false, 0x00}, PacketInfo{"TradeButtonStateChanged", "ServerToClient", true, 4}},
	{RouteKey{0xC1, 0x3D, false, 0x00}, PacketInfo{"TradeFinished", "ServerToClient", true, 4}},
	{RouteKey{0xC1, 0x3F, true, 0x02}, PacketInfo{"PlayerShopOpenSuccessful", "ServerToClient", true, 5}},
	{RouteKey{0xC1, 0x3F, true, 0x03}, PacketInfo{"PlayerShopClosed", "ServerToClient", true, 7}},
	{RouteKey{0xC1, 0x3F, true, 0x06}, PacketInfo{"PlayerShopBuyResult", "ServerToClient", true, 21}},
	{RouteKey{0xC1, 0x3F, true, 0x06}, PacketInfo{"PlayerShopBuyResultExtended", "ServerToClient", false, 0}},
	{RouteKey{0xC1, 0x3F, true, 0x08}, PacketInfo{"PlayerShopItemSoldToPlayer", "ServerToClient", true, 15}},
	{RouteKey{0xC1, 0x3F, true, 0x12}, PacketInfo{"ClosePlayerShopDialog", "ServerToClient", true, 6}},
	{RouteKey{0xC1, 0x40, false, 0x00}, PacketInfo{"PartyRequest", "ServerToClient", true, 5}},
	{RouteKey{0xC1, 0x42, true, 0x01}, PacketInfo{"PartyList", "ServerToClient", false, 0}},
	{RouteKey{0xC1, 0x42, true, 0x01}, PacketInfo{"PartyList075", "ServerToClient", false, 0}},
	{RouteKey{0xC1, 0x43, false, 0x00}, PacketInfo{"RemovePartyMember", "ServerToClient", true, 4}},
	{RouteKey{0xC1, 0x44, false, 0x00}, PacketInfo{"PartyHealthUpdate", "ServerToClient", false, 0}},
	{RouteKey{0xC1, 0x46, false, 0x00}, PacketInfo{"ChangeTerrainAttributes", "ServerToClient", false, 0}},
	{RouteKey{0xC1, 0x48, false, 0x00}, PacketInfo{"ShowEffect", "ServerToClient", true, 6}},
	{RouteKey{0xC1, 0x4B, false, 0x00}, PacketInfo{"RageAttackRangeResponse", "ServerToClient", true, 16}},
	{RouteKey{0xC1, 0x50, false, 0x00}, PacketInfo{"GuildJoinRequest", "ServerToClient", true, 5}},
	{RouteKey{0xC1, 0x51, false, 0x00}, PacketInfo{"GuildJoinResponse", "ServerToClient", true, 4}},
	{RouteKey{0xC1, 0x53, false, 0x00}, PacketInfo{"GuildKickResponse", "ServerToClient", true, 4}},
	{RouteKey{0xC1, 0x54, false, 0x00}, PacketInfo{"ShowGuildMasterDialog", "ServerToClient", true, 3}},
	{RouteKey{0xC1, 0x55, false, 0x00}, PacketInfo{"ShowGuildCreationDialog", "ServerToClient", true, 3}},
	{RouteKey{0xC1, 0x56, false, 0x00}, PacketInfo{"GuildCreationResult", "ServerToClient", true, 5}},
	{RouteKey{0xC1, 0x5C, false, 0x00}, PacketInfo{"SingleGuildInformation075", "ServerToClient", true, 45}},
	{RouteKey{0xC1, 0x5D, false, 0x00}, PacketInfo{"GuildMemberLeftGuild", "ServerToClient", true, 5}},
	{RouteKey{0xC1, 0x60, false, 0x00}, PacketInfo{"GuildWarRequestResult", "ServerToClient", true, 4}},
	{RouteKey{0xC1, 0x61, false, 0x00}, PacketInfo{"GuildWarRequest", "ServerToClient", true, 12}},
	{RouteKey{0xC1, 0x62, false, 0x00}, PacketInfo{"GuildWarDeclared", "ServerToClient", true, 13}},
	{RouteKey{0xC1, 0x63, false, 0x00}, PacketInfo{"GuildWarEnded", "ServerToClient", true, 12}},
	{RouteKey{0xC1, 0x64, false, 0x00}, PacketInfo{"GuildWarScoreUpdate", "ServerToClient", true, 6}},
	{RouteKey{0xC1, 0x66, false, 0x00}, PacketInfo{"GuildInformation", "ServerToClient", true, 60}},
	{RouteKey{0xC1, 0x81, false, 0x00}, PacketInfo{"VaultMoneyUpdate", "ServerToClient", true, 12}},
	{RouteKey{0xC1, 0x82, false, 0x00}, PacketInfo{"VaultClosed", "ServerToClient", true, 3}},
	{RouteKey{0xC1, 0x83, false, 0x00}, PacketInfo{"VaultProtectionInformation", "ServerToClient", true, 4}},
	{RouteKey{0xC1, 0x86, false, 0x00}, PacketInfo{"ItemCraftingResult", "ServerToClient", false, 0}},
	{RouteKey{0xC1, 0x87, false, 0x00}, PacketInfo{"CraftingDialogClosed075", "ServerToClient", true, 3}},
	{RouteKey{0xC1, 0x90, false, 0x00}, PacketInfo{"DevilSquareEnterResult", "ServerToClient", true, 4}},
	{RouteKey{0xC1, 0x91, false, 0x00}, PacketInfo{"MiniGameOpeningState", "ServerToClient", true, 7}},
	{RouteKey{0xC1, 0x92, false, 0x00}, PacketInfo{"UpdateMiniGameState", "ServerToClient", true, 4}},
	{RouteKey{0xC1, 0x93, false, 0x00}, PacketInfo{"MiniGameScoreTable", "ServerToClient", false, 0}},
	{RouteKey{0xC1, 0x93, false, 0x00}, PacketInfo{"BloodCastleScore", "ServerToClient", true, 29}},
	{RouteKey{0xC1, 0x9A, false, 0x00}, PacketInfo{"BloodCastleEnterResult", "ServerToClient", true, 4}},
	{RouteKey{0xC1, 0x9B, false, 0x00}, PacketInfo{"BloodCastleState", "ServerToClient", true, 13}},
	{RouteKey{0xC1, 0xA0, false, 0x00}, PacketInfo{"LegacyQuestStateList", "ServerToClient", false, 0}},
	{RouteKey{0xC1, 0xA1, false, 0x00}, PacketInfo{"LegacyQuestStateDialog", "ServerToClient", true, 5}},
	{RouteKey{0xC1, 0xA2, false, 0x00}, PacketInfo{"LegacySetQuestStateResponse", "ServerToClient", true, 6}},
	{RouteKey{0xC1, 0xA3, false, 0x00}, PacketInfo{"LegacyQuestReward", "ServerToClient", true, 7}},
	{RouteKey{0xC1, 0xA4, true, 0x00}, PacketInfo{"LegacyQuestMonsterKillInfo", "ServerToClient", true, 48}},
	{RouteKey{0xC1, 0xA7, false, 0x00}, PacketInfo{"PetMode", "ServerToClient", true, 7}},
	{RouteKey{0xC1, 0xA8, false, 0x00}, PacketInfo{"PetAttack", "ServerToClient", true, 9}},
	{RouteKey{0xC1, 0xA9, false, 0x00}, PacketInfo{"PetInfoResponse", "ServerToClient", true, 13}},
	{RouteKey{0xC1, 0xAA, true, 0x01}, PacketInfo{"DuelStartResult", "ServerToClient", true, 17}},
	{RouteKey{0xC1, 0xAA, true, 0x02}, PacketInfo{"DuelStartRequest", "ServerToClient", true, 16}},
	{RouteKey{0xC1, 0xAA, true, 0x03}, PacketInfo{"DuelEnd", "ServerToClient", true, 17}},
	{RouteKey{0xC1, 0xAA, true, 0x04}, PacketInfo{"DuelScore", "ServerToClient", true, 10}},
	{RouteKey{0xC1, 0xAA, true, 0x05}, PacketInfo{"DuelHealthUpdate", "ServerToClient", true, 12}},
	{RouteKey{0xC1, 0xAA, true, 0x06}, PacketInfo{"DuelStatus", "ServerToClient", true, 92}},
	{RouteKey{0xC1, 0xAA, true, 0x07}, PacketInfo{"DuelInit", "ServerToClient", true, 30}},
	{RouteKey{0xC1, 0xAA, true, 0x08}, PacketInfo{"DuelSpectatorAdded", "ServerToClient", true, 14}},
	{RouteKey{0xC1, 0xAA, true, 0x0A}, PacketInfo{"DuelSpectatorRemoved", "ServerToClient", true, 14}},
	{RouteKey{0xC1, 0xAA, true, 0x0B}, PacketInfo{"DuelSpectatorList", "ServerToClient", true, 105}},
	{RouteKey{0xC1, 0xAA, true, 0x0C}, PacketInfo{"DuelFinished", "ServerToClient", true, 24}},
	{RouteKey{0xC1, 0xAA, true, 0x0D}, PacketInfo{"DuelHealthBarInit", "ServerToClient", true, 4}},
	{RouteKey{0xC1, 0xAF, true, 0x01}, PacketInfo{"ChaosCastleEnterResult", "ServerToClient", true, 5}},
	{RouteKey{0xC1, 0xBA, false, 0x00}, PacketInfo{"SkillStageUpdate", "ServerToClient", true, 7}},
	{RouteKey{0xC1, 0xBF, true, 0x00}, PacketInfo{"IllusionTempleEnterResult", "ServerToClient", true, 5}},
	{RouteKey{0xC1, 0xBF, true, 0x01}, PacketInfo{"IllusionTempleState", "ServerToClient", false, 0}},
	{RouteKey{0xC1, 0xBF, true, 0x02}, PacketInfo{"IllusionTempleSkillUsageResult", "ServerToClient", true, 11}},
	{RouteKey{0xC1, 0xBF, true, 0x03}, PacketInfo{"IllusionTempleUserCount", "ServerToClient", true, 10}},
	{RouteKey{0xC1, 0xBF, true, 0x04}, PacketInfo{"IllusionTempleResult", "ServerToClient", false, 0}},
	{RouteKey{0xC1, 0xBF, true, 0x06}, PacketInfo{"IllusionTempleSkillPointUpdate", "ServerToClient", true, 5}},
	{RouteKey{0xC1, 0xBF, true, 0x07}, PacketInfo{"IllusionTempleSkillEnded", "ServerToClient", true, 8}},
	{RouteKey{0xC1, 0xBF, true, 0x07}, PacketInfo{"IllusionTempleSkillEnd", "ServerToClient", true, 6}},
	{RouteKey{0xC1, 0xBF, true, 0x08}, PacketInfo{"IllusionTempleHolyItemRelics", "ServerToClient", true, 16}},
	{RouteKey{0xC1, 0xBF, true, 0x0A}, PacketInfo{"ChainLightningHitInfo", "ServerToClient", false, 0}},
	{RouteKey{0xC1, 0xBF, true, 0x51}, PacketInfo{"MuHelperStatusUpdate", "ServerToClient", true, 16}},
	{RouteKey{0xC1, 0xC1, true, 0x01}, PacketInfo{"FriendAdded", "ServerToClient", true, 15}},
	{RouteKey{0xC1, 0xC2, false, 0x00}, PacketInfo{"FriendRequest", "ServerToClient", true, 13}},
	{RouteKey{0xC1, 0xC3, true, 0x01}, PacketInfo{"FriendDeleted", "ServerToClient", true, 14}},
	{RouteKey{0xC1, 0xC4, false, 0x00}, PacketInfo{"FriendOnlineStateUpdate", "ServerToClient", true, 14}},
	{RouteKey{0xC1, 0xC5, false, 0x00}, PacketInfo{"LetterSendResponse", "ServerToClient", true, 8}},
	{RouteKey{0xC1, 0xC8, false, 0x00}, PacketInfo{"RemoveLetter", "ServerToClient", true, 6}},
	{RouteKey{0xC1, 0xD4, false, 0x00}, PacketInfo{"ObjectWalked", "ServerToClient", false, 0}},
	{RouteKey{0xC1, 0xD4, false, 0x00}, PacketInfo{"ObjectWalkedExtended", "ServerToClient", false, 0}},
	{RouteKey{0xC1, 0xDE, true, 0x00}, PacketInfo{"CharacterClassCreationUnlock", "ServerToClient", true, 5}},
	{RouteKey{0xC1, 0xE5, false, 0x00}, PacketInfo{"GuildRelationshipRequest", "ServerToClient", true, 7}},
	{RouteKey{0xC1, 0xE6, false, 0x00}, PacketInfo{"GuildRelationshipChangeResult", "ServerToClient", true, 8}},
	{RouteKey{0xC1, 0xEB, true, 0x01}, PacketInfo{"RemoveAllianceGuildResult", "ServerToClient", true, 7}},
	{RouteKey{0xC1, 0xF1, true, 0x00}, PacketInfo{"GameServerEntered", "ServerToClient", true, 12}},
	{RouteKey{0xC1, 0xF1, true, 0x01}, PacketInfo{"LoginResponse", "ServerToClient", true, 5}},
	{RouteKey{0xC1, 0xF3, true, 0x00}, PacketInfo{"CharacterList", "ServerToClient", false, 0}},
	{RouteKey{0xC1, 0xF3, true, 0x00}, PacketInfo{"CharacterListExtended", "ServerToClient", false, 0}},
	{RouteKey{0xC1, 0xF3, true, 0x00}, PacketInfo{"CharacterList075", "ServerToClient", false, 0}},
	{RouteKey{0xC1, 0xF3, true, 0x00}, PacketInfo{"CharacterList095", "ServerToClient", false, 0}},
	{RouteKey{0xC1, 0xF3, true, 0x01}, PacketInfo{"CharacterCreationSuccessful", "ServerToClient", true, 42}},
	{RouteKey{0xC1, 0xF3, true, 0x01}, PacketInfo{"CharacterCreationFailed", "ServerToClient", true, 5}},
	{RouteKey{0xC1, 0xF3, true, 0x02}, PacketInfo{"CharacterDeleteResponse", "ServerToClient", true, 5}},
	{RouteKey{0xC1, 0xF3, true, 0x04}, PacketInfo{"RespawnAfterDeath075", "ServerToClient", true, 20}},
	{RouteKey{0xC1, 0xF3, true, 0x04}, PacketInfo{"RespawnAfterDeath095", "ServerToClient", true, 22}},
	{RouteKey{0xC1, 0xF3, true, 0x04}, PacketInfo{"RespawnAfterDeath", "ServerToClient", true, 28}},
	{RouteKey{0xC1, 0xF3, true, 0x04}, PacketInfo{"RespawnAfterDeathExtended", "ServerToClient", true, 36}},
	{RouteKey{0xC1, 0xF3, true, 0x05}, PacketInfo{"CharacterLevelUpdate", "ServerToClient", true, 24}},
	{RouteKey{0xC1, 0xF3, true, 0x05}, PacketInfo{"CharacterLevelUpdateExtended", "ServerToClient", true, 32}},
	{RouteKey{0xC1, 0xF3, true, 0x06}, PacketInfo{"CharacterStatIncreaseResponse", "ServerToClient", true, 12}},
	{RouteKey{0xC1, 0xF3, true, 0x06}, PacketInfo{"CharacterStatIncreaseResponseExtended", "ServerToClient", true, 24}},
	{RouteKey{0xC1, 0xF3, true, 0x07}, PacketInfo{"PoisonDamage", "ServerToClient", true, 8}},
	{RouteKey{0xC1, 0xF3, true, 0x08}, PacketInfo{"HeroStateChanged", "ServerToClient", true, 7}},
	{RouteKey{0xC1, 0xF3, true, 0x11}, PacketInfo{"SkillAdded", "ServerToClient", true, 10}},
	{RouteKey{0xC1, 0xF3, true, 0x11}, PacketInfo{"SkillRemoved", "ServerToClient", true, 10}},
	{RouteKey{0xC1, 0xF3, true, 0x11}, PacketInfo{"SkillListUpdate", "ServerToClient", false, 0}},
	{RouteKey{0xC1, 0xF3, true, 0x11}, PacketInfo{"SkillAdded075", "ServerToClient", true, 8}},
	{RouteKey{0xC1, 0xF3, true, 0x11}, PacketInfo{"SkillRemoved075", "ServerToClient", true, 10}},
	{RouteKey{0xC1, 0xF3, true, 0x11}, PacketInfo{"SkillAdded095", "ServerToClient", true, 8}},
	{RouteKey{0xC1, 0xF3, true, 0x11}, PacketInfo{"SkillRemoved095", "ServerToClient", true, 10}},
	{RouteKey{0xC1, 0xF3, true, 0x11}, PacketInfo{"SkillListUpdate075", "ServerToClient", false, 0}},
	{RouteKey{0xC1, 0xF3, true, 0x14}, PacketInfo{"InventoryItemUpgraded", "ServerToClient", false, 0}},
	{RouteKey{0xC1, 0xF3, true, 0x15}, PacketInfo{"CharacterFocused", "ServerToClient", true, 15}},
	{RouteKey{0xC1, 0xF3, true, 0x20}, PacketInfo{"SummonHealthUpdate", "ServerToClient", true, 5}},
	{RouteKey{0xC1, 0xF3, true, 0x22}, PacketInfo{"GuildSoccerTimeUpdate", "ServerToClient", true, 6}},
	{RouteKey{0xC1, 0xF3, true, 0x23}, PacketInfo{"GuildSoccerScoreUpdate", "ServerToClient", true, 22}},
	{RouteKey{0xC1, 0xF3, true, 0x30}, PacketInfo{"ApplyKeyConfiguration", "ServerToClient", false, 0}},
	{RouteKey{0xC1, 0xF3, true, 0x32}, PacketInfo{"BaseStatsExtended", "ServerToClient", true, 24}},
	{RouteKey{0xC1, 0xF3, true, 0x40}, PacketInfo{"ServerCommand", "ServerToClient", true, 7}},
	{RouteKey{0xC1, 0xF3, true, 0x40}, PacketInfo{"ShowFireworks", "ServerToClient", true, 7}},
	{RouteKey{0xC1, 0xF3, true, 0x40}, PacketInfo{"ShowChristmasFireworks", "ServerToClient", true, 7}},
	{RouteKey{0xC1, 0xF3, true, 0x40}, PacketInfo{"PlayFanfareSound", "ServerToClient", true, 7}},
	{RouteKey{0xC1, 0xF3, true, 0x40}, PacketInfo{"ShowSwirl", "ServerToClient", true, 7}},
	{RouteKey{0xC1, 0xF3, true, 0x50}, PacketInfo{"MasterStatsUpdate", "ServerToClient", true, 32}},
	{RouteKey{0xC1, 0xF3, true, 0x50}, PacketInfo{"MasterStatsUpdateExtended", "ServerToClient", true, 40}},
	{RouteKey{0xC1, 0xF3, true, 0x51}, PacketInfo{"MasterCharacterLevelUpdate", "ServerToClient", true, 20}},
	{RouteKey{0xC1, 0xF3, true, 0x51}, PacketInfo{"MasterCharacterLevelUpdateExtended", "ServerToClient", true, 28}},
	{RouteKey{0xC1, 0xF3, true, 0x52}, PacketInfo{"MasterSkillLevelUpdate", "ServerToClient", true, 28}},
	{RouteKey{0xC1, 0xF6, true, 0x03}, PacketInfo{"QuestEventResponse", "ServerToClient", true, 12}},
	{RouteKey{0xC1, 0xF6, true, 0x0A}, PacketInfo{"AvailableQuests", "ServerToClient", false, 0}},
	{RouteKey{0xC1, 0xF6, true, 0x0B}, PacketInfo{"QuestStepInfo", "ServerToClient", true, 11}},
	{RouteKey{0xC1, 0xF6, true, 0x0C}, PacketInfo{"QuestProgress", "ServerToClient", true, 251}},
	{RouteKey{0xC1, 0xF6, true, 0x0D}, PacketInfo{"QuestCompletionResponse", "ServerToClient", true, 9}},
	{RouteKey{0xC1, 0xF6, true, 0x0F}, PacketInfo{"QuestCancelled", "ServerToClient", true, 8}},
	{RouteKey{0xC1, 0xF6, true, 0x1A}, PacketInfo{"QuestStateList", "ServerToClient", false, 0}},
	{RouteKey{0xC1, 0xF6, true, 0x1B}, PacketInfo{"QuestState", "ServerToClient", true, 251}},
	{RouteKey{0xC2, 0x12, false, 0x00}, PacketInfo{"AddCharacterToScopeExtended", "ServerToClient", false, 0}},
	{RouteKey{0xC2, 0x12, false, 0x00}, PacketInfo{"AddCharactersToScope", "ServerToClient", false, 0}},
	{RouteKey{0xC2, 0x12, false, 0x00}, PacketInfo{"AddCharactersToScope075", "ServerToClient", false, 0}},
	{RouteKey{0xC2, 0x12, false, 0x00}, PacketInfo{"AddCharactersToScope095", "ServerToClient", false, 0}},
	{RouteKey{0xC2, 0x13, false, 0x00}, PacketInfo{"AddNpcsToScope", "ServerToClient", false, 0}},
	{RouteKey{0xC2, 0x13, false, 0x00}, PacketInfo{"AddNpcsToScope075", "ServerToClient", false, 0}},
	{RouteKey{0xC2, 0x13, false, 0x00}, PacketInfo{"AddNpcsToScope095", "ServerToClient", false, 0}},
	{RouteKey{0xC2, 0x1F, false, 0x00}, PacketInfo{"AddSummonedMonstersToScope", "ServerToClient", false, 0}},
	{RouteKey{0xC2, 0x1F, false, 0x00}, PacketInfo{"AddSummonedMonstersToScope075", "ServerToClient", false, 0}},
	{RouteKey{0xC2, 0x1F, false, 0x00}, PacketInfo{"AddSummonedMonstersToScope095", "ServerToClient", false, 0}},
	{RouteKey{0xC2, 0x20, false, 0x00}, PacketInfo{"ItemsDropped", "ServerToClient", false, 0}},
	{RouteKey{0xC2, 0x20, false, 0x00}, PacketInfo{"MoneyDropped", "ServerToClient", true, 21}},
	{RouteKey{0xC2, 0x20, false, 0x00}, PacketInfo{"MoneyDropped075", "ServerToClient", true, 14}},
	{RouteKey{0xC2, 0x21, false, 0x00}, PacketInfo{"ItemDropRemoved", "ServerToClient", false, 0}},
	{RouteKey{0xC2, 0x31, false, 0x00}, PacketInfo{"StoreItemList", "ServerToClient", false, 0}},
	{RouteKey{0xC2, 0x3F, true, 0x00}, PacketInfo{"PlayerShops", "ServerToClient", false, 0}},
	{RouteKey{0xC2, 0x3F, true, 0x05}, PacketInfo{"PlayerShopItemList", "ServerToClient", false, 0}},
	{RouteKey{0xC2, 0x3F, true, 0x05}, PacketInfo{"PlayerShopItemListExtended", "ServerToClient", false, 0}},
	{RouteKey{0xC2, 0x45, false, 0x00}, PacketInfo{"AddTransformedCharactersToScope075", "ServerToClient", false, 0}},
	{RouteKey{0xC2, 0x45, false, 0x00}, PacketInfo{"AddTransformedCharactersToScope", "ServerToClient", false, 0}},
	{RouteKey{0xC2, 0x52, false, 0x00}, PacketInfo{"GuildList", "ServerToClient", false, 0}},
	{RouteKey{0xC2, 0x52, false, 0x00}, PacketInfo{"GuildList075", "ServerToClient", false, 0}},
	{RouteKey{0xC2, 0x5A, false, 0x00}, PacketInfo{"GuildInformations075", "ServerToClient", false, 0}},
	{RouteKey{0xC2, 0x5B, false, 0x00}, PacketInfo{"AssignCharacterToGuild075", "ServerToClient", false, 0}},
	{RouteKey{0xC2, 0x65, false, 0x00}, PacketInfo{"AssignCharacterToGuild", "ServerToClient", false, 0}},
	{RouteKey{0xC2, 0xAE, false, 0x00}, PacketInfo{"MuHelperConfigurationData", "ServerToClient", true, 261}},
	{RouteKey{0xC2, 0xC0, false, 0x00}, PacketInfo{"MessengerInitialization", "ServerToClient", false, 0}},
	{RouteKey{0xC2, 0xE9, false, 0x00}, PacketInfo{"AllianceList", "ServerToClient", false, 0}},
	{RouteKey{0xC2, 0xF3, true, 0x53}, PacketInfo{"MasterSkillList", "ServerToClient", false, 0}},
	{RouteKey{0xC2, 0xF5, true, 0x01}, PacketInfo{"AvailableChatCommand", "ServerToClient", false, 0}},
	{RouteKey{0xC2, 0xF6, true, 0x0C}, PacketInfo{"QuestProgressExtended", "ServerToClient", true, 272}},
	{RouteKey{0xC2, 0xF6, true, 0x1B}, PacketInfo{"QuestStateExtended", "ServerToClient", true, 272}},
	{RouteKey{0xC3, 0x16, false, 0x00}, PacketInfo{"ExperienceGained", "ServerToClient", true, 9}},
	{RouteKey{0xC3, 0x16, false, 0x00}, PacketInfo{"ExperienceGainedExtended", "ServerToClient", true, 16}},
	{RouteKey{0xC3, 0x19, false, 0x00}, PacketInfo{"SkillAnimation", "ServerToClient", true, 9}},
	{RouteKey{0xC3, 0x19, false, 0x00}, PacketInfo{"SkillAnimation095", "ServerToClient", true, 8}},
	{RouteKey{0xC3, 0x1C, false, 0x00}, PacketInfo{"MapChanged075", "ServerToClient", true, 8}},
	{RouteKey{0xC3, 0x1C, true, 0x0F}, PacketInfo{"MapChanged", "ServerToClient", true, 15}},
	{RouteKey{0xC3, 0x1E, false, 0x00}, PacketInfo{"AreaSkillAnimation", "ServerToClient", true, 10}},
	{RouteKey{0xC3, 0x1E, false, 0x00}, PacketInfo{"AreaSkillAnimation095", "ServerToClient", true, 9}},
	{RouteKey{0xC3, 0x22, false, 0x00}, PacketInfo{"ItemAddedToInventory", "ServerToClient", false, 0}},
	{RouteKey{0xC3, 0x22, false, 0x00}, PacketInfo{"ItemPickUpRequestFailed", "ServerToClient", true, 4}},
	{RouteKey{0xC3, 0x22, true, 0xFE}, PacketInfo{"InventoryMoneyUpdate", "ServerToClient", true, 8}},
	{RouteKey{0xC3, 0x24, false, 0x00}, PacketInfo{"ItemMoved", "ServerToClient", false, 0}},
	{RouteKey{0xC3, 0x24, true, 0xFF}, PacketInfo{"ItemMoveRequestFailed", "ServerToClient", false, 0}},
	{RouteKey{0xC3, 0x29, false, 0x00}, PacketInfo{"ConsumeItemWithEffect", "ServerToClient", true, 6}},
	{RouteKey{0xC3, 0x30, false, 0x00}, PacketInfo{"NpcWindowResponse", "ServerToClient", true, 11}},
	{RouteKey{0xC3, 0x33, false, 0x00}, PacketInfo{"NpcItemSellResult", "ServerToClient", true, 8}},
	{RouteKey{0xC3, 0x36, false, 0x00}, PacketInfo{"TradeRequest", "ServerToClient", true, 13}},
	{RouteKey{0xC3, 0x3F, true, 0x01}, PacketInfo{"PlayerShopSetItemPriceResponse", "ServerToClient", true, 6}},
	{RouteKey{0xC3, 0x4A, false, 0x00}, PacketInfo{"RageAttack", "ServerToClient", true, 9}},
	{RouteKey{0xC3, 0xC6, false, 0x00}, PacketInfo{"AddLetter", "ServerToClient", true, 79}},
	{RouteKey{0xC3, 0xCA, false, 0x00}, PacketInfo{"ChatRoomConnectionInfo", "ServerToClient", true, 36}},
	{RouteKey{0xC3, 0xCB, false, 0x00}, PacketInfo{"FriendInvitationResult", "ServerToClient", true, 8}},
	{RouteKey{0xC3, 0xF1, true, 0x02}, PacketInfo{"LogoutResponse", "ServerToClient", true, 5}},
	{RouteKey{0xC3, 0xF3, true, 0x03}, PacketInfo{"CharacterInformation", "ServerToClient", true, 72}},
	{RouteKey{0xC3, 0xF3, true, 0x03}, PacketInfo{"CharacterInformationExtended", "ServerToClient", true, 92}},
	{RouteKey{0xC3, 0xF3, true, 0x03}, PacketInfo{"CharacterInformation075", "ServerToClient", true, 42}},
	{RouteKey{0xC3, 0xF3, true, 0x03}, PacketInfo{"CharacterInformation097", "ServerToClient", true, 52}},
	{RouteKey{0xC3, 0xF9, true, 0x01}, PacketInfo{"OpenNpcDialog", "ServerToClient", true, 12}},
	{RouteKey{0xC4, 0xC7, false, 0x00}, PacketInfo{"OpenLetter", "ServerToClient", false, 0}},
	{RouteKey{0xC4, 0xC7, false, 0x00}, PacketInfo{"OpenLetterExtended", "ServerToClient", false, 0}},
	{RouteKey{0xC4, 0xF3, true, 0x10}, PacketInfo{"CharacterInventory", "ServerToClient", false, 0}},
}

// Lookup 按精确键查包；重复键返回最先注册的条目。
func Lookup(key RouteKey) (PacketInfo, bool) {
	for _, e := range routes {
		if e.Key == key {
			return e.Info, true
		}
	}
	return PacketInfo{}, false
}

// LookupPacket 直接从一帧原始字节判定路由（C1/C3 的 Code 在偏移2，C2/C4 在偏移3）。
// 同时存在带/不带 SubCode 的条目时，优先匹配带 SubCode 的精确键。
func LookupPacket(buf []byte) (PacketInfo, bool) {
	if len(buf) < 3 {
		return PacketInfo{}, false
	}
	header := buf[0]
	codeIdx := 2
	if header == 0xC2 || header == 0xC4 {
		codeIdx = 3
	}
	if len(buf) <= codeIdx {
		return PacketInfo{}, false
	}
	code := buf[codeIdx]
	if len(buf) > codeIdx+1 {
		if info, ok := Lookup(RouteKey{header, code, true, buf[codeIdx+1]}); ok {
			return info, true
		}
	}
	return Lookup(RouteKey{header, code, false, 0})
}
