// Code generated by muprotogen; DO NOT EDIT.

package s2c

import "testing"

func TestFixedPacketsLayout(t *testing.T) {
	cases := []struct {
		name   string
		size   int
		header byte
		code   byte
		hasSub bool
		sub    byte
		mk     func() []byte
	}{
		{"GameServerEntered", 12, 0xC1, 0xF1, true, 0x00, func() []byte { return NewGameServerEntered().Bytes() }},
		{"MagicEffectStatus", 7, 0xC1, 0x07, false, 0x00, func() []byte { return NewMagicEffectStatus().Bytes() }},
		{"WeatherStatusUpdate", 4, 0xC1, 0x0F, false, 0x00, func() []byte { return NewWeatherStatusUpdate().Bytes() }},
		{"ObjectGotKilled", 9, 0xC1, 0x17, false, 0x00, func() []byte { return NewObjectGotKilled().Bytes() }},
		{"ObjectAnimation", 9, 0xC1, 0x18, false, 0x00, func() []byte { return NewObjectAnimation().Bytes() }},
		{"AreaSkillAnimation", 10, 0xC3, 0x1E, false, 0x00, func() []byte { return NewAreaSkillAnimation().Bytes() }},
		{"SkillAnimation", 9, 0xC3, 0x19, false, 0x00, func() []byte { return NewSkillAnimation().Bytes() }},
		{"AreaSkillAnimation075", 9, 0xC1, 0x1E, false, 0x00, func() []byte { return NewAreaSkillAnimation075().Bytes() }},
		{"AreaSkillAnimation095", 9, 0xC3, 0x1E, false, 0x00, func() []byte { return NewAreaSkillAnimation095().Bytes() }},
		{"SkillAnimation075", 8, 0xC1, 0x19, false, 0x00, func() []byte { return NewSkillAnimation075().Bytes() }},
		{"SkillAnimation095", 8, 0xC3, 0x19, false, 0x00, func() []byte { return NewSkillAnimation095().Bytes() }},
		{"MagicEffectCancelled", 7, 0xC1, 0x1B, false, 0x00, func() []byte { return NewMagicEffectCancelled().Bytes() }},
		{"MagicEffectCancelled075", 6, 0xC1, 0x1B, false, 0x00, func() []byte { return NewMagicEffectCancelled075().Bytes() }},
		{"RageAttack", 9, 0xC3, 0x4A, false, 0x00, func() []byte { return NewRageAttack().Bytes() }},
		{"RageAttackRangeResponse", 16, 0xC1, 0x4B, false, 0x00, func() []byte { return NewRageAttackRangeResponse().Bytes() }},
		{"AppearanceChangedExtended", 14, 0xC1, 0x25, false, 0x00, func() []byte { return NewAppearanceChangedExtended().Bytes() }},
		{"PartyRequest", 5, 0xC1, 0x40, false, 0x00, func() []byte { return NewPartyRequest().Bytes() }},
		{"RemovePartyMember", 4, 0xC1, 0x43, false, 0x00, func() []byte { return NewRemovePartyMember().Bytes() }},
		{"PlayerShopOpenSuccessful", 5, 0xC1, 0x3F, true, 0x02, func() []byte { return NewPlayerShopOpenSuccessful().Bytes() }},
		{"TradeButtonStateChanged", 4, 0xC1, 0x3C, false, 0x00, func() []byte { return NewTradeButtonStateChanged().Bytes() }},
		{"TradeMoneySetResponse", 4, 0xC1, 0x3A, true, 0x01, func() []byte { return NewTradeMoneySetResponse().Bytes() }},
		{"TradeMoneyUpdate", 8, 0xC1, 0x3B, false, 0x00, func() []byte { return NewTradeMoneyUpdate().Bytes() }},
		{"TradeRequestAnswer", 20, 0xC1, 0x37, false, 0x00, func() []byte { return NewTradeRequestAnswer().Bytes() }},
		{"TradeRequest", 13, 0xC3, 0x36, false, 0x00, func() []byte { return NewTradeRequest().Bytes() }},
		{"TradeFinished", 4, 0xC1, 0x3D, false, 0x00, func() []byte { return NewTradeFinished().Bytes() }},
		{"TradeItemRemoved", 4, 0xC1, 0x38, false, 0x00, func() []byte { return NewTradeItemRemoved().Bytes() }},
		{"LoginResponse", 5, 0xC1, 0xF1, true, 0x01, func() []byte { return NewLoginResponse().Bytes() }},
		{"LogoutResponse", 5, 0xC3, 0xF1, true, 0x02, func() []byte { return NewLogoutResponse().Bytes() }},
		{"ObjectHit", 10, 0xC1, 0x11, false, 0x00, func() []byte { return NewObjectHit().Bytes() }},
		{"ObjectHitExtended", 16, 0xC1, 0x11, false, 0x00, func() []byte { return NewObjectHitExtended().Bytes() }},
		{"ObjectMoved", 8, 0xC1, 0x15, false, 0x00, func() []byte { return NewObjectMoved().Bytes() }},
		{"ObjectWalked075", 8, 0xC1, 0x10, false, 0x00, func() []byte { return NewObjectWalked075().Bytes() }},
		{"ExperienceGained", 9, 0xC3, 0x16, false, 0x00, func() []byte { return NewExperienceGained().Bytes() }},
		{"ExperienceGainedExtended", 16, 0xC3, 0x16, false, 0x00, func() []byte { return NewExperienceGainedExtended().Bytes() }},
		{"MapChanged", 15, 0xC3, 0x1C, true, 0x0F, func() []byte { return NewMapChanged().Bytes() }},
		{"MapChanged075", 8, 0xC3, 0x1C, false, 0x00, func() []byte { return NewMapChanged075().Bytes() }},
		{"MoneyDropped", 21, 0xC2, 0x20, false, 0x00, func() []byte { return NewMoneyDropped().Bytes() }},
		{"MoneyDroppedExtended", 12, 0xC1, 0x2F, false, 0x00, func() []byte { return NewMoneyDroppedExtended().Bytes() }},
		{"MoneyDropped075", 14, 0xC2, 0x20, false, 0x00, func() []byte { return NewMoneyDropped075().Bytes() }},
		{"ItemDropResponse", 5, 0xC1, 0x23, false, 0x00, func() []byte { return NewItemDropResponse().Bytes() }},
		{"ItemPickUpRequestFailed", 4, 0xC3, 0x22, false, 0x00, func() []byte { return NewItemPickUpRequestFailed().Bytes() }},
		{"InventoryMoneyUpdate", 8, 0xC3, 0x22, true, 0xFE, func() []byte { return NewInventoryMoneyUpdate().Bytes() }},
		{"CurrentHealthAndShield", 9, 0xC1, 0x26, true, 0xFF, func() []byte { return NewCurrentHealthAndShield().Bytes() }},
		{"MaximumHealthAndShield", 9, 0xC1, 0x26, true, 0xFE, func() []byte { return NewMaximumHealthAndShield().Bytes() }},
		{"CurrentStatsExtended", 24, 0xC1, 0x26, true, 0xFF, func() []byte { return NewCurrentStatsExtended().Bytes() }},
		{"MaximumStatsExtended", 20, 0xC1, 0x26, true, 0xFE, func() []byte { return NewMaximumStatsExtended().Bytes() }},
		{"ItemConsumptionFailed", 9, 0xC1, 0x26, true, 0xFD, func() []byte { return NewItemConsumptionFailed().Bytes() }},
		{"ItemConsumptionFailedExtended", 12, 0xC1, 0x26, true, 0xFD, func() []byte { return NewItemConsumptionFailedExtended().Bytes() }},
		{"BaseStatsExtended", 24, 0xC1, 0xF3, true, 0x32, func() []byte { return NewBaseStatsExtended().Bytes() }},
		{"CurrentManaAndAbility", 8, 0xC1, 0x27, true, 0xFF, func() []byte { return NewCurrentManaAndAbility().Bytes() }},
		{"MaximumManaAndAbility", 8, 0xC1, 0x27, true, 0xFE, func() []byte { return NewMaximumManaAndAbility().Bytes() }},
		{"ItemRemoved", 5, 0xC1, 0x28, false, 0x00, func() []byte { return NewItemRemoved().Bytes() }},
		{"ConsumeItemWithEffect", 6, 0xC3, 0x29, false, 0x00, func() []byte { return NewConsumeItemWithEffect().Bytes() }},
		{"ItemDurabilityChanged", 6, 0xC1, 0x2A, false, 0x00, func() []byte { return NewItemDurabilityChanged().Bytes() }},
		{"FruitConsumptionResponse", 7, 0xC1, 0x2C, false, 0x00, func() []byte { return NewFruitConsumptionResponse().Bytes() }},
		{"EffectItemConsumption", 17, 0xC1, 0x2D, false, 0x00, func() []byte { return NewEffectItemConsumption().Bytes() }},
		{"NpcWindowResponse", 11, 0xC3, 0x30, false, 0x00, func() []byte { return NewNpcWindowResponse().Bytes() }},
		{"NpcItemBuyFailed", 4, 0xC1, 0x32, true, 0xFF, func() []byte { return NewNpcItemBuyFailed().Bytes() }},
		{"NpcItemSellResult", 8, 0xC3, 0x33, false, 0x00, func() []byte { return NewNpcItemSellResult().Bytes() }},
		{"PlayerShopSetItemPriceResponse", 6, 0xC3, 0x3F, true, 0x01, func() []byte { return NewPlayerShopSetItemPriceResponse().Bytes() }},
		{"PlayerShopClosed", 7, 0xC1, 0x3F, true, 0x03, func() []byte { return NewPlayerShopClosed().Bytes() }},
		{"PlayerShopItemSoldToPlayer", 15, 0xC1, 0x3F, true, 0x08, func() []byte { return NewPlayerShopItemSoldToPlayer().Bytes() }},
		{"ClosePlayerShopDialog", 6, 0xC1, 0x3F, true, 0x12, func() []byte { return NewClosePlayerShopDialog().Bytes() }},
		{"PlayerShopBuyResult", 21, 0xC1, 0x3F, true, 0x06, func() []byte { return NewPlayerShopBuyResult().Bytes() }},
		{"ShowEffect", 6, 0xC1, 0x48, false, 0x00, func() []byte { return NewShowEffect().Bytes() }},
		{"CharacterClassCreationUnlock", 5, 0xC1, 0xDE, true, 0x00, func() []byte { return NewCharacterClassCreationUnlock().Bytes() }},
		{"CharacterCreationSuccessful", 42, 0xC1, 0xF3, true, 0x01, func() []byte { return NewCharacterCreationSuccessful().Bytes() }},
		{"CharacterCreationFailed", 5, 0xC1, 0xF3, true, 0x01, func() []byte { return NewCharacterCreationFailed().Bytes() }},
		{"RespawnAfterDeath075", 20, 0xC1, 0xF3, true, 0x04, func() []byte { return NewRespawnAfterDeath075().Bytes() }},
		{"RespawnAfterDeath095", 22, 0xC1, 0xF3, true, 0x04, func() []byte { return NewRespawnAfterDeath095().Bytes() }},
		{"RespawnAfterDeath", 28, 0xC1, 0xF3, true, 0x04, func() []byte { return NewRespawnAfterDeath().Bytes() }},
		{"RespawnAfterDeathExtended", 36, 0xC1, 0xF3, true, 0x04, func() []byte { return NewRespawnAfterDeathExtended().Bytes() }},
		{"PoisonDamage", 8, 0xC1, 0xF3, true, 0x07, func() []byte { return NewPoisonDamage().Bytes() }},
		{"HeroStateChanged", 7, 0xC1, 0xF3, true, 0x08, func() []byte { return NewHeroStateChanged().Bytes() }},
		{"SkillAdded", 10, 0xC1, 0xF3, true, 0x11, func() []byte { return NewSkillAdded().Bytes() }},
		{"SkillRemoved", 10, 0xC1, 0xF3, true, 0x11, func() []byte { return NewSkillRemoved().Bytes() }},
		{"SkillAdded075", 8, 0xC1, 0xF3, true, 0x11, func() []byte { return NewSkillAdded075().Bytes() }},
		{"SkillRemoved075", 10, 0xC1, 0xF3, true, 0x11, func() []byte { return NewSkillRemoved075().Bytes() }},
		{"SkillAdded095", 8, 0xC1, 0xF3, true, 0x11, func() []byte { return NewSkillAdded095().Bytes() }},
		{"SkillRemoved095", 10, 0xC1, 0xF3, true, 0x11, func() []byte { return NewSkillRemoved095().Bytes() }},
		{"CharacterFocused", 15, 0xC1, 0xF3, true, 0x15, func() []byte { return NewCharacterFocused().Bytes() }},
		{"CharacterStatIncreaseResponse", 12, 0xC1, 0xF3, true, 0x06, func() []byte { return NewCharacterStatIncreaseResponse().Bytes() }},
		{"CharacterStatIncreaseResponseExtended", 24, 0xC1, 0xF3, true, 0x06, func() []byte { return NewCharacterStatIncreaseResponseExtended().Bytes() }},
		{"CharacterDeleteResponse", 5, 0xC1, 0xF3, true, 0x02, func() []byte { return NewCharacterDeleteResponse().Bytes() }},
		{"CharacterLevelUpdate", 24, 0xC1, 0xF3, true, 0x05, func() []byte { return NewCharacterLevelUpdate().Bytes() }},
		{"CharacterInformation", 72, 0xC3, 0xF3, true, 0x03, func() []byte { return NewCharacterInformation().Bytes() }},
		{"CharacterLevelUpdateExtended", 32, 0xC1, 0xF3, true, 0x05, func() []byte { return NewCharacterLevelUpdateExtended().Bytes() }},
		{"CharacterInformationExtended", 92, 0xC3, 0xF3, true, 0x03, func() []byte { return NewCharacterInformationExtended().Bytes() }},
		{"CharacterInformation075", 42, 0xC3, 0xF3, true, 0x03, func() []byte { return NewCharacterInformation075().Bytes() }},
		{"CharacterInformation097", 52, 0xC3, 0xF3, true, 0x03, func() []byte { return NewCharacterInformation097().Bytes() }},
		{"SummonHealthUpdate", 5, 0xC1, 0xF3, true, 0x20, func() []byte { return NewSummonHealthUpdate().Bytes() }},
		{"GuildSoccerTimeUpdate", 6, 0xC1, 0xF3, true, 0x22, func() []byte { return NewGuildSoccerTimeUpdate().Bytes() }},
		{"GuildSoccerScoreUpdate", 22, 0xC1, 0xF3, true, 0x23, func() []byte { return NewGuildSoccerScoreUpdate().Bytes() }},
		{"ServerCommand", 7, 0xC1, 0xF3, true, 0x40, func() []byte { return NewServerCommand().Bytes() }},
		{"ShowFireworks", 7, 0xC1, 0xF3, true, 0x40, func() []byte { return NewShowFireworks().Bytes() }},
		{"ShowChristmasFireworks", 7, 0xC1, 0xF3, true, 0x40, func() []byte { return NewShowChristmasFireworks().Bytes() }},
		{"PlayFanfareSound", 7, 0xC1, 0xF3, true, 0x40, func() []byte { return NewPlayFanfareSound().Bytes() }},
		{"ShowSwirl", 7, 0xC1, 0xF3, true, 0x40, func() []byte { return NewShowSwirl().Bytes() }},
		{"MasterStatsUpdate", 32, 0xC1, 0xF3, true, 0x50, func() []byte { return NewMasterStatsUpdate().Bytes() }},
		{"MasterStatsUpdateExtended", 40, 0xC1, 0xF3, true, 0x50, func() []byte { return NewMasterStatsUpdateExtended().Bytes() }},
		{"MasterCharacterLevelUpdate", 20, 0xC1, 0xF3, true, 0x51, func() []byte { return NewMasterCharacterLevelUpdate().Bytes() }},
		{"MasterCharacterLevelUpdateExtended", 28, 0xC1, 0xF3, true, 0x51, func() []byte { return NewMasterCharacterLevelUpdateExtended().Bytes() }},
		{"MasterSkillLevelUpdate", 28, 0xC1, 0xF3, true, 0x52, func() []byte { return NewMasterSkillLevelUpdate().Bytes() }},
		{"GuildJoinRequest", 5, 0xC1, 0x50, false, 0x00, func() []byte { return NewGuildJoinRequest().Bytes() }},
		{"GuildJoinResponse", 4, 0xC1, 0x51, false, 0x00, func() []byte { return NewGuildJoinResponse().Bytes() }},
		{"GuildKickResponse", 4, 0xC1, 0x53, false, 0x00, func() []byte { return NewGuildKickResponse().Bytes() }},
		{"ShowGuildMasterDialog", 3, 0xC1, 0x54, false, 0x00, func() []byte { return NewShowGuildMasterDialog().Bytes() }},
		{"ShowGuildCreationDialog", 3, 0xC1, 0x55, false, 0x00, func() []byte { return NewShowGuildCreationDialog().Bytes() }},
		{"GuildCreationResult", 5, 0xC1, 0x56, false, 0x00, func() []byte { return NewGuildCreationResult().Bytes() }},
		{"GuildMemberLeftGuild", 5, 0xC1, 0x5D, false, 0x00, func() []byte { return NewGuildMemberLeftGuild().Bytes() }},
		{"GuildWarRequestResult", 4, 0xC1, 0x60, false, 0x00, func() []byte { return NewGuildWarRequestResult().Bytes() }},
		{"GuildWarRequest", 12, 0xC1, 0x61, false, 0x00, func() []byte { return NewGuildWarRequest().Bytes() }},
		{"GuildWarDeclared", 13, 0xC1, 0x62, false, 0x00, func() []byte { return NewGuildWarDeclared().Bytes() }},
		{"GuildWarEnded", 12, 0xC1, 0x63, false, 0x00, func() []byte { return NewGuildWarEnded().Bytes() }},
		{"GuildWarScoreUpdate", 6, 0xC1, 0x64, false, 0x00, func() []byte { return NewGuildWarScoreUpdate().Bytes() }},
		{"GuildRelationshipRequest", 7, 0xC1, 0xE5, false, 0x00, func() []byte { return NewGuildRelationshipRequest().Bytes() }},
		{"GuildRelationshipChangeResult", 8, 0xC1, 0xE6, false, 0x00, func() []byte { return NewGuildRelationshipChangeResult().Bytes() }},
		{"RemoveAllianceGuildResult", 7, 0xC1, 0xEB, true, 0x01, func() []byte { return NewRemoveAllianceGuildResult().Bytes() }},
		{"GuildInformation", 60, 0xC1, 0x66, false, 0x00, func() []byte { return NewGuildInformation().Bytes() }},
		{"SingleGuildInformation075", 45, 0xC1, 0x5C, false, 0x00, func() []byte { return NewSingleGuildInformation075().Bytes() }},
		{"VaultMoneyUpdate", 12, 0xC1, 0x81, false, 0x00, func() []byte { return NewVaultMoneyUpdate().Bytes() }},
		{"VaultClosed", 3, 0xC1, 0x82, false, 0x00, func() []byte { return NewVaultClosed().Bytes() }},
		{"VaultProtectionInformation", 4, 0xC1, 0x83, false, 0x00, func() []byte { return NewVaultProtectionInformation().Bytes() }},
		{"CraftingDialogClosed075", 3, 0xC1, 0x87, false, 0x00, func() []byte { return NewCraftingDialogClosed075().Bytes() }},
		{"LegacyQuestStateDialog", 5, 0xC1, 0xA1, false, 0x00, func() []byte { return NewLegacyQuestStateDialog().Bytes() }},
		{"LegacySetQuestStateResponse", 6, 0xC1, 0xA2, false, 0x00, func() []byte { return NewLegacySetQuestStateResponse().Bytes() }},
		{"LegacyQuestReward", 7, 0xC1, 0xA3, false, 0x00, func() []byte { return NewLegacyQuestReward().Bytes() }},
		{"LegacyQuestMonsterKillInfo", 48, 0xC1, 0xA4, true, 0x00, func() []byte { return NewLegacyQuestMonsterKillInfo().Bytes() }},
		{"PetMode", 7, 0xC1, 0xA7, false, 0x00, func() []byte { return NewPetMode().Bytes() }},
		{"PetAttack", 9, 0xC1, 0xA8, false, 0x00, func() []byte { return NewPetAttack().Bytes() }},
		{"PetInfoResponse", 13, 0xC1, 0xA9, false, 0x00, func() []byte { return NewPetInfoResponse().Bytes() }},
		{"DuelStartResult", 17, 0xC1, 0xAA, true, 0x01, func() []byte { return NewDuelStartResult().Bytes() }},
		{"DuelStartRequest", 16, 0xC1, 0xAA, true, 0x02, func() []byte { return NewDuelStartRequest().Bytes() }},
		{"DuelEnd", 17, 0xC1, 0xAA, true, 0x03, func() []byte { return NewDuelEnd().Bytes() }},
		{"DuelScore", 10, 0xC1, 0xAA, true, 0x04, func() []byte { return NewDuelScore().Bytes() }},
		{"DuelHealthUpdate", 12, 0xC1, 0xAA, true, 0x05, func() []byte { return NewDuelHealthUpdate().Bytes() }},
		{"DuelStatus", 92, 0xC1, 0xAA, true, 0x06, func() []byte { return NewDuelStatus().Bytes() }},
		{"DuelInit", 30, 0xC1, 0xAA, true, 0x07, func() []byte { return NewDuelInit().Bytes() }},
		{"DuelHealthBarInit", 4, 0xC1, 0xAA, true, 0x0D, func() []byte { return NewDuelHealthBarInit().Bytes() }},
		{"DuelSpectatorAdded", 14, 0xC1, 0xAA, true, 0x08, func() []byte { return NewDuelSpectatorAdded().Bytes() }},
		{"DuelSpectatorRemoved", 14, 0xC1, 0xAA, true, 0x0A, func() []byte { return NewDuelSpectatorRemoved().Bytes() }},
		{"DuelSpectatorList", 105, 0xC1, 0xAA, true, 0x0B, func() []byte { return NewDuelSpectatorList().Bytes() }},
		{"DuelFinished", 24, 0xC1, 0xAA, true, 0x0C, func() []byte { return NewDuelFinished().Bytes() }},
		{"SkillStageUpdate", 7, 0xC1, 0xBA, false, 0x00, func() []byte { return NewSkillStageUpdate().Bytes() }},
		{"IllusionTempleEnterResult", 5, 0xC1, 0xBF, true, 0x00, func() []byte { return NewIllusionTempleEnterResult().Bytes() }},
		{"IllusionTempleSkillUsageResult", 11, 0xC1, 0xBF, true, 0x02, func() []byte { return NewIllusionTempleSkillUsageResult().Bytes() }},
		{"IllusionTempleUserCount", 10, 0xC1, 0xBF, true, 0x03, func() []byte { return NewIllusionTempleUserCount().Bytes() }},
		{"IllusionTempleSkillPointUpdate", 5, 0xC1, 0xBF, true, 0x06, func() []byte { return NewIllusionTempleSkillPointUpdate().Bytes() }},
		{"IllusionTempleSkillEnded", 8, 0xC1, 0xBF, true, 0x07, func() []byte { return NewIllusionTempleSkillEnded().Bytes() }},
		{"IllusionTempleHolyItemRelics", 16, 0xC1, 0xBF, true, 0x08, func() []byte { return NewIllusionTempleHolyItemRelics().Bytes() }},
		{"IllusionTempleSkillEnd", 6, 0xC1, 0xBF, true, 0x07, func() []byte { return NewIllusionTempleSkillEnd().Bytes() }},
		{"MuHelperStatusUpdate", 16, 0xC1, 0xBF, true, 0x51, func() []byte { return NewMuHelperStatusUpdate().Bytes() }},
		{"MuHelperConfigurationData", 261, 0xC2, 0xAE, false, 0x00, func() []byte { return NewMuHelperConfigurationData().Bytes() }},
		{"FriendAdded", 15, 0xC1, 0xC1, true, 0x01, func() []byte { return NewFriendAdded().Bytes() }},
		{"FriendRequest", 13, 0xC1, 0xC2, false, 0x00, func() []byte { return NewFriendRequest().Bytes() }},
		{"FriendDeleted", 14, 0xC1, 0xC3, true, 0x01, func() []byte { return NewFriendDeleted().Bytes() }},
		{"FriendOnlineStateUpdate", 14, 0xC1, 0xC4, false, 0x00, func() []byte { return NewFriendOnlineStateUpdate().Bytes() }},
		{"LetterSendResponse", 8, 0xC1, 0xC5, false, 0x00, func() []byte { return NewLetterSendResponse().Bytes() }},
		{"AddLetter", 79, 0xC3, 0xC6, false, 0x00, func() []byte { return NewAddLetter().Bytes() }},
		{"RemoveLetter", 6, 0xC1, 0xC8, false, 0x00, func() []byte { return NewRemoveLetter().Bytes() }},
		{"ChatRoomConnectionInfo", 36, 0xC3, 0xCA, false, 0x00, func() []byte { return NewChatRoomConnectionInfo().Bytes() }},
		{"FriendInvitationResult", 8, 0xC3, 0xCB, false, 0x00, func() []byte { return NewFriendInvitationResult().Bytes() }},
		{"QuestEventResponse", 12, 0xC1, 0xF6, true, 0x03, func() []byte { return NewQuestEventResponse().Bytes() }},
		{"QuestStepInfo", 11, 0xC1, 0xF6, true, 0x0B, func() []byte { return NewQuestStepInfo().Bytes() }},
		{"QuestProgress", 251, 0xC1, 0xF6, true, 0x0C, func() []byte { return NewQuestProgress().Bytes() }},
		{"QuestProgressExtended", 272, 0xC2, 0xF6, true, 0x0C, func() []byte { return NewQuestProgressExtended().Bytes() }},
		{"QuestCompletionResponse", 9, 0xC1, 0xF6, true, 0x0D, func() []byte { return NewQuestCompletionResponse().Bytes() }},
		{"QuestCancelled", 8, 0xC1, 0xF6, true, 0x0F, func() []byte { return NewQuestCancelled().Bytes() }},
		{"QuestState", 251, 0xC1, 0xF6, true, 0x1B, func() []byte { return NewQuestState().Bytes() }},
		{"QuestStateExtended", 272, 0xC2, 0xF6, true, 0x1B, func() []byte { return NewQuestStateExtended().Bytes() }},
		{"OpenNpcDialog", 12, 0xC3, 0xF9, true, 0x01, func() []byte { return NewOpenNpcDialog().Bytes() }},
		{"DevilSquareEnterResult", 4, 0xC1, 0x90, false, 0x00, func() []byte { return NewDevilSquareEnterResult().Bytes() }},
		{"MiniGameOpeningState", 7, 0xC1, 0x91, false, 0x00, func() []byte { return NewMiniGameOpeningState().Bytes() }},
		{"UpdateMiniGameState", 4, 0xC1, 0x92, false, 0x00, func() []byte { return NewUpdateMiniGameState().Bytes() }},
		{"BloodCastleScore", 29, 0xC1, 0x93, false, 0x00, func() []byte { return NewBloodCastleScore().Bytes() }},
		{"BloodCastleEnterResult", 4, 0xC1, 0x9A, false, 0x00, func() []byte { return NewBloodCastleEnterResult().Bytes() }},
		{"BloodCastleState", 13, 0xC1, 0x9B, false, 0x00, func() []byte { return NewBloodCastleState().Bytes() }},
		{"ChaosCastleEnterResult", 5, 0xC1, 0xAF, true, 0x01, func() []byte { return NewChaosCastleEnterResult().Bytes() }},
		{"MapEventState", 5, 0xC1, 0x0B, false, 0x00, func() []byte { return NewMapEventState().Bytes() }},
	}
	for _, tc := range cases {
		buf := tc.mk()
		if len(buf) != tc.size {
			t.Errorf("%s: got %d bytes, want %d", tc.name, len(buf), tc.size)
		}
		if buf[0] != tc.header {
			t.Errorf("%s: header 0x%02X, want 0x%02X", tc.name, buf[0], tc.header)
		}
		codeIdx := 2
		if tc.header == 0xC2 || tc.header == 0xC4 {
			codeIdx = 3
		}
		if buf[codeIdx] != tc.code {
			t.Errorf("%s: code 0x%02X, want 0x%02X", tc.name, buf[codeIdx], tc.code)
		}
		if tc.hasSub && buf[codeIdx+1] != tc.sub {
			t.Errorf("%s: sub 0x%02X, want 0x%02X", tc.name, buf[codeIdx+1], tc.sub)
		}
	}
}

func TestFixedStructSizes(t *testing.T) {
	cases := []struct {
		name string
		size int
		mk   func() []byte
	}{
		{"PlayerShopItem", 20, func() []byte { b := make([]byte, PlayerShopItemLength); _ = AsPlayerShopItem(b); return b }},
		{"QuestIdentification", 4, func() []byte { b := make([]byte, QuestIdentificationLength); _ = AsQuestIdentification(b); return b }},
		{"QuestCondition", 26, func() []byte { b := make([]byte, QuestConditionLength); _ = AsQuestCondition(b); return b }},
		{"QuestReward", 22, func() []byte { b := make([]byte, QuestRewardLength); _ = AsQuestReward(b); return b }},
		{"QuestConditionExtended", 28, func() []byte {
			b := make([]byte, QuestConditionExtendedLength)
			_ = AsQuestConditionExtended(b)
			return b
		}},
		{"QuestRewardExtended", 24, func() []byte { b := make([]byte, QuestRewardExtendedLength); _ = AsQuestRewardExtended(b); return b }},
		{"EffectId", 1, func() []byte { b := make([]byte, EffectIdLength); _ = AsEffectId(b); return b }},
		{"CharacterData2", 27, func() []byte { b := make([]byte, CharacterData2Length); _ = AsCharacterData2(b); return b }},
		{"CharacterData3", 31, func() []byte { b := make([]byte, CharacterData3Length); _ = AsCharacterData3(b); return b }},
		{"NpcData", 10, func() []byte { b := make([]byte, NpcDataLength); _ = AsNpcData(b); return b }},
		{"NpcData2", 9, func() []byte { b := make([]byte, NpcData2Length); _ = AsNpcData2(b); return b }},
		{"NpcData3", 12, func() []byte { b := make([]byte, NpcData3Length); _ = AsNpcData3(b); return b }},
		{"EffectId2", 1, func() []byte { b := make([]byte, EffectId2Length); _ = AsEffectId2(b); return b }},
		{"SummonedMonsterData2", 19, func() []byte { b := make([]byte, SummonedMonsterData2Length); _ = AsSummonedMonsterData2(b); return b }},
		{"SummonedMonsterData3", 20, func() []byte { b := make([]byte, SummonedMonsterData3Length); _ = AsSummonedMonsterData3(b); return b }},
		{"ObjectId", 2, func() []byte { b := make([]byte, ObjectIdLength); _ = AsObjectId(b); return b }},
		{"RageTarget", 2, func() []byte { b := make([]byte, RageTargetLength); _ = AsRageTarget(b); return b }},
		{"PartyMember", 24, func() []byte { b := make([]byte, PartyMemberLength); _ = AsPartyMember(b); return b }},
		{"PartyMember2", 14, func() []byte { b := make([]byte, PartyMember2Length); _ = AsPartyMember2(b); return b }},
		{"PartyMemberHealth", 1, func() []byte { b := make([]byte, PartyMemberHealthLength); _ = AsPartyMemberHealth(b); return b }},
		{"DroppedItemId", 2, func() []byte { b := make([]byte, DroppedItemIdLength); _ = AsDroppedItemId(b); return b }},
		{"PlayerShop", 38, func() []byte { b := make([]byte, PlayerShopLength); _ = AsPlayerShop(b); return b }},
		{"CharacterData4", 19, func() []byte { b := make([]byte, CharacterData4Length); _ = AsCharacterData4(b); return b }},
		{"EffectId3", 1, func() []byte { b := make([]byte, EffectId3Length); _ = AsEffectId3(b); return b }},
		{"TerrainArea", 4, func() []byte { b := make([]byte, TerrainAreaLength); _ = AsTerrainArea(b); return b }},
		{"CharacterData6", 34, func() []byte { b := make([]byte, CharacterData6Length); _ = AsCharacterData6(b); return b }},
		{"CharacterData7", 44, func() []byte { b := make([]byte, CharacterData7Length); _ = AsCharacterData7(b); return b }},
		{"CharacterData8", 24, func() []byte { b := make([]byte, CharacterData8Length); _ = AsCharacterData8(b); return b }},
		{"CharacterData9", 26, func() []byte { b := make([]byte, CharacterData9Length); _ = AsCharacterData9(b); return b }},
		{"SkillEntry", 4, func() []byte { b := make([]byte, SkillEntryLength); _ = AsSkillEntry(b); return b }},
		{"SkillEntry2", 3, func() []byte { b := make([]byte, SkillEntry2Length); _ = AsSkillEntry2(b); return b }},
		{"MasterSkillEntry", 12, func() []byte { b := make([]byte, MasterSkillEntryLength); _ = AsMasterSkillEntry(b); return b }},
		{"GuildMember", 13, func() []byte { b := make([]byte, GuildMemberLength); _ = AsGuildMember(b); return b }},
		{"GuildMember2", 12, func() []byte { b := make([]byte, GuildMember2Length); _ = AsGuildMember2(b); return b }},
		{"AllianceGuildEntry", 41, func() []byte { b := make([]byte, AllianceGuildEntryLength); _ = AsAllianceGuildEntry(b); return b }},
		{"GuildMemberRelation", 12, func() []byte { b := make([]byte, GuildMemberRelationLength); _ = AsGuildMemberRelation(b); return b }},
		{"GuildMemberRelation2", 4, func() []byte { b := make([]byte, GuildMemberRelation2Length); _ = AsGuildMemberRelation2(b); return b }},
		{"GuildInfo", 42, func() []byte { b := make([]byte, GuildInfoLength); _ = AsGuildInfo(b); return b }},
		{"MonsterKillInfo", 8, func() []byte { b := make([]byte, MonsterKillInfoLength); _ = AsMonsterKillInfo(b); return b }},
		{"DuelRoomStatus", 22, func() []byte { b := make([]byte, DuelRoomStatusLength); _ = AsDuelRoomStatus(b); return b }},
		{"DuelSpectator", 10, func() []byte { b := make([]byte, DuelSpectatorLength); _ = AsDuelSpectator(b); return b }},
		{"IllusionTemplePartyEntry", 5, func() []byte {
			b := make([]byte, IllusionTemplePartyEntryLength)
			_ = AsIllusionTemplePartyEntry(b)
			return b
		}},
		{"PlayerResult", 17, func() []byte { b := make([]byte, PlayerResultLength); _ = AsPlayerResult(b); return b }},
		{"ChainTarget", 2, func() []byte { b := make([]byte, ChainTargetLength); _ = AsChainTarget(b); return b }},
		{"Friend", 11, func() []byte { b := make([]byte, FriendLength); _ = AsFriend(b); return b }},
		{"ResultItem", 24, func() []byte { b := make([]byte, ResultItemLength); _ = AsResultItem(b); return b }},
		{"ChatCommandParameter", 102, func() []byte { b := make([]byte, ChatCommandParameterLength); _ = AsChatCommandParameter(b); return b }},
	}
	for _, tc := range cases {
		if len(tc.mk()) != tc.size {
			t.Errorf("%s: size mismatch", tc.name)
		}
	}
}

func TestWeatherStatusUpdateBitPacking(t *testing.T) {
	p := NewWeatherStatusUpdate()
	p.SetWeather(2)
	p.SetVariation(9)
	if p.d[3] != 0x29 {
		t.Fatalf("packed byte 0x%02X, want 0x29", p.d[3])
	}
	if p.Weather() != 2 || p.Variation() != 9 {
		t.Fatalf("bit fields read back mismatch: %d %d", p.Weather(), p.Variation())
	}
}

func TestChatMessageVariableSize(t *testing.T) {
	size := ChatMessageRequiredSize(2)
	if size != 16 {
		t.Fatalf("required size %d, want 16", size)
	}
	p := NewChatMessage(size)
	if p.Len() != 16 || p.d[0] != 0xC1 || p.d[1] != 16 || p.d[2] != 0x00 {
		t.Fatalf("variable header mismatch: len=%d c1=%02x lenb=%d code=%02x", p.Len(), p.d[0], p.d[1], p.d[2])
	}
}
