// Code generated by muprotogen from MUnique.OpenMU.Network.Packets 0.9.10; DO NOT EDIT.

package s2c

// StoredItem The structure for a stored item, e.g. in the inventory or vault.
type StoredItem struct{ d []byte }

func AsStoredItem(buf []byte) *StoredItem { return &StoredItem{d: buf} }
func (s *StoredItem) Bytes() []byte       { return s.d }
func (s *StoredItem) Len() int            { return len(s.d) }

func (s *StoredItem) ItemSlot() byte         { return s.d[0] }
func (s *StoredItem) SetItemSlot(value byte) { s.d[0] = byte(value) }

func (s *StoredItem) ItemData() []byte { return s.d[1:] }

// PlayerShopItem Data of an item in a player shop.
type PlayerShopItem struct{ d []byte }

const PlayerShopItemLength = 20

func AsPlayerShopItem(buf []byte) *PlayerShopItem { return &PlayerShopItem{d: buf} }
func (s *PlayerShopItem) Bytes() []byte           { return s.d }
func (s *PlayerShopItem) Len() int                { return len(s.d) }

func (s *PlayerShopItem) ItemSlot() byte         { return s.d[0] }
func (s *PlayerShopItem) SetItemSlot(value byte) { s.d[0] = byte(value) }

func (s *PlayerShopItem) ItemData() []byte { return s.d[1:13] }

func (s *PlayerShopItem) Price() uint32         { return getU32LE(s.d[16:]) }
func (s *PlayerShopItem) SetPrice(value uint32) { setU32LE(s.d[16:], value) }

// PlayerShopItemExtended Data of an item in a player shop, which allows for dynamic item sizes and trades for specific kind of items (e.g. jewels), too.
type PlayerShopItemExtended struct{ d []byte }

func AsPlayerShopItemExtended(buf []byte) *PlayerShopItemExtended {
	return &PlayerShopItemExtended{d: buf}
}
func (s *PlayerShopItemExtended) Bytes() []byte { return s.d }
func (s *PlayerShopItemExtended) Len() int      { return len(s.d) }

func (s *PlayerShopItemExtended) MoneyPrice() uint32         { return getU32LE(s.d[0:]) }
func (s *PlayerShopItemExtended) SetMoneyPrice(value uint32) { setU32LE(s.d[0:], value) }

func (s *PlayerShopItemExtended) PriceItemType() uint16         { return getU16LE(s.d[4:]) }
func (s *PlayerShopItemExtended) SetPriceItemType(value uint16) { setU16LE(s.d[4:], value) }

func (s *PlayerShopItemExtended) RequiredItemAmount() uint16         { return getU16LE(s.d[6:]) }
func (s *PlayerShopItemExtended) SetRequiredItemAmount(value uint16) { setU16LE(s.d[6:], value) }

func (s *PlayerShopItemExtended) ItemSlot() byte         { return s.d[8] }
func (s *PlayerShopItemExtended) SetItemSlot(value byte) { s.d[8] = byte(value) }

func (s *PlayerShopItemExtended) ItemData() []byte { return s.d[9:] }

// QuestIdentification Defines the information which identifies a quest.
type QuestIdentification struct{ d []byte }

const QuestIdentificationLength = 4

func AsQuestIdentification(buf []byte) *QuestIdentification { return &QuestIdentification{d: buf} }
func (s *QuestIdentification) Bytes() []byte                { return s.d }
func (s *QuestIdentification) Len() int                     { return len(s.d) }

func (s *QuestIdentification) Number() uint16         { return getU16LE(s.d[0:]) }
func (s *QuestIdentification) SetNumber(value uint16) { setU16LE(s.d[0:], value) }

func (s *QuestIdentification) Group() uint16         { return getU16LE(s.d[2:]) }
func (s *QuestIdentification) SetGroup(value uint16) { setU16LE(s.d[2:], value) }

// QuestCondition Defines a condition which must be fulfilled to complete the quest.
type QuestCondition struct{ d []byte }

const QuestConditionLength = 26

func AsQuestCondition(buf []byte) *QuestCondition { return &QuestCondition{d: buf} }
func (s *QuestCondition) Bytes() []byte           { return s.d }
func (s *QuestCondition) Len() int                { return len(s.d) }

func (s *QuestCondition) Type() ConditionType         { return ConditionType(s.d[0]) }
func (s *QuestCondition) SetType(value ConditionType) { s.d[0] = byte(value) }

func (s *QuestCondition) RequirementId() uint16         { return getU16LE(s.d[4:]) }
func (s *QuestCondition) SetRequirementId(value uint16) { setU16LE(s.d[4:], value) }

func (s *QuestCondition) RequiredCount() uint32         { return getU32LE(s.d[6:]) }
func (s *QuestCondition) SetRequiredCount(value uint32) { setU32LE(s.d[6:], value) }

func (s *QuestCondition) CurrentCount() uint32         { return getU32LE(s.d[10:]) }
func (s *QuestCondition) SetCurrentCount(value uint32) { setU32LE(s.d[10:], value) }

func (s *QuestCondition) RequiredItemData() []byte { return s.d[14:26] }

// QuestReward Defines a reward which is given when the quest is completed.
type QuestReward struct{ d []byte }

const QuestRewardLength = 22

func AsQuestReward(buf []byte) *QuestReward { return &QuestReward{d: buf} }
func (s *QuestReward) Bytes() []byte        { return s.d }
func (s *QuestReward) Len() int             { return len(s.d) }

func (s *QuestReward) Type() RewardType         { return RewardType(s.d[0]) }
func (s *QuestReward) SetType(value RewardType) { s.d[0] = byte(value) }

func (s *QuestReward) RewardId() uint16         { return getU16LE(s.d[4:]) }
func (s *QuestReward) SetRewardId(value uint16) { setU16LE(s.d[4:], value) }

func (s *QuestReward) RewardCount() uint32         { return getU32LE(s.d[6:]) }
func (s *QuestReward) SetRewardCount(value uint32) { setU32LE(s.d[6:], value) }

func (s *QuestReward) RewardedItemData() []byte { return s.d[10:22] }

// QuestConditionExtended Defines a condition which must be fulfilled to complete the quest.
type QuestConditionExtended struct{ d []byte }

const QuestConditionExtendedLength = 28

func AsQuestConditionExtended(buf []byte) *QuestConditionExtended {
	return &QuestConditionExtended{d: buf}
}
func (s *QuestConditionExtended) Bytes() []byte { return s.d }
func (s *QuestConditionExtended) Len() int      { return len(s.d) }

func (s *QuestConditionExtended) Type() ConditionType         { return ConditionType(s.d[0]) }
func (s *QuestConditionExtended) SetType(value ConditionType) { s.d[0] = byte(value) }

func (s *QuestConditionExtended) RequirementId() uint16         { return getU16LE(s.d[2:]) }
func (s *QuestConditionExtended) SetRequirementId(value uint16) { setU16LE(s.d[2:], value) }

func (s *QuestConditionExtended) RequiredCount() uint32         { return getU32LE(s.d[4:]) }
func (s *QuestConditionExtended) SetRequiredCount(value uint32) { setU32LE(s.d[4:], value) }

func (s *QuestConditionExtended) CurrentCount() uint32         { return getU32LE(s.d[8:]) }
func (s *QuestConditionExtended) SetCurrentCount(value uint32) { setU32LE(s.d[8:], value) }

func (s *QuestConditionExtended) RequiredItemData() []byte { return s.d[12:27] }

// QuestRewardExtended Defines a reward which is given when the quest is completed.
type QuestRewardExtended struct{ d []byte }

const QuestRewardExtendedLength = 24

func AsQuestRewardExtended(buf []byte) *QuestRewardExtended { return &QuestRewardExtended{d: buf} }
func (s *QuestRewardExtended) Bytes() []byte                { return s.d }
func (s *QuestRewardExtended) Len() int                     { return len(s.d) }

func (s *QuestRewardExtended) Type() RewardType         { return RewardType(s.d[0]) }
func (s *QuestRewardExtended) SetType(value RewardType) { s.d[0] = byte(value) }

func (s *QuestRewardExtended) RewardId() uint16         { return getU16LE(s.d[2:]) }
func (s *QuestRewardExtended) SetRewardId(value uint16) { setU16LE(s.d[2:], value) }

func (s *QuestRewardExtended) RewardCount() uint32         { return getU32LE(s.d[4:]) }
func (s *QuestRewardExtended) SetRewardCount(value uint32) { setU32LE(s.d[4:], value) }

func (s *QuestRewardExtended) RewardedItemData() []byte { return s.d[8:23] }

// CharacterData Contains the data of an NPC.
type CharacterData struct{ d []byte }

func AsCharacterData(buf []byte) *CharacterData { return &CharacterData{d: buf} }
func (s *CharacterData) Bytes() []byte          { return s.d }
func (s *CharacterData) Len() int               { return len(s.d) }

func (s *CharacterData) Id() uint16         { return getU16BE(s.d[0:]) }
func (s *CharacterData) SetId(value uint16) { setU16BE(s.d[0:], value) }

func (s *CharacterData) CurrentPositionX() byte         { return s.d[2] }
func (s *CharacterData) SetCurrentPositionX(value byte) { s.d[2] = byte(value) }

func (s *CharacterData) CurrentPositionY() byte         { return s.d[3] }
func (s *CharacterData) SetCurrentPositionY(value byte) { s.d[3] = byte(value) }

func (s *CharacterData) Appearance() []byte { return s.d[4:22] }

func (s *CharacterData) Name() []byte         { return cstring(s.d[22:32]) }
func (s *CharacterData) NameString() string   { return string(cstring(s.d[22:32])) }
func (s *CharacterData) SetName(value string) { writeCString(s.d[22:32], value) }

func (s *CharacterData) TargetPositionX() byte         { return s.d[32] }
func (s *CharacterData) SetTargetPositionX(value byte) { s.d[32] = byte(value) }

func (s *CharacterData) TargetPositionY() byte         { return s.d[33] }
func (s *CharacterData) SetTargetPositionY(value byte) { s.d[33] = byte(value) }

func (s *CharacterData) Rotation() byte         { return byte(byteBits(s.d[34], 4, 4)) }
func (s *CharacterData) SetRotation(value byte) { setByteBits(&s.d[34], byte(value), 4, 4) }

func (s *CharacterData) HeroState() CharacterHeroState {
	return CharacterHeroState(byteBits(s.d[34], 4, 0))
}
func (s *CharacterData) SetHeroState(value CharacterHeroState) {
	setByteBits(&s.d[34], byte(value), 4, 0)
}

func (s *CharacterData) EffectCount() byte         { return s.d[35] }
func (s *CharacterData) SetEffectCount(value byte) { s.d[35] = byte(value) }

func (s *CharacterData) EffectsCount() int { return int(s.EffectCount()) }
func (s *CharacterData) Effects(i int) *EffectId {
	count := int(s.EffectCount())
	start := 36 + i*EffectIdLength
	if i < 0 || i >= count || start+EffectIdLength > len(s.d) {
		return nil
	}
	return AsEffectId(s.d[start:])
}

// EffectId Contains the id of a magic effect.
type EffectId struct{ d []byte }

const EffectIdLength = 1

func AsEffectId(buf []byte) *EffectId { return &EffectId{d: buf} }
func (s *EffectId) Bytes() []byte     { return s.d }
func (s *EffectId) Len() int          { return len(s.d) }

func (s *EffectId) Id() byte         { return s.d[0] }
func (s *EffectId) SetId(value byte) { s.d[0] = byte(value) }

// CharacterData2 Contains the data of an NPC.
type CharacterData2 struct{ d []byte }

const CharacterData2Length = 27

func AsCharacterData2(buf []byte) *CharacterData2 { return &CharacterData2{d: buf} }
func (s *CharacterData2) Bytes() []byte           { return s.d }
func (s *CharacterData2) Len() int                { return len(s.d) }

func (s *CharacterData2) Id() uint16         { return getU16BE(s.d[0:]) }
func (s *CharacterData2) SetId(value uint16) { setU16BE(s.d[0:], value) }

func (s *CharacterData2) CurrentPositionX() byte         { return s.d[2] }
func (s *CharacterData2) SetCurrentPositionX(value byte) { s.d[2] = byte(value) }

func (s *CharacterData2) CurrentPositionY() byte         { return s.d[3] }
func (s *CharacterData2) SetCurrentPositionY(value byte) { s.d[3] = byte(value) }

func (s *CharacterData2) Appearance() []byte { return s.d[4:13] }

func (s *CharacterData2) IsPoisoned() bool { return s.d[13]&(1<<0) != 0 }
func (s *CharacterData2) SetIsPoisoned(value bool) {
	if value {
		s.d[13] |= 1 << 0
	} else {
		s.d[13] &^= 1 << 0
	}
}

func (s *CharacterData2) IsIced() bool { return s.d[13]&(1<<1) != 0 }
func (s *CharacterData2) SetIsIced(value bool) {
	if value {
		s.d[13] |= 1 << 1
	} else {
		s.d[13] &^= 1 << 1
	}
}

func (s *CharacterData2) IsDamageBuffed() bool { return s.d[13]&(1<<2) != 0 }
func (s *CharacterData2) SetIsDamageBuffed(value bool) {
	if value {
		s.d[13] |= 1 << 2
	} else {
		s.d[13] &^= 1 << 2
	}
}

func (s *CharacterData2) IsDefenseBuffed() bool { return s.d[13]&(1<<3) != 0 }
func (s *CharacterData2) SetIsDefenseBuffed(value bool) {
	if value {
		s.d[13] |= 1 << 3
	} else {
		s.d[13] &^= 1 << 3
	}
}

func (s *CharacterData2) Name() []byte         { return cstring(s.d[14:24]) }
func (s *CharacterData2) NameString() string   { return string(cstring(s.d[14:24])) }
func (s *CharacterData2) SetName(value string) { writeCString(s.d[14:24], value) }

func (s *CharacterData2) TargetPositionX() byte         { return s.d[24] }
func (s *CharacterData2) SetTargetPositionX(value byte) { s.d[24] = byte(value) }

func (s *CharacterData2) TargetPositionY() byte         { return s.d[25] }
func (s *CharacterData2) SetTargetPositionY(value byte) { s.d[25] = byte(value) }

func (s *CharacterData2) Rotation() byte         { return byte(byteBits(s.d[26], 4, 4)) }
func (s *CharacterData2) SetRotation(value byte) { setByteBits(&s.d[26], byte(value), 4, 4) }

func (s *CharacterData2) HeroState() CharacterHeroState {
	return CharacterHeroState(byteBits(s.d[26], 4, 0))
}
func (s *CharacterData2) SetHeroState(value CharacterHeroState) {
	setByteBits(&s.d[26], byte(value), 4, 0)
}

// CharacterData3 Contains the data of an NPC.
type CharacterData3 struct{ d []byte }

const CharacterData3Length = 31

func AsCharacterData3(buf []byte) *CharacterData3 { return &CharacterData3{d: buf} }
func (s *CharacterData3) Bytes() []byte           { return s.d }
func (s *CharacterData3) Len() int                { return len(s.d) }

func (s *CharacterData3) Id() uint16         { return getU16BE(s.d[0:]) }
func (s *CharacterData3) SetId(value uint16) { setU16BE(s.d[0:], value) }

func (s *CharacterData3) CurrentPositionX() byte         { return s.d[2] }
func (s *CharacterData3) SetCurrentPositionX(value byte) { s.d[2] = byte(value) }

func (s *CharacterData3) CurrentPositionY() byte         { return s.d[3] }
func (s *CharacterData3) SetCurrentPositionY(value byte) { s.d[3] = byte(value) }

func (s *CharacterData3) Appearance() []byte { return s.d[4:17] }

func (s *CharacterData3) IsPoisoned() bool { return s.d[17]&(1<<0) != 0 }
func (s *CharacterData3) SetIsPoisoned(value bool) {
	if value {
		s.d[17] |= 1 << 0
	} else {
		s.d[17] &^= 1 << 0
	}
}

func (s *CharacterData3) IsIced() bool { return s.d[17]&(1<<1) != 0 }
func (s *CharacterData3) SetIsIced(value bool) {
	if value {
		s.d[17] |= 1 << 1
	} else {
		s.d[17] &^= 1 << 1
	}
}

func (s *CharacterData3) IsDamageBuffed() bool { return s.d[17]&(1<<2) != 0 }
func (s *CharacterData3) SetIsDamageBuffed(value bool) {
	if value {
		s.d[17] |= 1 << 2
	} else {
		s.d[17] &^= 1 << 2
	}
}

func (s *CharacterData3) IsDefenseBuffed() bool { return s.d[17]&(1<<3) != 0 }
func (s *CharacterData3) SetIsDefenseBuffed(value bool) {
	if value {
		s.d[17] |= 1 << 3
	} else {
		s.d[17] &^= 1 << 3
	}
}

func (s *CharacterData3) Name() []byte         { return cstring(s.d[18:28]) }
func (s *CharacterData3) NameString() string   { return string(cstring(s.d[18:28])) }
func (s *CharacterData3) SetName(value string) { writeCString(s.d[18:28], value) }

func (s *CharacterData3) TargetPositionX() byte         { return s.d[28] }
func (s *CharacterData3) SetTargetPositionX(value byte) { s.d[28] = byte(value) }

func (s *CharacterData3) TargetPositionY() byte         { return s.d[29] }
func (s *CharacterData3) SetTargetPositionY(value byte) { s.d[29] = byte(value) }

func (s *CharacterData3) Rotation() byte         { return byte(byteBits(s.d[30], 4, 4)) }
func (s *CharacterData3) SetRotation(value byte) { setByteBits(&s.d[30], byte(value), 4, 4) }

func (s *CharacterData3) HeroState() CharacterHeroState {
	return CharacterHeroState(byteBits(s.d[30], 4, 0))
}
func (s *CharacterData3) SetHeroState(value CharacterHeroState) {
	setByteBits(&s.d[30], byte(value), 4, 0)
}

// NpcData Contains the data of an NPC.
type NpcData struct{ d []byte }

const NpcDataLength = 10

func AsNpcData(buf []byte) *NpcData { return &NpcData{d: buf} }
func (s *NpcData) Bytes() []byte    { return s.d }
func (s *NpcData) Len() int         { return len(s.d) }

func (s *NpcData) Id() uint16         { return getU16BE(s.d[0:]) }
func (s *NpcData) SetId(value uint16) { setU16BE(s.d[0:], value) }

func (s *NpcData) TypeNumber() uint16         { return getU16BE(s.d[2:]) }
func (s *NpcData) SetTypeNumber(value uint16) { setU16BE(s.d[2:], value) }

func (s *NpcData) CurrentPositionX() byte         { return s.d[4] }
func (s *NpcData) SetCurrentPositionX(value byte) { s.d[4] = byte(value) }

func (s *NpcData) CurrentPositionY() byte         { return s.d[5] }
func (s *NpcData) SetCurrentPositionY(value byte) { s.d[5] = byte(value) }

func (s *NpcData) TargetPositionX() byte         { return s.d[6] }
func (s *NpcData) SetTargetPositionX(value byte) { s.d[6] = byte(value) }

func (s *NpcData) TargetPositionY() byte         { return s.d[7] }
func (s *NpcData) SetTargetPositionY(value byte) { s.d[7] = byte(value) }

func (s *NpcData) Rotation() byte         { return byte(byteBits(s.d[8], 4, 4)) }
func (s *NpcData) SetRotation(value byte) { setByteBits(&s.d[8], byte(value), 4, 4) }

func (s *NpcData) EffectCount() byte         { return s.d[9] }
func (s *NpcData) SetEffectCount(value byte) { s.d[9] = byte(value) }

// NpcData2 Contains the data of an NPC.
type NpcData2 struct{ d []byte }

const NpcData2Length = 9

func AsNpcData2(buf []byte) *NpcData2 { return &NpcData2{d: buf} }
func (s *NpcData2) Bytes() []byte     { return s.d }
func (s *NpcData2) Len() int          { return len(s.d) }

func (s *NpcData2) Id() uint16         { return getU16BE(s.d[0:]) }
func (s *NpcData2) SetId(value uint16) { setU16BE(s.d[0:], value) }

func (s *NpcData2) TypeNumber() byte         { return s.d[2] }
func (s *NpcData2) SetTypeNumber(value byte) { s.d[2] = byte(value) }

func (s *NpcData2) IsPoisoned() bool { return s.d[3]&(1<<0) != 0 }
func (s *NpcData2) SetIsPoisoned(value bool) {
	if value {
		s.d[3] |= 1 << 0
	} else {
		s.d[3] &^= 1 << 0
	}
}

func (s *NpcData2) IsIced() bool { return s.d[3]&(1<<1) != 0 }
func (s *NpcData2) SetIsIced(value bool) {
	if value {
		s.d[3] |= 1 << 1
	} else {
		s.d[3] &^= 1 << 1
	}
}

func (s *NpcData2) IsDamageBuffed() bool { return s.d[3]&(1<<2) != 0 }
func (s *NpcData2) SetIsDamageBuffed(value bool) {
	if value {
		s.d[3] |= 1 << 2
	} else {
		s.d[3] &^= 1 << 2
	}
}

func (s *NpcData2) IsDefenseBuffed() bool { return s.d[3]&(1<<3) != 0 }
func (s *NpcData2) SetIsDefenseBuffed(value bool) {
	if value {
		s.d[3] |= 1 << 3
	} else {
		s.d[3] &^= 1 << 3
	}
}

func (s *NpcData2) CurrentPositionX() byte         { return s.d[4] }
func (s *NpcData2) SetCurrentPositionX(value byte) { s.d[4] = byte(value) }

func (s *NpcData2) CurrentPositionY() byte         { return s.d[5] }
func (s *NpcData2) SetCurrentPositionY(value byte) { s.d[5] = byte(value) }

func (s *NpcData2) TargetPositionX() byte         { return s.d[6] }
func (s *NpcData2) SetTargetPositionX(value byte) { s.d[6] = byte(value) }

func (s *NpcData2) TargetPositionY() byte         { return s.d[7] }
func (s *NpcData2) SetTargetPositionY(value byte) { s.d[7] = byte(value) }

func (s *NpcData2) Rotation() byte         { return byte(byteBits(s.d[8], 4, 4)) }
func (s *NpcData2) SetRotation(value byte) { setByteBits(&s.d[8], byte(value), 4, 4) }

// NpcData3 Contains the data of an NPC.
type NpcData3 struct{ d []byte }

const NpcData3Length = 12

func AsNpcData3(buf []byte) *NpcData3 { return &NpcData3{d: buf} }
func (s *NpcData3) Bytes() []byte     { return s.d }
func (s *NpcData3) Len() int          { return len(s.d) }

func (s *NpcData3) Id() uint16         { return getU16BE(s.d[0:]) }
func (s *NpcData3) SetId(value uint16) { setU16BE(s.d[0:], value) }

func (s *NpcData3) TypeNumber() byte         { return s.d[2] }
func (s *NpcData3) SetTypeNumber(value byte) { s.d[2] = byte(value) }

func (s *NpcData3) IsPoisoned() bool { return s.d[4]&(1<<0) != 0 }
func (s *NpcData3) SetIsPoisoned(value bool) {
	if value {
		s.d[4] |= 1 << 0
	} else {
		s.d[4] &^= 1 << 0
	}
}

func (s *NpcData3) IsIced() bool { return s.d[4]&(1<<1) != 0 }
func (s *NpcData3) SetIsIced(value bool) {
	if value {
		s.d[4] |= 1 << 1
	} else {
		s.d[4] &^= 1 << 1
	}
}

func (s *NpcData3) IsDamageBuffed() bool { return s.d[4]&(1<<2) != 0 }
func (s *NpcData3) SetIsDamageBuffed(value bool) {
	if value {
		s.d[4] |= 1 << 2
	} else {
		s.d[4] &^= 1 << 2
	}
}

func (s *NpcData3) IsDefenseBuffed() bool { return s.d[4]&(1<<3) != 0 }
func (s *NpcData3) SetIsDefenseBuffed(value bool) {
	if value {
		s.d[4] |= 1 << 3
	} else {
		s.d[4] &^= 1 << 3
	}
}

func (s *NpcData3) CurrentPositionX() byte         { return s.d[6] }
func (s *NpcData3) SetCurrentPositionX(value byte) { s.d[6] = byte(value) }

func (s *NpcData3) CurrentPositionY() byte         { return s.d[7] }
func (s *NpcData3) SetCurrentPositionY(value byte) { s.d[7] = byte(value) }

func (s *NpcData3) TargetPositionX() byte         { return s.d[8] }
func (s *NpcData3) SetTargetPositionX(value byte) { s.d[8] = byte(value) }

func (s *NpcData3) TargetPositionY() byte         { return s.d[9] }
func (s *NpcData3) SetTargetPositionY(value byte) { s.d[9] = byte(value) }

func (s *NpcData3) Rotation() byte         { return byte(byteBits(s.d[10], 4, 4)) }
func (s *NpcData3) SetRotation(value byte) { setByteBits(&s.d[10], byte(value), 4, 4) }

// SummonedMonsterData Contains the data of an NPC.
type SummonedMonsterData struct{ d []byte }

func AsSummonedMonsterData(buf []byte) *SummonedMonsterData { return &SummonedMonsterData{d: buf} }
func (s *SummonedMonsterData) Bytes() []byte                { return s.d }
func (s *SummonedMonsterData) Len() int                     { return len(s.d) }

func (s *SummonedMonsterData) Id() uint16         { return getU16BE(s.d[0:]) }
func (s *SummonedMonsterData) SetId(value uint16) { setU16BE(s.d[0:], value) }

func (s *SummonedMonsterData) TypeNumber() uint16         { return getU16BE(s.d[2:]) }
func (s *SummonedMonsterData) SetTypeNumber(value uint16) { setU16BE(s.d[2:], value) }

func (s *SummonedMonsterData) CurrentPositionX() byte         { return s.d[4] }
func (s *SummonedMonsterData) SetCurrentPositionX(value byte) { s.d[4] = byte(value) }

func (s *SummonedMonsterData) CurrentPositionY() byte         { return s.d[5] }
func (s *SummonedMonsterData) SetCurrentPositionY(value byte) { s.d[5] = byte(value) }

func (s *SummonedMonsterData) TargetPositionX() byte         { return s.d[6] }
func (s *SummonedMonsterData) SetTargetPositionX(value byte) { s.d[6] = byte(value) }

func (s *SummonedMonsterData) TargetPositionY() byte         { return s.d[7] }
func (s *SummonedMonsterData) SetTargetPositionY(value byte) { s.d[7] = byte(value) }

func (s *SummonedMonsterData) Rotation() byte         { return byte(byteBits(s.d[8], 4, 4)) }
func (s *SummonedMonsterData) SetRotation(value byte) { setByteBits(&s.d[8], byte(value), 4, 4) }

func (s *SummonedMonsterData) OwnerCharacterName() []byte         { return cstring(s.d[9:19]) }
func (s *SummonedMonsterData) OwnerCharacterNameString() string   { return string(cstring(s.d[9:19])) }
func (s *SummonedMonsterData) SetOwnerCharacterName(value string) { writeCString(s.d[9:19], value) }

func (s *SummonedMonsterData) EffectCount() byte         { return s.d[19] }
func (s *SummonedMonsterData) SetEffectCount(value byte) { s.d[19] = byte(value) }

func (s *SummonedMonsterData) EffectsCount() int { return int(s.EffectCount()) }
func (s *SummonedMonsterData) Effects(i int) *EffectId2 {
	count := int(s.EffectCount())
	start := 20 + i*EffectId2Length
	if i < 0 || i >= count || start+EffectId2Length > len(s.d) {
		return nil
	}
	return AsEffectId2(s.d[start:])
}

// EffectId2 Contains the id of a magic effect.
type EffectId2 struct{ d []byte }

const EffectId2Length = 1

func AsEffectId2(buf []byte) *EffectId2 { return &EffectId2{d: buf} }
func (s *EffectId2) Bytes() []byte      { return s.d }
func (s *EffectId2) Len() int           { return len(s.d) }

func (s *EffectId2) Id() byte         { return s.d[0] }
func (s *EffectId2) SetId(value byte) { s.d[0] = byte(value) }

// SummonedMonsterData2 Contains the data of an NPC.
type SummonedMonsterData2 struct{ d []byte }

const SummonedMonsterData2Length = 19

func AsSummonedMonsterData2(buf []byte) *SummonedMonsterData2 { return &SummonedMonsterData2{d: buf} }
func (s *SummonedMonsterData2) Bytes() []byte                 { return s.d }
func (s *SummonedMonsterData2) Len() int                      { return len(s.d) }

func (s *SummonedMonsterData2) Id() uint16         { return getU16BE(s.d[0:]) }
func (s *SummonedMonsterData2) SetId(value uint16) { setU16BE(s.d[0:], value) }

func (s *SummonedMonsterData2) TypeNumber() byte         { return s.d[2] }
func (s *SummonedMonsterData2) SetTypeNumber(value byte) { s.d[2] = byte(value) }

func (s *SummonedMonsterData2) IsPoisoned() bool { return s.d[3]&(1<<0) != 0 }
func (s *SummonedMonsterData2) SetIsPoisoned(value bool) {
	if value {
		s.d[3] |= 1 << 0
	} else {
		s.d[3] &^= 1 << 0
	}
}

func (s *SummonedMonsterData2) IsIced() bool { return s.d[3]&(1<<1) != 0 }
func (s *SummonedMonsterData2) SetIsIced(value bool) {
	if value {
		s.d[3] |= 1 << 1
	} else {
		s.d[3] &^= 1 << 1
	}
}

func (s *SummonedMonsterData2) IsDamageBuffed() bool { return s.d[3]&(1<<2) != 0 }
func (s *SummonedMonsterData2) SetIsDamageBuffed(value bool) {
	if value {
		s.d[3] |= 1 << 2
	} else {
		s.d[3] &^= 1 << 2
	}
}

func (s *SummonedMonsterData2) IsDefenseBuffed() bool { return s.d[3]&(1<<3) != 0 }
func (s *SummonedMonsterData2) SetIsDefenseBuffed(value bool) {
	if value {
		s.d[3] |= 1 << 3
	} else {
		s.d[3] &^= 1 << 3
	}
}

func (s *SummonedMonsterData2) CurrentPositionX() byte         { return s.d[4] }
func (s *SummonedMonsterData2) SetCurrentPositionX(value byte) { s.d[4] = byte(value) }

func (s *SummonedMonsterData2) CurrentPositionY() byte         { return s.d[5] }
func (s *SummonedMonsterData2) SetCurrentPositionY(value byte) { s.d[5] = byte(value) }

func (s *SummonedMonsterData2) TargetPositionX() byte         { return s.d[6] }
func (s *SummonedMonsterData2) SetTargetPositionX(value byte) { s.d[6] = byte(value) }

func (s *SummonedMonsterData2) TargetPositionY() byte         { return s.d[7] }
func (s *SummonedMonsterData2) SetTargetPositionY(value byte) { s.d[7] = byte(value) }

func (s *SummonedMonsterData2) Rotation() byte         { return byte(byteBits(s.d[8], 4, 4)) }
func (s *SummonedMonsterData2) SetRotation(value byte) { setByteBits(&s.d[8], byte(value), 4, 4) }

func (s *SummonedMonsterData2) OwnerCharacterName() []byte         { return cstring(s.d[9:19]) }
func (s *SummonedMonsterData2) OwnerCharacterNameString() string   { return string(cstring(s.d[9:19])) }
func (s *SummonedMonsterData2) SetOwnerCharacterName(value string) { writeCString(s.d[9:19], value) }

// SummonedMonsterData3 Contains the data of an NPC.
type SummonedMonsterData3 struct{ d []byte }

const SummonedMonsterData3Length = 20

func AsSummonedMonsterData3(buf []byte) *SummonedMonsterData3 { return &SummonedMonsterData3{d: buf} }
func (s *SummonedMonsterData3) Bytes() []byte                 { return s.d }
func (s *SummonedMonsterData3) Len() int                      { return len(s.d) }

func (s *SummonedMonsterData3) Id() uint16         { return getU16BE(s.d[0:]) }
func (s *SummonedMonsterData3) SetId(value uint16) { setU16BE(s.d[0:], value) }

func (s *SummonedMonsterData3) TypeNumber() byte         { return s.d[2] }
func (s *SummonedMonsterData3) SetTypeNumber(value byte) { s.d[2] = byte(value) }

func (s *SummonedMonsterData3) IsPoisoned() bool { return s.d[4]&(1<<0) != 0 }
func (s *SummonedMonsterData3) SetIsPoisoned(value bool) {
	if value {
		s.d[4] |= 1 << 0
	} else {
		s.d[4] &^= 1 << 0
	}
}

func (s *SummonedMonsterData3) IsIced() bool { return s.d[4]&(1<<1) != 0 }
func (s *SummonedMonsterData3) SetIsIced(value bool) {
	if value {
		s.d[4] |= 1 << 1
	} else {
		s.d[4] &^= 1 << 1
	}
}

func (s *SummonedMonsterData3) IsDamageBuffed() bool { return s.d[4]&(1<<2) != 0 }
func (s *SummonedMonsterData3) SetIsDamageBuffed(value bool) {
	if value {
		s.d[4] |= 1 << 2
	} else {
		s.d[4] &^= 1 << 2
	}
}

func (s *SummonedMonsterData3) IsDefenseBuffed() bool { return s.d[4]&(1<<3) != 0 }
func (s *SummonedMonsterData3) SetIsDefenseBuffed(value bool) {
	if value {
		s.d[4] |= 1 << 3
	} else {
		s.d[4] &^= 1 << 3
	}
}

func (s *SummonedMonsterData3) CurrentPositionX() byte         { return s.d[5] }
func (s *SummonedMonsterData3) SetCurrentPositionX(value byte) { s.d[5] = byte(value) }

func (s *SummonedMonsterData3) CurrentPositionY() byte         { return s.d[6] }
func (s *SummonedMonsterData3) SetCurrentPositionY(value byte) { s.d[6] = byte(value) }

func (s *SummonedMonsterData3) TargetPositionX() byte         { return s.d[7] }
func (s *SummonedMonsterData3) SetTargetPositionX(value byte) { s.d[7] = byte(value) }

func (s *SummonedMonsterData3) TargetPositionY() byte         { return s.d[8] }
func (s *SummonedMonsterData3) SetTargetPositionY(value byte) { s.d[8] = byte(value) }

func (s *SummonedMonsterData3) Rotation() byte         { return byte(byteBits(s.d[9], 4, 4)) }
func (s *SummonedMonsterData3) SetRotation(value byte) { setByteBits(&s.d[9], byte(value), 4, 4) }

func (s *SummonedMonsterData3) OwnerCharacterName() []byte         { return cstring(s.d[10:20]) }
func (s *SummonedMonsterData3) OwnerCharacterNameString() string   { return string(cstring(s.d[10:20])) }
func (s *SummonedMonsterData3) SetOwnerCharacterName(value string) { writeCString(s.d[10:20], value) }

// ObjectId Contains the id of a object.
type ObjectId struct{ d []byte }

const ObjectIdLength = 2

func AsObjectId(buf []byte) *ObjectId { return &ObjectId{d: buf} }
func (s *ObjectId) Bytes() []byte     { return s.d }
func (s *ObjectId) Len() int          { return len(s.d) }

func (s *ObjectId) Id() uint16         { return getU16BE(s.d[0:]) }
func (s *ObjectId) SetId(value uint16) { setU16BE(s.d[0:], value) }

// RageTarget Contains the target identifier.
type RageTarget struct{ d []byte }

const RageTargetLength = 2

func AsRageTarget(buf []byte) *RageTarget { return &RageTarget{d: buf} }
func (s *RageTarget) Bytes() []byte       { return s.d }
func (s *RageTarget) Len() int            { return len(s.d) }

func (s *RageTarget) TargetId() uint16         { return getU16LE(s.d[0:]) }
func (s *RageTarget) SetTargetId(value uint16) { setU16LE(s.d[0:], value) }

// PartyMember Data about a party member.
type PartyMember struct{ d []byte }

const PartyMemberLength = 24

func AsPartyMember(buf []byte) *PartyMember { return &PartyMember{d: buf} }
func (s *PartyMember) Bytes() []byte        { return s.d }
func (s *PartyMember) Len() int             { return len(s.d) }

func (s *PartyMember) Name() []byte         { return cstring(s.d[0:10]) }
func (s *PartyMember) NameString() string   { return string(cstring(s.d[0:10])) }
func (s *PartyMember) SetName(value string) { writeCString(s.d[0:10], value) }

func (s *PartyMember) Index() byte         { return s.d[10] }
func (s *PartyMember) SetIndex(value byte) { s.d[10] = byte(value) }

func (s *PartyMember) MapId() byte         { return s.d[11] }
func (s *PartyMember) SetMapId(value byte) { s.d[11] = byte(value) }

func (s *PartyMember) PositionX() byte         { return s.d[12] }
func (s *PartyMember) SetPositionX(value byte) { s.d[12] = byte(value) }

func (s *PartyMember) PositionY() byte         { return s.d[13] }
func (s *PartyMember) SetPositionY(value byte) { s.d[13] = byte(value) }

func (s *PartyMember) CurrentHealth() uint32         { return getU32LE(s.d[16:]) }
func (s *PartyMember) SetCurrentHealth(value uint32) { setU32LE(s.d[16:], value) }

func (s *PartyMember) MaximumHealth() uint32         { return getU32LE(s.d[20:]) }
func (s *PartyMember) SetMaximumHealth(value uint32) { setU32LE(s.d[20:], value) }

// PartyMember2 Data about a party member.
type PartyMember2 struct{ d []byte }

const PartyMember2Length = 14

func AsPartyMember2(buf []byte) *PartyMember2 { return &PartyMember2{d: buf} }
func (s *PartyMember2) Bytes() []byte         { return s.d }
func (s *PartyMember2) Len() int              { return len(s.d) }

func (s *PartyMember2) Name() []byte         { return cstring(s.d[0:10]) }
func (s *PartyMember2) NameString() string   { return string(cstring(s.d[0:10])) }
func (s *PartyMember2) SetName(value string) { writeCString(s.d[0:10], value) }

func (s *PartyMember2) Index() byte         { return s.d[10] }
func (s *PartyMember2) SetIndex(value byte) { s.d[10] = byte(value) }

func (s *PartyMember2) MapId() byte         { return s.d[11] }
func (s *PartyMember2) SetMapId(value byte) { s.d[11] = byte(value) }

func (s *PartyMember2) PositionX() byte         { return s.d[12] }
func (s *PartyMember2) SetPositionX(value byte) { s.d[12] = byte(value) }

func (s *PartyMember2) PositionY() byte         { return s.d[13] }
func (s *PartyMember2) SetPositionY(value byte) { s.d[13] = byte(value) }

// PartyMemberHealth Health of a party member
type PartyMemberHealth struct{ d []byte }

const PartyMemberHealthLength = 1

func AsPartyMemberHealth(buf []byte) *PartyMemberHealth { return &PartyMemberHealth{d: buf} }
func (s *PartyMemberHealth) Bytes() []byte              { return s.d }
func (s *PartyMemberHealth) Len() int                   { return len(s.d) }

func (s *PartyMemberHealth) Index() byte         { return byte(byteBits(s.d[0], 4, 4)) }
func (s *PartyMemberHealth) SetIndex(value byte) { setByteBits(&s.d[0], byte(value), 4, 4) }

func (s *PartyMemberHealth) Value() byte         { return byte(byteBits(s.d[0], 4, 0)) }
func (s *PartyMemberHealth) SetValue(value byte) { setByteBits(&s.d[0], byte(value), 4, 0) }

// DroppedItem Contains the data about a dropped item.
type DroppedItem struct{ d []byte }

func AsDroppedItem(buf []byte) *DroppedItem { return &DroppedItem{d: buf} }
func (s *DroppedItem) Bytes() []byte        { return s.d }
func (s *DroppedItem) Len() int             { return len(s.d) }

func (s *DroppedItem) Id() uint16         { return getU16BE(s.d[0:]) }
func (s *DroppedItem) SetId(value uint16) { setU16BE(s.d[0:], value) }

func (s *DroppedItem) IsFreshDrop() bool { return s.d[0]&(1<<7) != 0 }
func (s *DroppedItem) SetIsFreshDrop(value bool) {
	if value {
		s.d[0] |= 1 << 7
	} else {
		s.d[0] &^= 1 << 7
	}
}

func (s *DroppedItem) PositionX() byte         { return s.d[2] }
func (s *DroppedItem) SetPositionX(value byte) { s.d[2] = byte(value) }

func (s *DroppedItem) PositionY() byte         { return s.d[3] }
func (s *DroppedItem) SetPositionY(value byte) { s.d[3] = byte(value) }

func (s *DroppedItem) ItemData() []byte { return s.d[4:] }

// DroppedItemId Contains the id of a dropped item.
type DroppedItemId struct{ d []byte }

const DroppedItemIdLength = 2

func AsDroppedItemId(buf []byte) *DroppedItemId { return &DroppedItemId{d: buf} }
func (s *DroppedItemId) Bytes() []byte          { return s.d }
func (s *DroppedItemId) Len() int               { return len(s.d) }

func (s *DroppedItemId) Id() uint16         { return getU16BE(s.d[0:]) }
func (s *DroppedItemId) SetId(value uint16) { setU16BE(s.d[0:], value) }

// PlayerShop Data of the shop of a player.
type PlayerShop struct{ d []byte }

const PlayerShopLength = 38

func AsPlayerShop(buf []byte) *PlayerShop { return &PlayerShop{d: buf} }
func (s *PlayerShop) Bytes() []byte       { return s.d }
func (s *PlayerShop) Len() int            { return len(s.d) }

func (s *PlayerShop) PlayerId() uint16         { return getU16BE(s.d[0:]) }
func (s *PlayerShop) SetPlayerId(value uint16) { setU16BE(s.d[0:], value) }

func (s *PlayerShop) StoreName() []byte         { return cstring(s.d[2:38]) }
func (s *PlayerShop) StoreNameString() string   { return string(cstring(s.d[2:38])) }
func (s *PlayerShop) SetStoreName(value string) { writeCString(s.d[2:38], value) }

// CharacterData4 Contains the data of an transformed character.
type CharacterData4 struct{ d []byte }

const CharacterData4Length = 19

func AsCharacterData4(buf []byte) *CharacterData4 { return &CharacterData4{d: buf} }
func (s *CharacterData4) Bytes() []byte           { return s.d }
func (s *CharacterData4) Len() int                { return len(s.d) }

func (s *CharacterData4) Id() uint16         { return getU16BE(s.d[0:]) }
func (s *CharacterData4) SetId(value uint16) { setU16BE(s.d[0:], value) }

func (s *CharacterData4) CurrentPositionX() byte         { return s.d[2] }
func (s *CharacterData4) SetCurrentPositionX(value byte) { s.d[2] = byte(value) }

func (s *CharacterData4) CurrentPositionY() byte         { return s.d[3] }
func (s *CharacterData4) SetCurrentPositionY(value byte) { s.d[3] = byte(value) }

func (s *CharacterData4) Skin() byte         { return s.d[4] }
func (s *CharacterData4) SetSkin(value byte) { s.d[4] = byte(value) }

func (s *CharacterData4) IsPoisoned() bool { return s.d[5]&(1<<0) != 0 }
func (s *CharacterData4) SetIsPoisoned(value bool) {
	if value {
		s.d[5] |= 1 << 0
	} else {
		s.d[5] &^= 1 << 0
	}
}

func (s *CharacterData4) IsIced() bool { return s.d[5]&(1<<1) != 0 }
func (s *CharacterData4) SetIsIced(value bool) {
	if value {
		s.d[5] |= 1 << 1
	} else {
		s.d[5] &^= 1 << 1
	}
}

func (s *CharacterData4) IsDamageBuffed() bool { return s.d[5]&(1<<2) != 0 }
func (s *CharacterData4) SetIsDamageBuffed(value bool) {
	if value {
		s.d[5] |= 1 << 2
	} else {
		s.d[5] &^= 1 << 2
	}
}

func (s *CharacterData4) IsDefenseBuffed() bool { return s.d[5]&(1<<3) != 0 }
func (s *CharacterData4) SetIsDefenseBuffed(value bool) {
	if value {
		s.d[5] |= 1 << 3
	} else {
		s.d[5] &^= 1 << 3
	}
}

func (s *CharacterData4) Name() []byte         { return cstring(s.d[6:16]) }
func (s *CharacterData4) NameString() string   { return string(cstring(s.d[6:16])) }
func (s *CharacterData4) SetName(value string) { writeCString(s.d[6:16], value) }

func (s *CharacterData4) TargetPositionX() byte         { return s.d[16] }
func (s *CharacterData4) SetTargetPositionX(value byte) { s.d[16] = byte(value) }

func (s *CharacterData4) TargetPositionY() byte         { return s.d[17] }
func (s *CharacterData4) SetTargetPositionY(value byte) { s.d[17] = byte(value) }

func (s *CharacterData4) Rotation() byte         { return byte(byteBits(s.d[18], 4, 4)) }
func (s *CharacterData4) SetRotation(value byte) { setByteBits(&s.d[18], byte(value), 4, 4) }

func (s *CharacterData4) HeroState() CharacterHeroState {
	return CharacterHeroState(byteBits(s.d[18], 4, 0))
}
func (s *CharacterData4) SetHeroState(value CharacterHeroState) {
	setByteBits(&s.d[18], byte(value), 4, 0)
}

// CharacterData5 Contains the data of an transformed character.
type CharacterData5 struct{ d []byte }

func AsCharacterData5(buf []byte) *CharacterData5 { return &CharacterData5{d: buf} }
func (s *CharacterData5) Bytes() []byte           { return s.d }
func (s *CharacterData5) Len() int                { return len(s.d) }

func (s *CharacterData5) Id() uint16         { return getU16BE(s.d[0:]) }
func (s *CharacterData5) SetId(value uint16) { setU16BE(s.d[0:], value) }

func (s *CharacterData5) CurrentPositionX() byte         { return s.d[2] }
func (s *CharacterData5) SetCurrentPositionX(value byte) { s.d[2] = byte(value) }

func (s *CharacterData5) CurrentPositionY() byte         { return s.d[3] }
func (s *CharacterData5) SetCurrentPositionY(value byte) { s.d[3] = byte(value) }

func (s *CharacterData5) Skin() uint16         { return getU16BE(s.d[4:]) }
func (s *CharacterData5) SetSkin(value uint16) { setU16BE(s.d[4:], value) }

func (s *CharacterData5) Name() []byte         { return cstring(s.d[6:16]) }
func (s *CharacterData5) NameString() string   { return string(cstring(s.d[6:16])) }
func (s *CharacterData5) SetName(value string) { writeCString(s.d[6:16], value) }

func (s *CharacterData5) TargetPositionX() byte         { return s.d[16] }
func (s *CharacterData5) SetTargetPositionX(value byte) { s.d[16] = byte(value) }

func (s *CharacterData5) TargetPositionY() byte         { return s.d[17] }
func (s *CharacterData5) SetTargetPositionY(value byte) { s.d[17] = byte(value) }

func (s *CharacterData5) Rotation() byte         { return byte(byteBits(s.d[18], 4, 4)) }
func (s *CharacterData5) SetRotation(value byte) { setByteBits(&s.d[18], byte(value), 4, 4) }

func (s *CharacterData5) HeroState() CharacterHeroState {
	return CharacterHeroState(byteBits(s.d[18], 4, 0))
}
func (s *CharacterData5) SetHeroState(value CharacterHeroState) {
	setByteBits(&s.d[18], byte(value), 4, 0)
}

func (s *CharacterData5) Appearance() []byte { return s.d[19:37] }

func (s *CharacterData5) EffectCount() byte         { return s.d[37] }
func (s *CharacterData5) SetEffectCount(value byte) { s.d[37] = byte(value) }

func (s *CharacterData5) EffectsCount() int { return int(s.EffectCount()) }
func (s *CharacterData5) Effects(i int) *EffectId3 {
	count := int(s.EffectCount())
	start := 38 + i*EffectId3Length
	if i < 0 || i >= count || start+EffectId3Length > len(s.d) {
		return nil
	}
	return AsEffectId3(s.d[start:])
}

// EffectId3 Contains the id of a magic effect.
type EffectId3 struct{ d []byte }

const EffectId3Length = 1

func AsEffectId3(buf []byte) *EffectId3 { return &EffectId3{d: buf} }
func (s *EffectId3) Bytes() []byte      { return s.d }
func (s *EffectId3) Len() int           { return len(s.d) }

func (s *EffectId3) Id() byte         { return s.d[0] }
func (s *EffectId3) SetId(value byte) { s.d[0] = byte(value) }

// TerrainArea Defines the area which should be changed.
type TerrainArea struct{ d []byte }

const TerrainAreaLength = 4

func AsTerrainArea(buf []byte) *TerrainArea { return &TerrainArea{d: buf} }
func (s *TerrainArea) Bytes() []byte        { return s.d }
func (s *TerrainArea) Len() int             { return len(s.d) }

func (s *TerrainArea) StartX() byte         { return s.d[0] }
func (s *TerrainArea) SetStartX(value byte) { s.d[0] = byte(value) }

func (s *TerrainArea) StartY() byte         { return s.d[1] }
func (s *TerrainArea) SetStartY(value byte) { s.d[1] = byte(value) }

func (s *TerrainArea) EndX() byte         { return s.d[2] }
func (s *TerrainArea) SetEndX(value byte) { s.d[2] = byte(value) }

func (s *TerrainArea) EndY() byte         { return s.d[3] }
func (s *TerrainArea) SetEndY(value byte) { s.d[3] = byte(value) }

// CharacterData6 Data of one character in the list.
type CharacterData6 struct{ d []byte }

const CharacterData6Length = 34

func AsCharacterData6(buf []byte) *CharacterData6 { return &CharacterData6{d: buf} }
func (s *CharacterData6) Bytes() []byte           { return s.d }
func (s *CharacterData6) Len() int                { return len(s.d) }

func (s *CharacterData6) SlotIndex() byte         { return s.d[0] }
func (s *CharacterData6) SetSlotIndex(value byte) { s.d[0] = byte(value) }

func (s *CharacterData6) Name() []byte         { return cstring(s.d[1:11]) }
func (s *CharacterData6) NameString() string   { return string(cstring(s.d[1:11])) }
func (s *CharacterData6) SetName(value string) { writeCString(s.d[1:11], value) }

func (s *CharacterData6) Level() uint16         { return getU16LE(s.d[12:]) }
func (s *CharacterData6) SetLevel(value uint16) { setU16LE(s.d[12:], value) }

func (s *CharacterData6) Status() CharacterStatus         { return CharacterStatus(byteBits(s.d[14], 4, 0)) }
func (s *CharacterData6) SetStatus(value CharacterStatus) { setByteBits(&s.d[14], byte(value), 4, 0) }

func (s *CharacterData6) IsItemBlockActive() bool { return s.d[14]&(1<<4) != 0 }
func (s *CharacterData6) SetIsItemBlockActive(value bool) {
	if value {
		s.d[14] |= 1 << 4
	} else {
		s.d[14] &^= 1 << 4
	}
}

func (s *CharacterData6) Appearance() []byte { return s.d[15:33] }

func (s *CharacterData6) GuildPosition() GuildMemberRole         { return GuildMemberRole(s.d[33]) }
func (s *CharacterData6) SetGuildPosition(value GuildMemberRole) { s.d[33] = byte(value) }

// CharacterData7 Data of one character in the list.
type CharacterData7 struct{ d []byte }

const CharacterData7Length = 44

func AsCharacterData7(buf []byte) *CharacterData7 { return &CharacterData7{d: buf} }
func (s *CharacterData7) Bytes() []byte           { return s.d }
func (s *CharacterData7) Len() int                { return len(s.d) }

func (s *CharacterData7) SlotIndex() byte         { return s.d[0] }
func (s *CharacterData7) SetSlotIndex(value byte) { s.d[0] = byte(value) }

func (s *CharacterData7) Name() []byte         { return cstring(s.d[1:11]) }
func (s *CharacterData7) NameString() string   { return string(cstring(s.d[1:11])) }
func (s *CharacterData7) SetName(value string) { writeCString(s.d[1:11], value) }

func (s *CharacterData7) Level() uint16         { return getU16LE(s.d[12:]) }
func (s *CharacterData7) SetLevel(value uint16) { setU16LE(s.d[12:], value) }

func (s *CharacterData7) Status() CharacterStatus         { return CharacterStatus(byteBits(s.d[14], 4, 0)) }
func (s *CharacterData7) SetStatus(value CharacterStatus) { setByteBits(&s.d[14], byte(value), 4, 0) }

func (s *CharacterData7) IsItemBlockActive() bool { return s.d[14]&(1<<4) != 0 }
func (s *CharacterData7) SetIsItemBlockActive(value bool) {
	if value {
		s.d[14] |= 1 << 4
	} else {
		s.d[14] &^= 1 << 4
	}
}

func (s *CharacterData7) Appearance() []byte { return s.d[15:42] }

func (s *CharacterData7) GuildPosition() GuildMemberRole         { return GuildMemberRole(s.d[42]) }
func (s *CharacterData7) SetGuildPosition(value GuildMemberRole) { s.d[42] = byte(value) }

// CharacterData8 Data of one character in the list.
type CharacterData8 struct{ d []byte }

const CharacterData8Length = 24

func AsCharacterData8(buf []byte) *CharacterData8 { return &CharacterData8{d: buf} }
func (s *CharacterData8) Bytes() []byte           { return s.d }
func (s *CharacterData8) Len() int                { return len(s.d) }

func (s *CharacterData8) SlotIndex() byte         { return s.d[0] }
func (s *CharacterData8) SetSlotIndex(value byte) { s.d[0] = byte(value) }

func (s *CharacterData8) Name() []byte         { return cstring(s.d[1:11]) }
func (s *CharacterData8) NameString() string   { return string(cstring(s.d[1:11])) }
func (s *CharacterData8) SetName(value string) { writeCString(s.d[1:11], value) }

func (s *CharacterData8) Level() uint16         { return getU16BE(s.d[11:]) }
func (s *CharacterData8) SetLevel(value uint16) { setU16BE(s.d[11:], value) }

func (s *CharacterData8) Status() CharacterStatus         { return CharacterStatus(byteBits(s.d[13], 4, 0)) }
func (s *CharacterData8) SetStatus(value CharacterStatus) { setByteBits(&s.d[13], byte(value), 4, 0) }

func (s *CharacterData8) IsItemBlockActive() bool { return s.d[13]&(1<<4) != 0 }
func (s *CharacterData8) SetIsItemBlockActive(value bool) {
	if value {
		s.d[13] |= 1 << 4
	} else {
		s.d[13] &^= 1 << 4
	}
}

func (s *CharacterData8) Appearance() []byte { return s.d[14:23] }

// CharacterData9 Data of one character in the list.
type CharacterData9 struct{ d []byte }

const CharacterData9Length = 26

func AsCharacterData9(buf []byte) *CharacterData9 { return &CharacterData9{d: buf} }
func (s *CharacterData9) Bytes() []byte           { return s.d }
func (s *CharacterData9) Len() int                { return len(s.d) }

func (s *CharacterData9) SlotIndex() byte         { return s.d[0] }
func (s *CharacterData9) SetSlotIndex(value byte) { s.d[0] = byte(value) }

func (s *CharacterData9) Name() []byte         { return cstring(s.d[1:11]) }
func (s *CharacterData9) NameString() string   { return string(cstring(s.d[1:11])) }
func (s *CharacterData9) SetName(value string) { writeCString(s.d[1:11], value) }

func (s *CharacterData9) Level() uint16         { return getU16LE(s.d[12:]) }
func (s *CharacterData9) SetLevel(value uint16) { setU16LE(s.d[12:], value) }

func (s *CharacterData9) Status() CharacterStatus         { return CharacterStatus(byteBits(s.d[14], 4, 0)) }
func (s *CharacterData9) SetStatus(value CharacterStatus) { setByteBits(&s.d[14], byte(value), 4, 0) }

func (s *CharacterData9) IsItemBlockActive() bool { return s.d[14]&(1<<4) != 0 }
func (s *CharacterData9) SetIsItemBlockActive(value bool) {
	if value {
		s.d[14] |= 1 << 4
	} else {
		s.d[14] &^= 1 << 4
	}
}

func (s *CharacterData9) Appearance() []byte { return s.d[15:26] }

// SkillEntry Structure for a skill entry of the skill list.
type SkillEntry struct{ d []byte }

const SkillEntryLength = 4

func AsSkillEntry(buf []byte) *SkillEntry { return &SkillEntry{d: buf} }
func (s *SkillEntry) Bytes() []byte       { return s.d }
func (s *SkillEntry) Len() int            { return len(s.d) }

func (s *SkillEntry) SkillIndex() byte         { return s.d[0] }
func (s *SkillEntry) SetSkillIndex(value byte) { s.d[0] = byte(value) }

func (s *SkillEntry) SkillNumber() uint16         { return getU16LE(s.d[1:]) }
func (s *SkillEntry) SetSkillNumber(value uint16) { setU16LE(s.d[1:], value) }

func (s *SkillEntry) SkillLevel() byte         { return s.d[3] }
func (s *SkillEntry) SetSkillLevel(value byte) { s.d[3] = byte(value) }

// SkillEntry2 Structure for a skill entry of the skill list.
type SkillEntry2 struct{ d []byte }

const SkillEntry2Length = 3

func AsSkillEntry2(buf []byte) *SkillEntry2 { return &SkillEntry2{d: buf} }
func (s *SkillEntry2) Bytes() []byte        { return s.d }
func (s *SkillEntry2) Len() int             { return len(s.d) }

func (s *SkillEntry2) SkillIndex() byte         { return s.d[0] }
func (s *SkillEntry2) SetSkillIndex(value byte) { s.d[0] = byte(value) }

func (s *SkillEntry2) SkillNumberAndLevel() uint16         { return getU16BE(s.d[1:]) }
func (s *SkillEntry2) SetSkillNumberAndLevel(value uint16) { setU16BE(s.d[1:], value) }

// MasterSkillEntry An entry in the master skill list.
type MasterSkillEntry struct{ d []byte }

const MasterSkillEntryLength = 12

func AsMasterSkillEntry(buf []byte) *MasterSkillEntry { return &MasterSkillEntry{d: buf} }
func (s *MasterSkillEntry) Bytes() []byte             { return s.d }
func (s *MasterSkillEntry) Len() int                  { return len(s.d) }

func (s *MasterSkillEntry) MasterSkillIndex() byte         { return s.d[0] }
func (s *MasterSkillEntry) SetMasterSkillIndex(value byte) { s.d[0] = byte(value) }

func (s *MasterSkillEntry) Level() byte         { return s.d[1] }
func (s *MasterSkillEntry) SetLevel(value byte) { s.d[1] = byte(value) }

func (s *MasterSkillEntry) DisplayValue() float32         { return getF32(s.d[4:]) }
func (s *MasterSkillEntry) SetDisplayValue(value float32) { setF32(s.d[4:], value) }

func (s *MasterSkillEntry) DisplayValueOfNextLevel() float32         { return getF32(s.d[8:]) }
func (s *MasterSkillEntry) SetDisplayValueOfNextLevel(value float32) { setF32(s.d[8:], value) }

// GuildMember Contains the data of one guild member.
type GuildMember struct{ d []byte }

const GuildMemberLength = 13

func AsGuildMember(buf []byte) *GuildMember { return &GuildMember{d: buf} }
func (s *GuildMember) Bytes() []byte        { return s.d }
func (s *GuildMember) Len() int             { return len(s.d) }

func (s *GuildMember) Name() []byte         { return cstring(s.d[0:10]) }
func (s *GuildMember) NameString() string   { return string(cstring(s.d[0:10])) }
func (s *GuildMember) SetName(value string) { writeCString(s.d[0:10], value) }

func (s *GuildMember) ServerId() byte         { return s.d[10] }
func (s *GuildMember) SetServerId(value byte) { s.d[10] = byte(value) }

func (s *GuildMember) ServerId2() byte         { return s.d[11] }
func (s *GuildMember) SetServerId2(value byte) { s.d[11] = byte(value) }

func (s *GuildMember) Role() GuildMemberRole         { return GuildMemberRole(s.d[12]) }
func (s *GuildMember) SetRole(value GuildMemberRole) { s.d[12] = byte(value) }

// GuildMember2 Contains the data of one guild member.
type GuildMember2 struct{ d []byte }

const GuildMember2Length = 12

func AsGuildMember2(buf []byte) *GuildMember2 { return &GuildMember2{d: buf} }
func (s *GuildMember2) Bytes() []byte         { return s.d }
func (s *GuildMember2) Len() int              { return len(s.d) }

func (s *GuildMember2) Name() []byte         { return cstring(s.d[0:10]) }
func (s *GuildMember2) NameString() string   { return string(cstring(s.d[0:10])) }
func (s *GuildMember2) SetName(value string) { writeCString(s.d[0:10], value) }

func (s *GuildMember2) ServerId() byte         { return s.d[10] }
func (s *GuildMember2) SetServerId(value byte) { s.d[10] = byte(value) }

func (s *GuildMember2) ServerId2() byte         { return s.d[11] }
func (s *GuildMember2) SetServerId2(value byte) { s.d[11] = byte(value) }

// AllianceGuildEntry Contains the data of one alliance guild entry.
type AllianceGuildEntry struct{ d []byte }

const AllianceGuildEntryLength = 41

func AsAllianceGuildEntry(buf []byte) *AllianceGuildEntry { return &AllianceGuildEntry{d: buf} }
func (s *AllianceGuildEntry) Bytes() []byte               { return s.d }
func (s *AllianceGuildEntry) Len() int                    { return len(s.d) }

func (s *AllianceGuildEntry) MemberCount() byte         { return s.d[0] }
func (s *AllianceGuildEntry) SetMemberCount(value byte) { s.d[0] = byte(value) }

func (s *AllianceGuildEntry) Logo() []byte { return s.d[1:33] }

func (s *AllianceGuildEntry) GuildName() []byte         { return cstring(s.d[33:41]) }
func (s *AllianceGuildEntry) GuildNameString() string   { return string(cstring(s.d[33:41])) }
func (s *AllianceGuildEntry) SetGuildName(value string) { writeCString(s.d[33:41], value) }

// GuildMemberRelation Relation between a guild and a member.
type GuildMemberRelation struct{ d []byte }

const GuildMemberRelationLength = 12

func AsGuildMemberRelation(buf []byte) *GuildMemberRelation { return &GuildMemberRelation{d: buf} }
func (s *GuildMemberRelation) Bytes() []byte                { return s.d }
func (s *GuildMemberRelation) Len() int                     { return len(s.d) }

func (s *GuildMemberRelation) GuildId() uint32         { return getU32LE(s.d[0:]) }
func (s *GuildMemberRelation) SetGuildId(value uint32) { setU32LE(s.d[0:], value) }

func (s *GuildMemberRelation) Role() GuildMemberRole         { return GuildMemberRole(s.d[4]) }
func (s *GuildMemberRelation) SetRole(value GuildMemberRole) { s.d[4] = byte(value) }

func (s *GuildMemberRelation) IsPlayerAppearingNew() bool { return s.d[7]&(1<<7) != 0 }
func (s *GuildMemberRelation) SetIsPlayerAppearingNew(value bool) {
	if value {
		s.d[7] |= 1 << 7
	} else {
		s.d[7] &^= 1 << 7
	}
}

func (s *GuildMemberRelation) PlayerId() uint16         { return getU16BE(s.d[7:]) }
func (s *GuildMemberRelation) SetPlayerId(value uint16) { setU16BE(s.d[7:], value) }

// GuildMemberRelation2 Relation between a guild and a member.
type GuildMemberRelation2 struct{ d []byte }

const GuildMemberRelation2Length = 4

func AsGuildMemberRelation2(buf []byte) *GuildMemberRelation2 { return &GuildMemberRelation2{d: buf} }
func (s *GuildMemberRelation2) Bytes() []byte                 { return s.d }
func (s *GuildMemberRelation2) Len() int                      { return len(s.d) }

func (s *GuildMemberRelation2) PlayerId() uint16         { return getU16BE(s.d[0:]) }
func (s *GuildMemberRelation2) SetPlayerId(value uint16) { setU16BE(s.d[0:], value) }

func (s *GuildMemberRelation2) GuildId() uint16         { return getU16BE(s.d[2:]) }
func (s *GuildMemberRelation2) SetGuildId(value uint16) { setU16BE(s.d[2:], value) }

// GuildInfo Information about one guild.
type GuildInfo struct{ d []byte }

const GuildInfoLength = 42

func AsGuildInfo(buf []byte) *GuildInfo { return &GuildInfo{d: buf} }
func (s *GuildInfo) Bytes() []byte      { return s.d }
func (s *GuildInfo) Len() int           { return len(s.d) }

func (s *GuildInfo) GuildId() uint16         { return getU16BE(s.d[0:]) }
func (s *GuildInfo) SetGuildId(value uint16) { setU16BE(s.d[0:], value) }

func (s *GuildInfo) GuildName() []byte         { return cstring(s.d[2:10]) }
func (s *GuildInfo) GuildNameString() string   { return string(cstring(s.d[2:10])) }
func (s *GuildInfo) SetGuildName(value string) { writeCString(s.d[2:10], value) }

func (s *GuildInfo) Logo() []byte { return s.d[10:42] }

// MonsterKillInfo A pair of Monster number and the current kill count.
type MonsterKillInfo struct{ d []byte }

const MonsterKillInfoLength = 8

func AsMonsterKillInfo(buf []byte) *MonsterKillInfo { return &MonsterKillInfo{d: buf} }
func (s *MonsterKillInfo) Bytes() []byte            { return s.d }
func (s *MonsterKillInfo) Len() int                 { return len(s.d) }

func (s *MonsterKillInfo) MonsterNumber() uint32         { return getU32LE(s.d[0:]) }
func (s *MonsterKillInfo) SetMonsterNumber(value uint32) { setU32LE(s.d[0:], value) }

func (s *MonsterKillInfo) KillCount() uint32         { return getU32LE(s.d[4:]) }
func (s *MonsterKillInfo) SetKillCount(value uint32) { setU32LE(s.d[4:], value) }

// DuelRoomStatus Structure for a duel room entry.
type DuelRoomStatus struct{ d []byte }

const DuelRoomStatusLength = 22

func AsDuelRoomStatus(buf []byte) *DuelRoomStatus { return &DuelRoomStatus{d: buf} }
func (s *DuelRoomStatus) Bytes() []byte           { return s.d }
func (s *DuelRoomStatus) Len() int                { return len(s.d) }

func (s *DuelRoomStatus) Player1Name() []byte         { return cstring(s.d[0:10]) }
func (s *DuelRoomStatus) Player1NameString() string   { return string(cstring(s.d[0:10])) }
func (s *DuelRoomStatus) SetPlayer1Name(value string) { writeCString(s.d[0:10], value) }

func (s *DuelRoomStatus) Player2Name() []byte         { return cstring(s.d[10:20]) }
func (s *DuelRoomStatus) Player2NameString() string   { return string(cstring(s.d[10:20])) }
func (s *DuelRoomStatus) SetPlayer2Name(value string) { writeCString(s.d[10:20], value) }

func (s *DuelRoomStatus) DuelRunning() bool { return s.d[20]&(1<<0) != 0 }
func (s *DuelRoomStatus) SetDuelRunning(value bool) {
	if value {
		s.d[20] |= 1 << 0
	} else {
		s.d[20] &^= 1 << 0
	}
}

func (s *DuelRoomStatus) DuelOpen() bool { return s.d[21]&(1<<0) != 0 }
func (s *DuelRoomStatus) SetDuelOpen(value bool) {
	if value {
		s.d[21] |= 1 << 0
	} else {
		s.d[21] &^= 1 << 0
	}
}

// DuelSpectator Structure for a duel room entry.
type DuelSpectator struct{ d []byte }

const DuelSpectatorLength = 10

func AsDuelSpectator(buf []byte) *DuelSpectator { return &DuelSpectator{d: buf} }
func (s *DuelSpectator) Bytes() []byte          { return s.d }
func (s *DuelSpectator) Len() int               { return len(s.d) }

func (s *DuelSpectator) Name() []byte         { return cstring(s.d[0:10]) }
func (s *DuelSpectator) NameString() string   { return string(cstring(s.d[0:10])) }
func (s *DuelSpectator) SetName(value string) { writeCString(s.d[0:10], value) }

// IllusionTemplePartyEntry Contains the info about a party member in illusion temple.
type IllusionTemplePartyEntry struct{ d []byte }

const IllusionTemplePartyEntryLength = 5

func AsIllusionTemplePartyEntry(buf []byte) *IllusionTemplePartyEntry {
	return &IllusionTemplePartyEntry{d: buf}
}
func (s *IllusionTemplePartyEntry) Bytes() []byte { return s.d }
func (s *IllusionTemplePartyEntry) Len() int      { return len(s.d) }

func (s *IllusionTemplePartyEntry) PlayerId() uint16         { return getU16LE(s.d[0:]) }
func (s *IllusionTemplePartyEntry) SetPlayerId(value uint16) { setU16LE(s.d[0:], value) }

func (s *IllusionTemplePartyEntry) MapNumber() uint16         { return getU16LE(s.d[2:]) }
func (s *IllusionTemplePartyEntry) SetMapNumber(value uint16) { setU16LE(s.d[2:], value) }

func (s *IllusionTemplePartyEntry) PositionX() byte         { return s.d[3] }
func (s *IllusionTemplePartyEntry) SetPositionX(value byte) { s.d[3] = byte(value) }

func (s *IllusionTemplePartyEntry) PositionY() byte         { return s.d[4] }
func (s *IllusionTemplePartyEntry) SetPositionY(value byte) { s.d[4] = byte(value) }

// PlayerResult Contains the result of a player in the event.
type PlayerResult struct{ d []byte }

const PlayerResultLength = 17

func AsPlayerResult(buf []byte) *PlayerResult { return &PlayerResult{d: buf} }
func (s *PlayerResult) Bytes() []byte         { return s.d }
func (s *PlayerResult) Len() int              { return len(s.d) }

func (s *PlayerResult) Name() []byte         { return cstring(s.d[0:]) }
func (s *PlayerResult) NameString() string   { return string(cstring(s.d[0:])) }
func (s *PlayerResult) SetName(value string) { writeCString(s.d[0:], value) }

func (s *PlayerResult) MapNumber() byte         { return s.d[10] }
func (s *PlayerResult) SetMapNumber(value byte) { s.d[10] = byte(value) }

func (s *PlayerResult) Team() byte         { return s.d[11] }
func (s *PlayerResult) SetTeam(value byte) { s.d[11] = byte(value) }

func (s *PlayerResult) Class() byte         { return s.d[12] }
func (s *PlayerResult) SetClass(value byte) { s.d[12] = byte(value) }

func (s *PlayerResult) AddedExperience() uint32         { return getU32LE(s.d[13:]) }
func (s *PlayerResult) SetAddedExperience(value uint32) { setU32LE(s.d[13:], value) }

// ChainTarget Contains the target identifier.
type ChainTarget struct{ d []byte }

const ChainTargetLength = 2

func AsChainTarget(buf []byte) *ChainTarget { return &ChainTarget{d: buf} }
func (s *ChainTarget) Bytes() []byte        { return s.d }
func (s *ChainTarget) Len() int             { return len(s.d) }

func (s *ChainTarget) TargetId() uint16         { return getU16LE(s.d[0:]) }
func (s *ChainTarget) SetTargetId(value uint16) { setU16LE(s.d[0:], value) }

// Friend The structure which contains the friend name and online state.
type Friend struct{ d []byte }

const FriendLength = 11

func AsFriend(buf []byte) *Friend { return &Friend{d: buf} }
func (s *Friend) Bytes() []byte   { return s.d }
func (s *Friend) Len() int        { return len(s.d) }

func (s *Friend) Name() []byte         { return cstring(s.d[0:10]) }
func (s *Friend) NameString() string   { return string(cstring(s.d[0:10])) }
func (s *Friend) SetName(value string) { writeCString(s.d[0:10], value) }

func (s *Friend) ServerId() byte         { return s.d[10] }
func (s *Friend) SetServerId(value byte) { s.d[10] = byte(value) }

// ResultItem The result of one player.
type ResultItem struct{ d []byte }

const ResultItemLength = 24

func AsResultItem(buf []byte) *ResultItem { return &ResultItem{d: buf} }
func (s *ResultItem) Bytes() []byte       { return s.d }
func (s *ResultItem) Len() int            { return len(s.d) }

func (s *ResultItem) PlayerName() []byte         { return cstring(s.d[0:10]) }
func (s *ResultItem) PlayerNameString() string   { return string(cstring(s.d[0:10])) }
func (s *ResultItem) SetPlayerName(value string) { writeCString(s.d[0:10], value) }

func (s *ResultItem) TotalScore() uint32         { return getU32LE(s.d[12:]) }
func (s *ResultItem) SetTotalScore(value uint32) { setU32LE(s.d[12:], value) }

func (s *ResultItem) BonusExperience() uint32         { return getU32LE(s.d[16:]) }
func (s *ResultItem) SetBonusExperience(value uint32) { setU32LE(s.d[16:], value) }

func (s *ResultItem) BonusMoney() uint32         { return getU32LE(s.d[20:]) }
func (s *ResultItem) SetBonusMoney(value uint32) { setU32LE(s.d[20:], value) }

// ChatCommandParameter Describes one parameter of a chat command, so that a user interface can offer an input for it.
type ChatCommandParameter struct{ d []byte }

const ChatCommandParameterLength = 102

func AsChatCommandParameter(buf []byte) *ChatCommandParameter { return &ChatCommandParameter{d: buf} }
func (s *ChatCommandParameter) Bytes() []byte                 { return s.d }
func (s *ChatCommandParameter) Len() int                      { return len(s.d) }

func (s *ChatCommandParameter) IsRequired() bool { return s.d[0]&(1<<0) != 0 }
func (s *ChatCommandParameter) SetIsRequired(value bool) {
	if value {
		s.d[0] |= 1 << 0
	} else {
		s.d[0] &^= 1 << 0
	}
}

func (s *ChatCommandParameter) Type() ChatCommandParameterType {
	return ChatCommandParameterType(s.d[1])
}
func (s *ChatCommandParameter) SetType(value ChatCommandParameterType) { s.d[1] = byte(value) }

func (s *ChatCommandParameter) Name() []byte         { return cstring(s.d[2:34]) }
func (s *ChatCommandParameter) NameString() string   { return string(cstring(s.d[2:34])) }
func (s *ChatCommandParameter) SetName(value string) { writeCString(s.d[2:34], value) }

func (s *ChatCommandParameter) ShortName() []byte         { return cstring(s.d[34:54]) }
func (s *ChatCommandParameter) ShortNameString() string   { return string(cstring(s.d[34:54])) }
func (s *ChatCommandParameter) SetShortName(value string) { writeCString(s.d[34:54], value) }

func (s *ChatCommandParameter) ValidValues() []byte         { return cstring(s.d[54:102]) }
func (s *ChatCommandParameter) ValidValuesString() string   { return string(cstring(s.d[54:102])) }
func (s *ChatCommandParameter) SetValidValues(value string) { writeCString(s.d[54:102], value) }
