// Code generated by muprotogen; DO NOT EDIT.

package c2s

import "testing"

func TestFixedPacketsLayout(t *testing.T) {
	cases := []struct {
		name   string
		size   int
		header byte
		code   byte
		hasSub bool
		sub    byte
		mk     func() []byte
	}{
		{"Ping", 12, 0xC3, 0x0E, true, 0x00, func() []byte { return NewPing().Bytes() }},
		{"ChecksumResponse", 8, 0xC3, 0x03, false, 0x00, func() []byte { return NewChecksumResponse().Bytes() }},
		{"LoginLongPassword", 60, 0xC3, 0xF1, true, 0x01, func() []byte { return NewLoginLongPassword().Bytes() }},
		{"LoginShortPassword", 50, 0xC3, 0xF1, true, 0x01, func() []byte { return NewLoginShortPassword().Bytes() }},
		{"Login075", 48, 0xC3, 0xF1, true, 0x01, func() []byte { return NewLogin075().Bytes() }},
		{"LogOut", 5, 0xC3, 0xF1, true, 0x02, func() []byte { return NewLogOut().Bytes() }},
		{"LogOutByCheatDetection", 6, 0xC3, 0xF1, true, 0x03, func() []byte { return NewLogOutByCheatDetection().Bytes() }},
		{"ResetCharacterPointRequest", 4, 0xC1, 0xF2, true, 0x00, func() []byte { return NewResetCharacterPointRequest().Bytes() }},
		{"PlayerShopSetItemPrice", 9, 0xC3, 0x3F, true, 0x01, func() []byte { return NewPlayerShopSetItemPrice().Bytes() }},
		{"PlayerShopOpen", 30, 0xC3, 0x3F, true, 0x02, func() []byte { return NewPlayerShopOpen().Bytes() }},
		{"PlayerShopClose", 4, 0xC3, 0x3F, true, 0x03, func() []byte { return NewPlayerShopClose().Bytes() }},
		{"PlayerShopItemListRequest", 16, 0xC3, 0x3F, true, 0x05, func() []byte { return NewPlayerShopItemListRequest().Bytes() }},
		{"PlayerShopItemBuyRequest", 17, 0xC3, 0x3F, true, 0x06, func() []byte { return NewPlayerShopItemBuyRequest().Bytes() }},
		{"PlayerShopCloseOther", 16, 0xC3, 0x3F, true, 0x07, func() []byte { return NewPlayerShopCloseOther().Bytes() }},
		{"PickupItemRequest", 5, 0xC3, 0x22, false, 0x00, func() []byte { return NewPickupItemRequest().Bytes() }},
		{"PickupItemRequest075", 5, 0xC1, 0x22, false, 0x00, func() []byte { return NewPickupItemRequest075().Bytes() }},
		{"DropItemRequest", 6, 0xC3, 0x23, false, 0x00, func() []byte { return NewDropItemRequest().Bytes() }},
		{"ItemMoveRequest", 19, 0xC3, 0x24, false, 0x00, func() []byte { return NewItemMoveRequest().Bytes() }},
		{"ItemMoveRequestExtended", 7, 0xC3, 0x24, false, 0x00, func() []byte { return NewItemMoveRequestExtended().Bytes() }},
		{"ConsumeItemRequest", 6, 0xC3, 0x26, false, 0x00, func() []byte { return NewConsumeItemRequest().Bytes() }},
		{"ConsumeItemRequest075", 5, 0xC1, 0x26, false, 0x00, func() []byte { return NewConsumeItemRequest075().Bytes() }},
		{"TalkToNpcRequest", 5, 0xC3, 0x30, false, 0x00, func() []byte { return NewTalkToNpcRequest().Bytes() }},
		{"CloseNpcRequest", 3, 0xC1, 0x31, false, 0x00, func() []byte { return NewCloseNpcRequest().Bytes() }},
		{"BuyItemFromNpcRequest", 4, 0xC3, 0x32, false, 0x00, func() []byte { return NewBuyItemFromNpcRequest().Bytes() }},
		{"SellItemToNpcRequest", 4, 0xC3, 0x33, false, 0x00, func() []byte { return NewSellItemToNpcRequest().Bytes() }},
		{"RepairItemRequest", 5, 0xC1, 0x34, false, 0x00, func() []byte { return NewRepairItemRequest().Bytes() }},
		{"WarpCommandRequest", 10, 0xC1, 0x8E, true, 0x02, func() []byte { return NewWarpCommandRequest().Bytes() }},
		{"EnterGateRequest", 8, 0xC3, 0x1C, false, 0x00, func() []byte { return NewEnterGateRequest().Bytes() }},
		{"EnterGateRequest075", 6, 0xC3, 0x1C, false, 0x00, func() []byte { return NewEnterGateRequest075().Bytes() }},
		{"TeleportTarget", 7, 0xC3, 0xB0, false, 0x00, func() []byte { return NewTeleportTarget().Bytes() }},
		{"ServerChangeAuthentication", 69, 0xC3, 0xB1, true, 0x01, func() []byte { return NewServerChangeAuthentication().Bytes() }},
		{"CastleSiegeStatusRequest", 4, 0xC1, 0xB2, true, 0x00, func() []byte { return NewCastleSiegeStatusRequest().Bytes() }},
		{"CastleSiegeRegistrationRequest", 4, 0xC1, 0xB2, true, 0x01, func() []byte { return NewCastleSiegeRegistrationRequest().Bytes() }},
		{"CastleSiegeUnregisterRequest", 5, 0xC1, 0xB2, true, 0x02, func() []byte { return NewCastleSiegeUnregisterRequest().Bytes() }},
		{"CastleSiegeRegistrationStateRequest", 4, 0xC1, 0xB2, true, 0x03, func() []byte { return NewCastleSiegeRegistrationStateRequest().Bytes() }},
		{"CastleSiegeMarkRegistration", 5, 0xC1, 0xB2, true, 0x04, func() []byte { return NewCastleSiegeMarkRegistration().Bytes() }},
		{"CastleSiegeDefenseBuyRequest", 12, 0xC1, 0xB2, true, 0x05, func() []byte { return NewCastleSiegeDefenseBuyRequest().Bytes() }},
		{"CastleSiegeDefenseRepairRequest", 12, 0xC1, 0xB2, true, 0x06, func() []byte { return NewCastleSiegeDefenseRepairRequest().Bytes() }},
		{"CastleSiegeDefenseUpgradeRequest", 20, 0xC1, 0xB2, true, 0x07, func() []byte { return NewCastleSiegeDefenseUpgradeRequest().Bytes() }},
		{"CastleSiegeTaxInfoRequest", 4, 0xC1, 0xB2, true, 0x08, func() []byte { return NewCastleSiegeTaxInfoRequest().Bytes() }},
		{"CastleSiegeTaxChangeRequest", 9, 0xC1, 0xB2, true, 0x09, func() []byte { return NewCastleSiegeTaxChangeRequest().Bytes() }},
		{"CastleSiegeTaxMoneyWithdraw", 8, 0xC1, 0xB2, true, 0x10, func() []byte { return NewCastleSiegeTaxMoneyWithdraw().Bytes() }},
		{"ToggleCastleGateRequest", 7, 0xC1, 0xB2, true, 0x12, func() []byte { return NewToggleCastleGateRequest().Bytes() }},
		{"CastleGuildCommand", 8, 0xC1, 0xB2, true, 0x1D, func() []byte { return NewCastleGuildCommand().Bytes() }},
		{"CastleSiegeHuntingZoneEntranceSetting", 5, 0xC1, 0xB2, true, 0x1F, func() []byte { return NewCastleSiegeHuntingZoneEntranceSetting().Bytes() }},
		{"CastleSiegeGateListRequest", 4, 0xC1, 0xB3, true, 0x01, func() []byte { return NewCastleSiegeGateListRequest().Bytes() }},
		{"CastleSiegeStatueListRequest", 4, 0xC1, 0xB3, true, 0x02, func() []byte { return NewCastleSiegeStatueListRequest().Bytes() }},
		{"CastleSiegeRegisteredGuildsListRequest", 3, 0xC1, 0xB4, false, 0x00, func() []byte { return NewCastleSiegeRegisteredGuildsListRequest().Bytes() }},
		{"CastleOwnerListRequest", 3, 0xC1, 0xB5, false, 0x00, func() []byte { return NewCastleOwnerListRequest().Bytes() }},
		{"FireCatapultRequest", 7, 0xC1, 0xB7, true, 0x01, func() []byte { return NewFireCatapultRequest().Bytes() }},
		{"WeaponExplosionRequest", 6, 0xC1, 0xB7, true, 0x04, func() []byte { return NewWeaponExplosionRequest().Bytes() }},
		{"GuildLogoOfCastleOwnerRequest", 4, 0xC1, 0xB9, true, 0x02, func() []byte { return NewGuildLogoOfCastleOwnerRequest().Bytes() }},
		{"CastleSiegeHuntingZoneEnterRequest", 8, 0xC1, 0xB9, true, 0x05, func() []byte { return NewCastleSiegeHuntingZoneEnterRequest().Bytes() }},
		{"CrywolfInfoRequest", 4, 0xC1, 0xBD, true, 0x00, func() []byte { return NewCrywolfInfoRequest().Bytes() }},
		{"CrywolfContractRequest", 6, 0xC1, 0xBD, true, 0x03, func() []byte { return NewCrywolfContractRequest().Bytes() }},
		{"CrywolfChaosRateBenefitRequest", 4, 0xC1, 0xBD, true, 0x09, func() []byte { return NewCrywolfChaosRateBenefitRequest().Bytes() }},
		{"WhiteAngelItemRequest", 4, 0xC1, 0xD0, true, 0x03, func() []byte { return NewWhiteAngelItemRequest().Bytes() }},
		{"EnterOnWerewolfRequest", 4, 0xC1, 0xD0, true, 0x07, func() []byte { return NewEnterOnWerewolfRequest().Bytes() }},
		{"EnterOnGatekeeperRequest", 4, 0xC1, 0xD0, true, 0x08, func() []byte { return NewEnterOnGatekeeperRequest().Bytes() }},
		{"LeoHelperItemRequest", 4, 0xC1, 0xD0, true, 0x09, func() []byte { return NewLeoHelperItemRequest().Bytes() }},
		{"MoveToDeviasBySnowmanRequest", 4, 0xC1, 0xD0, true, 0x0A, func() []byte { return NewMoveToDeviasBySnowmanRequest().Bytes() }},
		{"SantaClausItemRequest", 4, 0xC1, 0xD0, true, 0x10, func() []byte { return NewSantaClausItemRequest().Bytes() }},
		{"KanturuInfoRequest", 4, 0xC1, 0xD1, true, 0x00, func() []byte { return NewKanturuInfoRequest().Bytes() }},
		{"KanturuEnterRequest", 4, 0xC1, 0xD1, true, 0x01, func() []byte { return NewKanturuEnterRequest().Bytes() }},
		{"RaklionStateInfoRequest", 4, 0xC1, 0xD1, true, 0x10, func() []byte { return NewRaklionStateInfoRequest().Bytes() }},
		{"CashShopPointInfoRequest", 4, 0xC1, 0xD2, true, 0x01, func() []byte { return NewCashShopPointInfoRequest().Bytes() }},
		{"CashShopOpenState", 5, 0xC1, 0xD2, true, 0x02, func() []byte { return NewCashShopOpenState().Bytes() }},
		{"CashShopItemBuyRequest", 23, 0xC1, 0xD2, true, 0x03, func() []byte { return NewCashShopItemBuyRequest().Bytes() }},
		{"CashShopItemGiftRequest", 234, 0xC1, 0xD2, true, 0x04, func() []byte { return NewCashShopItemGiftRequest().Bytes() }},
		{"CashShopStorageListRequest", 10, 0xC1, 0xD2, true, 0x05, func() []byte { return NewCashShopStorageListRequest().Bytes() }},
		{"CashShopDeleteStorageItemRequest", 234, 0xC1, 0xD2, true, 0x0A, func() []byte { return NewCashShopDeleteStorageItemRequest().Bytes() }},
		{"CashShopStorageItemConsumeRequest", 15, 0xC1, 0xD2, true, 0x0B, func() []byte { return NewCashShopStorageItemConsumeRequest().Bytes() }},
		{"CashShopEventItemListRequest", 8, 0xC1, 0xD2, true, 0x13, func() []byte { return NewCashShopEventItemListRequest().Bytes() }},
		{"UnlockVault", 7, 0xC1, 0x83, true, 0x00, func() []byte { return NewUnlockVault().Bytes() }},
		{"SetVaultPin", 27, 0xC1, 0x83, true, 0x01, func() []byte { return NewSetVaultPin().Bytes() }},
		{"RemoveVaultPin", 27, 0xC1, 0x83, true, 0x02, func() []byte { return NewRemoveVaultPin().Bytes() }},
		{"VaultClosed", 3, 0xC1, 0x82, false, 0x00, func() []byte { return NewVaultClosed().Bytes() }},
		{"VaultMoveMoneyRequest", 8, 0xC1, 0x81, false, 0x00, func() []byte { return NewVaultMoveMoneyRequest().Bytes() }},
		{"LahapJewelMixRequest", 7, 0xC1, 0xBC, false, 0x00, func() []byte { return NewLahapJewelMixRequest().Bytes() }},
		{"PartyListRequest", 3, 0xC1, 0x42, false, 0x00, func() []byte { return NewPartyListRequest().Bytes() }},
		{"PartyPlayerKickRequest", 4, 0xC1, 0x43, false, 0x00, func() []byte { return NewPartyPlayerKickRequest().Bytes() }},
		{"PartyInviteRequest", 5, 0xC1, 0x40, false, 0x00, func() []byte { return NewPartyInviteRequest().Bytes() }},
		{"PartyInviteResponse", 6, 0xC1, 0x41, false, 0x00, func() []byte { return NewPartyInviteResponse().Bytes() }},
		{"InstantMoveRequest", 5, 0xC1, 0x15, false, 0x00, func() []byte { return NewInstantMoveRequest().Bytes() }},
		{"AnimationRequest", 5, 0xC1, 0x18, false, 0x00, func() []byte { return NewAnimationRequest().Bytes() }},
		{"RequestCharacterList", 5, 0xC1, 0xF3, true, 0x00, func() []byte { return NewRequestCharacterList().Bytes() }},
		{"CreateCharacter", 15, 0xC1, 0xF3, true, 0x01, func() []byte { return NewCreateCharacter().Bytes() }},
		{"DeleteCharacter", 24, 0xC1, 0xF3, true, 0x02, func() []byte { return NewDeleteCharacter().Bytes() }},
		{"SelectCharacter", 14, 0xC1, 0xF3, true, 0x03, func() []byte { return NewSelectCharacter().Bytes() }},
		{"FocusCharacter", 14, 0xC1, 0xF3, true, 0x15, func() []byte { return NewFocusCharacter().Bytes() }},
		{"IncreaseCharacterStatPoint", 5, 0xC1, 0xF3, true, 0x06, func() []byte { return NewIncreaseCharacterStatPoint().Bytes() }},
		{"InventoryRequest", 4, 0xC3, 0xF3, true, 0x10, func() []byte { return NewInventoryRequest().Bytes() }},
		{"ClientReadyAfterMapChange", 4, 0xC1, 0xF3, true, 0x12, func() []byte { return NewClientReadyAfterMapChange().Bytes() }},
		{"AddMasterSkillPoint", 6, 0xC1, 0xF3, true, 0x52, func() []byte { return NewAddMasterSkillPoint().Bytes() }},
		{"HitRequest", 7, 0xC1, 0x11, false, 0x00, func() []byte { return NewHitRequest().Bytes() }},
		{"TargetedSkill", 7, 0xC3, 0x19, false, 0x00, func() []byte { return NewTargetedSkill().Bytes() }},
		{"TargetedSkill075", 6, 0xC1, 0x19, false, 0x00, func() []byte { return NewTargetedSkill075().Bytes() }},
		{"TargetedSkill095", 6, 0xC3, 0x19, false, 0x00, func() []byte { return NewTargetedSkill095().Bytes() }},
		{"MagicEffectCancelRequest", 7, 0xC1, 0x1B, false, 0x00, func() []byte { return NewMagicEffectCancelRequest().Bytes() }},
		{"AreaSkill", 13, 0xC3, 0x1E, false, 0x00, func() []byte { return NewAreaSkill().Bytes() }},
		{"AreaSkill075", 7, 0xC1, 0x1E, false, 0x00, func() []byte { return NewAreaSkill075().Bytes() }},
		{"AreaSkill095", 7, 0xC3, 0x1E, false, 0x00, func() []byte { return NewAreaSkill095().Bytes() }},
		{"RageAttackRequest", 8, 0xC3, 0x4A, false, 0x00, func() []byte { return NewRageAttackRequest().Bytes() }},
		{"RageAttackRangeRequest", 7, 0xC1, 0x4B, false, 0x00, func() []byte { return NewRageAttackRangeRequest().Bytes() }},
		{"TradeCancel", 3, 0xC1, 0x3D, false, 0x00, func() []byte { return NewTradeCancel().Bytes() }},
		{"TradeButtonStateChange", 4, 0xC1, 0x3C, false, 0x00, func() []byte { return NewTradeButtonStateChange().Bytes() }},
		{"TradeRequest", 5, 0xC3, 0x36, false, 0x00, func() []byte { return NewTradeRequest().Bytes() }},
		{"TradeRequestResponse", 4, 0xC1, 0x37, false, 0x00, func() []byte { return NewTradeRequestResponse().Bytes() }},
		{"SetTradeMoney", 8, 0xC1, 0x3A, false, 0x00, func() []byte { return NewSetTradeMoney().Bytes() }},
		{"LetterDeleteRequest", 6, 0xC1, 0xC8, false, 0x00, func() []byte { return NewLetterDeleteRequest().Bytes() }},
		{"LetterListRequest", 3, 0xC1, 0xC9, false, 0x00, func() []byte { return NewLetterListRequest().Bytes() }},
		{"LetterReadRequest", 6, 0xC1, 0xC7, false, 0x00, func() []byte { return NewLetterReadRequest().Bytes() }},
		{"GuildJoinRequest", 5, 0xC1, 0x50, false, 0x00, func() []byte { return NewGuildJoinRequest().Bytes() }},
		{"GuildJoinResponse", 6, 0xC1, 0x51, false, 0x00, func() []byte { return NewGuildJoinResponse().Bytes() }},
		{"GuildListRequest", 3, 0xC1, 0x52, false, 0x00, func() []byte { return NewGuildListRequest().Bytes() }},
		{"GuildCreateRequest", 44, 0xC1, 0x55, false, 0x00, func() []byte { return NewGuildCreateRequest().Bytes() }},
		{"GuildCreateRequest075", 43, 0xC1, 0x55, false, 0x00, func() []byte { return NewGuildCreateRequest075().Bytes() }},
		{"GuildMasterAnswer", 4, 0xC1, 0x54, false, 0x00, func() []byte { return NewGuildMasterAnswer().Bytes() }},
		{"CancelGuildCreation", 3, 0xC1, 0x57, false, 0x00, func() []byte { return NewCancelGuildCreation().Bytes() }},
		{"GuildWarResponse", 4, 0xC1, 0x61, false, 0x00, func() []byte { return NewGuildWarResponse().Bytes() }},
		{"GuildInfoRequest", 8, 0xC1, 0x66, false, 0x00, func() []byte { return NewGuildInfoRequest().Bytes() }},
		{"GuildRoleAssignRequest", 15, 0xC1, 0xE1, false, 0x00, func() []byte { return NewGuildRoleAssignRequest().Bytes() }},
		{"GuildTypeChangeRequest", 4, 0xC1, 0xE2, false, 0x00, func() []byte { return NewGuildTypeChangeRequest().Bytes() }},
		{"GuildRelationshipChangeRequest", 7, 0xC1, 0xE5, false, 0x00, func() []byte { return NewGuildRelationshipChangeRequest().Bytes() }},
		{"GuildRelationshipChangeResponse", 8, 0xC1, 0xE6, false, 0x00, func() []byte { return NewGuildRelationshipChangeResponse().Bytes() }},
		{"RequestAllianceList", 3, 0xC1, 0xE9, false, 0x00, func() []byte { return NewRequestAllianceList().Bytes() }},
		{"RemoveAllianceGuildRequest", 12, 0xC1, 0xEB, true, 0x01, func() []byte { return NewRemoveAllianceGuildRequest().Bytes() }},
		{"PingResponse", 3, 0xC1, 0x71, false, 0x00, func() []byte { return NewPingResponse().Bytes() }},
		{"ItemRepair", 4, 0xC3, 0x34, false, 0x00, func() []byte { return NewItemRepair().Bytes() }},
		{"ChaosMachineMixRequest", 5, 0xC1, 0x86, false, 0x00, func() []byte { return NewChaosMachineMixRequest().Bytes() }},
		{"CraftingDialogCloseRequest", 3, 0xC1, 0x87, false, 0x00, func() []byte { return NewCraftingDialogCloseRequest().Bytes() }},
		{"FriendListRequest", 3, 0xC1, 0xC0, false, 0x00, func() []byte { return NewFriendListRequest().Bytes() }},
		{"FriendAddRequest", 13, 0xC1, 0xC1, false, 0x00, func() []byte { return NewFriendAddRequest().Bytes() }},
		{"FriendDelete", 13, 0xC1, 0xC3, false, 0x00, func() []byte { return NewFriendDelete().Bytes() }},
		{"ChatRoomCreateRequest", 13, 0xC1, 0xCA, false, 0x00, func() []byte { return NewChatRoomCreateRequest().Bytes() }},
		{"FriendAddResponse", 14, 0xC1, 0xC2, false, 0x00, func() []byte { return NewFriendAddResponse().Bytes() }},
		{"SetFriendOnlineState", 4, 0xC1, 0xC4, false, 0x00, func() []byte { return NewSetFriendOnlineState().Bytes() }},
		{"ChatRoomInvitationRequest", 19, 0xC1, 0xCB, false, 0x00, func() []byte { return NewChatRoomInvitationRequest().Bytes() }},
		{"LegacyQuestStateRequest", 3, 0xC1, 0xA0, false, 0x00, func() []byte { return NewLegacyQuestStateRequest().Bytes() }},
		{"LegacyQuestStateSetRequest", 5, 0xC1, 0xA2, false, 0x00, func() []byte { return NewLegacyQuestStateSetRequest().Bytes() }},
		{"PetCommandRequest", 7, 0xC1, 0xA7, false, 0x00, func() []byte { return NewPetCommandRequest().Bytes() }},
		{"PetInfoRequest", 6, 0xC1, 0xA9, false, 0x00, func() []byte { return NewPetInfoRequest().Bytes() }},
		{"IllusionTempleEnterRequest", 6, 0xC1, 0xBF, true, 0x00, func() []byte { return NewIllusionTempleEnterRequest().Bytes() }},
		{"IllusionTempleSkillRequest", 8, 0xC1, 0xBF, true, 0x02, func() []byte { return NewIllusionTempleSkillRequest().Bytes() }},
		{"IllusionTempleRewardRequest", 4, 0xC1, 0xBF, true, 0x05, func() []byte { return NewIllusionTempleRewardRequest().Bytes() }},
		{"LuckyCoinCountRequest", 4, 0xC1, 0xBF, true, 0x0B, func() []byte { return NewLuckyCoinCountRequest().Bytes() }},
		{"LuckyCoinRegistrationRequest", 4, 0xC1, 0xBF, true, 0x0C, func() []byte { return NewLuckyCoinRegistrationRequest().Bytes() }},
		{"LuckyCoinExchangeRequest", 8, 0xC1, 0xBF, true, 0x0D, func() []byte { return NewLuckyCoinExchangeRequest().Bytes() }},
		{"DoppelgangerEnterRequest", 5, 0xC1, 0xBF, true, 0x0E, func() []byte { return NewDoppelgangerEnterRequest().Bytes() }},
		{"EnterMarketPlaceRequest", 4, 0xC1, 0xBF, true, 0x17, func() []byte { return NewEnterMarketPlaceRequest().Bytes() }},
		{"MuHelperStatusChangeRequest", 5, 0xC1, 0xBF, true, 0x51, func() []byte { return NewMuHelperStatusChangeRequest().Bytes() }},
		{"MuHelperSaveDataRequest", 261, 0xC2, 0xAE, false, 0x00, func() []byte { return NewMuHelperSaveDataRequest().Bytes() }},
		{"QuestSelectRequest", 9, 0xC1, 0xF6, true, 0x0A, func() []byte { return NewQuestSelectRequest().Bytes() }},
		{"QuestProceedRequest", 9, 0xC1, 0xF6, true, 0x0B, func() []byte { return NewQuestProceedRequest().Bytes() }},
		{"QuestCompletionRequest", 8, 0xC1, 0xF6, true, 0x0D, func() []byte { return NewQuestCompletionRequest().Bytes() }},
		{"QuestCancelRequest", 8, 0xC1, 0xF6, true, 0x0F, func() []byte { return NewQuestCancelRequest().Bytes() }},
		{"QuestClientActionRequest", 8, 0xC1, 0xF6, true, 0x10, func() []byte { return NewQuestClientActionRequest().Bytes() }},
		{"ActiveQuestListRequest", 4, 0xC1, 0xF6, true, 0x1A, func() []byte { return NewActiveQuestListRequest().Bytes() }},
		{"QuestStateRequest", 8, 0xC1, 0xF6, true, 0x1B, func() []byte { return NewQuestStateRequest().Bytes() }},
		{"EventQuestStateListRequest", 4, 0xC1, 0xF6, true, 0x21, func() []byte { return NewEventQuestStateListRequest().Bytes() }},
		{"AvailableQuestsRequest", 4, 0xC1, 0xF6, true, 0x30, func() []byte { return NewAvailableQuestsRequest().Bytes() }},
		{"NpcBuffRequest", 4, 0xC1, 0xF6, true, 0x31, func() []byte { return NewNpcBuffRequest().Bytes() }},
		{"EnterEmpireGuardianEvent", 5, 0xC1, 0xF7, true, 0x01, func() []byte { return NewEnterEmpireGuardianEvent().Bytes() }},
		{"GensJoinRequest", 5, 0xC1, 0xF8, true, 0x01, func() []byte { return NewGensJoinRequest().Bytes() }},
		{"GensLeaveRequest", 4, 0xC1, 0xF8, true, 0x03, func() []byte { return NewGensLeaveRequest().Bytes() }},
		{"GensRewardRequest", 5, 0xC1, 0xF8, true, 0x09, func() []byte { return NewGensRewardRequest().Bytes() }},
		{"GensRankingRequest", 4, 0xC1, 0xF8, true, 0x0B, func() []byte { return NewGensRankingRequest().Bytes() }},
		{"DevilSquareEnterRequest", 5, 0xC1, 0x90, false, 0x00, func() []byte { return NewDevilSquareEnterRequest().Bytes() }},
		{"MiniGameOpeningStateRequest", 5, 0xC1, 0x91, false, 0x00, func() []byte { return NewMiniGameOpeningStateRequest().Bytes() }},
		{"EventChipRegistrationRequest", 5, 0xC1, 0x95, false, 0x00, func() []byte { return NewEventChipRegistrationRequest().Bytes() }},
		{"MutoNumberRequest", 3, 0xC1, 0x96, false, 0x00, func() []byte { return NewMutoNumberRequest().Bytes() }},
		{"EventChipExitDialog", 3, 0xC1, 0x97, false, 0x00, func() []byte { return NewEventChipExitDialog().Bytes() }},
		{"EventChipExchangeRequest", 4, 0xC1, 0x98, false, 0x00, func() []byte { return NewEventChipExchangeRequest().Bytes() }},
		{"LuckyNumberRequest", 18, 0xC1, 0x9D, false, 0x00, func() []byte { return NewLuckyNumberRequest().Bytes() }},
		{"BloodCastleEnterRequest", 5, 0xC1, 0x9A, false, 0x00, func() []byte { return NewBloodCastleEnterRequest().Bytes() }},
		{"MiniGameEventCountRequest", 4, 0xC1, 0x9F, false, 0x00, func() []byte { return NewMiniGameEventCountRequest().Bytes() }},
		{"ChaosCastleEnterRequest", 6, 0xC1, 0xAF, true, 0x01, func() []byte { return NewChaosCastleEnterRequest().Bytes() }},
		{"ChaosCastlePositionSet", 6, 0xC1, 0xAF, true, 0x02, func() []byte { return NewChaosCastlePositionSet().Bytes() }},
		{"DuelStartRequest", 16, 0xC3, 0xAA, true, 0x01, func() []byte { return NewDuelStartRequest().Bytes() }},
		{"DuelStartResponse", 17, 0xC3, 0xAA, true, 0x02, func() []byte { return NewDuelStartResponse().Bytes() }},
		{"DuelStopRequest", 4, 0xC3, 0xAA, true, 0x03, func() []byte { return NewDuelStopRequest().Bytes() }},
		{"DuelChannelJoinRequest", 5, 0xC3, 0xAA, true, 0x07, func() []byte { return NewDuelChannelJoinRequest().Bytes() }},
		{"DuelChannelQuitRequest", 4, 0xC3, 0xAA, true, 0x09, func() []byte { return NewDuelChannelQuitRequest().Bytes() }},
		{"ChatCommandListRequest", 4, 0xC1, 0xF5, true, 0x00, func() []byte { return NewChatCommandListRequest().Bytes() }},
	}
	for _, tc := range cases {
		buf := tc.mk()
		if len(buf) != tc.size {
			t.Errorf("%s: got %d bytes, want %d", tc.name, len(buf), tc.size)
		}
		if buf[0] != tc.header {
			t.Errorf("%s: header 0x%02X, want 0x%02X", tc.name, buf[0], tc.header)
		}
		codeIdx := 2
		if tc.header == 0xC2 || tc.header == 0xC4 {
			codeIdx = 3
		}
		if buf[codeIdx] != tc.code {
			t.Errorf("%s: code 0x%02X, want 0x%02X", tc.name, buf[codeIdx], tc.code)
		}
		if tc.hasSub && buf[codeIdx+1] != tc.sub {
			t.Errorf("%s: sub 0x%02X, want 0x%02X", tc.name, buf[codeIdx+1], tc.sub)
		}
	}
}

func TestFixedStructSizes(t *testing.T) {
	cases := []struct {
		name string
		size int
		mk   func() []byte
	}{
		{"TargetData", 3, func() []byte { b := make([]byte, TargetDataLength); _ = AsTargetData(b); return b }},
		{"TargetData2", 2, func() []byte { b := make([]byte, TargetData2Length); _ = AsTargetData2(b); return b }},
		{"TargetData3", 2, func() []byte { b := make([]byte, TargetData3Length); _ = AsTargetData3(b); return b }},
	}
	for _, tc := range cases {
		if len(tc.mk()) != tc.size {
			t.Errorf("%s: size mismatch", tc.name)
		}
	}
}
