// Code generated by muprotogen from MUnique.OpenMU.Network.Packets 0.9.10; DO NOT EDIT.

package c2s

// ItemStorageKind Defines from or to which item storage an item is moved.
type ItemStorageKind uint16

const (
	// ItemStorageKind_Inventory The inventory storage.
	ItemStorageKind_Inventory ItemStorageKind = 0
	// ItemStorageKind_Trade The trade storage.
	ItemStorageKind_Trade ItemStorageKind = 1
	// ItemStorageKind_Vault The vault storage.
	ItemStorageKind_Vault ItemStorageKind = 2
	// ItemStorageKind_ChaosMachine The chaos machine storage.
	ItemStorageKind_ChaosMachine ItemStorageKind = 3
	// ItemStorageKind_PlayerShop The player shop storage.
	ItemStorageKind_PlayerShop ItemStorageKind = 4
	// ItemStorageKind_PetTrainer The pet trainer dialog storage.
	ItemStorageKind_PetTrainer ItemStorageKind = 5
	// ItemStorageKind_Refinery The storage of the refinery of the elphis npc.
	ItemStorageKind_Refinery ItemStorageKind = 6
	// ItemStorageKind_Smelting The storage of the smelting dialog of the osbourne npc.
	ItemStorageKind_Smelting ItemStorageKind = 7
	// ItemStorageKind_ItemRestore The storage of the item restore dialog of the jerridon npc.
	ItemStorageKind_ItemRestore ItemStorageKind = 8
	// ItemStorageKind_ChaosCardMaster The storage of the chaos card master dialog.
	ItemStorageKind_ChaosCardMaster ItemStorageKind = 9
	// ItemStorageKind_CherryBlossomSpirit The storage of the cherry blossom spirit dialog.
	ItemStorageKind_CherryBlossomSpirit ItemStorageKind = 10
	// ItemStorageKind_SeedCrafting The storage of the seed crafting dialog.
	ItemStorageKind_SeedCrafting ItemStorageKind = 11
	// ItemStorageKind_SeedSphereCrafting The storage of the seed sphere crafting dialog.
	ItemStorageKind_SeedSphereCrafting ItemStorageKind = 12
	// ItemStorageKind_SeedMountCrafting The storage of the seed sphere mount dialog.
	ItemStorageKind_SeedMountCrafting ItemStorageKind = 13
	// ItemStorageKind_SeedUnmountCrafting The storage of the seed sphere unmount dialog.
	ItemStorageKind_SeedUnmountCrafting ItemStorageKind = 14
)

// LegacyQuestState The quest state for the legacy quest system.
type LegacyQuestState uint16

const (
	// LegacyQuestState_Undefined The state is undefined. This value is used when there is no quest defined for a specific index
	LegacyQuestState_Undefined LegacyQuestState = 0
	// LegacyQuestState_Active The quest is active and in progress.
	LegacyQuestState_Active LegacyQuestState = 1
	// LegacyQuestState_Complete The quest was completed.
	LegacyQuestState_Complete LegacyQuestState = 2
	// LegacyQuestState_Inactive The quest is inactive, that means it isn't active and wasn't completed yet.
	LegacyQuestState_Inactive LegacyQuestState = 3
)

// CharacterClassNumber Defines the values which are used for the character classes on client side.
type CharacterClassNumber uint16

const (
	// CharacterClassNumber_DarkWizard Value for the dark wizard character class.
	CharacterClassNumber_DarkWizard CharacterClassNumber = 0
	// CharacterClassNumber_SoulMaster Value for the soul master character class.
	CharacterClassNumber_SoulMaster CharacterClassNumber = 2
	// CharacterClassNumber_GrandMaster Value for the grand master character class.
	CharacterClassNumber_GrandMaster CharacterClassNumber = 3
	// CharacterClassNumber_DarkKnight Value for the dark knight character class.
	CharacterClassNumber_DarkKnight CharacterClassNumber = 4
	// CharacterClassNumber_BladeKnight Value for the blade knight character class.
	CharacterClassNumber_BladeKnight CharacterClassNumber = 6
	// CharacterClassNumber_BladeMaster Value for the blade master character class.
	CharacterClassNumber_BladeMaster CharacterClassNumber = 7
	// CharacterClassNumber_FairyElf Value for the fairy elf character class.
	CharacterClassNumber_FairyElf CharacterClassNumber = 8
	// CharacterClassNumber_MuseElf Value for the muse elf character class.
	CharacterClassNumber_MuseElf CharacterClassNumber = 10
	// CharacterClassNumber_HighElf Value for the high elf character class.
	CharacterClassNumber_HighElf CharacterClassNumber = 11
	// CharacterClassNumber_MagicGladiator Value for the magic gladiator character class.
	CharacterClassNumber_MagicGladiator CharacterClassNumber = 12
	// CharacterClassNumber_DuelMaster Value for the duel master character class.
	CharacterClassNumber_DuelMaster CharacterClassNumber = 13
	// CharacterClassNumber_DarkLord Value for the dark lord character class.
	CharacterClassNumber_DarkLord CharacterClassNumber = 16
	// CharacterClassNumber_LordEmperor Value for the lord emperor character class.
	CharacterClassNumber_LordEmperor CharacterClassNumber = 17
	// CharacterClassNumber_Summoner Value for the summoner character class.
	CharacterClassNumber_Summoner CharacterClassNumber = 20
	// CharacterClassNumber_BloodySummoner Value for the bloody summoner character class.
	CharacterClassNumber_BloodySummoner CharacterClassNumber = 22
	// CharacterClassNumber_DimensionMaster Value for the dimension master character class.
	CharacterClassNumber_DimensionMaster CharacterClassNumber = 23
	// CharacterClassNumber_RageFighter Value for the rage fighter character class.
	CharacterClassNumber_RageFighter CharacterClassNumber = 24
	// CharacterClassNumber_FistMaster Value for the fist master character class.
	CharacterClassNumber_FistMaster CharacterClassNumber = 25
)

// CharacterStatAttribute Defines the type of a character stat attribute.
type CharacterStatAttribute uint16

const (
	// CharacterStatAttribute_Strength The strength attribute.
	CharacterStatAttribute_Strength CharacterStatAttribute = 0
	// CharacterStatAttribute_Agility The agility attribute.
	CharacterStatAttribute_Agility CharacterStatAttribute = 1
	// CharacterStatAttribute_Vitality The vitality attribute.
	CharacterStatAttribute_Vitality CharacterStatAttribute = 2
	// CharacterStatAttribute_Energy The energy attribute.
	CharacterStatAttribute_Energy CharacterStatAttribute = 3
	// CharacterStatAttribute_Leadership The leadership attribute.
	CharacterStatAttribute_Leadership CharacterStatAttribute = 4
)

// CharacterHeroState Defines the hero state of a character.
type CharacterHeroState uint16

const (
	// CharacterHeroState_New The character is new and has the highest state.
	CharacterHeroState_New CharacterHeroState = 0
	// CharacterHeroState_Hero The character is a hero.
	CharacterHeroState_Hero CharacterHeroState = 1
	// CharacterHeroState_LightHero The character is a hero, but the state is almost gone.
	CharacterHeroState_LightHero CharacterHeroState = 2
	// CharacterHeroState_Normal The character is in a neutral state.
	CharacterHeroState_Normal CharacterHeroState = 3
	// CharacterHeroState_PlayerKillWarning The character killed another character, and has a kill warning.
	CharacterHeroState_PlayerKillWarning CharacterHeroState = 4
	// CharacterHeroState_PlayerKiller1stStage The character killed two characters, and has some restrictions.
	CharacterHeroState_PlayerKiller1stStage CharacterHeroState = 5
	// CharacterHeroState_PlayerKiller2ndStage The character killed more than two characters, and has hard restrictions.
	CharacterHeroState_PlayerKiller2ndStage CharacterHeroState = 6
)

// LogOutType Describes the way how the player wants to leave the current game.
type LogOutType uint16

const (
	// LogOutType_CloseGame The player wants to close the game.
	LogOutType_CloseGame LogOutType = 0
	// LogOutType_BackToCharacterSelection The player wants to go back to the character selection screen.
	LogOutType_BackToCharacterSelection LogOutType = 1
	// LogOutType_BackToServerSelection The player wants to go back to the server selection screen.
	LogOutType_BackToServerSelection LogOutType = 2
)

// MiniGameType Defines the type of the mini game.
type MiniGameType uint16

const (
	// MiniGameType_Undefined Undefined mini game type.
	MiniGameType_Undefined MiniGameType = 0
	// MiniGameType_DevilSquare The devil square mini game.
	MiniGameType_DevilSquare MiniGameType = 1
	// MiniGameType_BloodCastle The blood castle mini game.
	MiniGameType_BloodCastle MiniGameType = 2
	// MiniGameType_CursedTemple The cursed temple mini game.
	MiniGameType_CursedTemple MiniGameType = 3
	// MiniGameType_ChaosCastle The chaos castle mini game.
	MiniGameType_ChaosCastle MiniGameType = 4
	// MiniGameType_IllusionTemple The illusion temple mini game.
	MiniGameType_IllusionTemple MiniGameType = 5
	// MiniGameType_Doppelganger The doppelgänger mini game.
	MiniGameType_Doppelganger MiniGameType = 6
)

// ServerToClientGuildMemberRole Defines the role of a guild member.
type ServerToClientGuildMemberRole uint16

const (
	// ServerToClientGuildMemberRole_NormalMember The member is a normal member without special rights.
	ServerToClientGuildMemberRole_NormalMember ServerToClientGuildMemberRole = 0
	// ServerToClientGuildMemberRole_BattleMaster The member is a battle master.
	ServerToClientGuildMemberRole_BattleMaster ServerToClientGuildMemberRole = 32
	// ServerToClientGuildMemberRole_AssistantMaster The member is the assistant guild master.
	ServerToClientGuildMemberRole_AssistantMaster ServerToClientGuildMemberRole = 64
	// ServerToClientGuildMemberRole_GuildMaster The member is the guild master.
	ServerToClientGuildMemberRole_GuildMaster ServerToClientGuildMemberRole = 128
	// ServerToClientGuildMemberRole_Undefined The character is not a member, therefore the role is undefined.
	ServerToClientGuildMemberRole_Undefined ServerToClientGuildMemberRole = 255
)

// ServerToClientGuildWarType Describes the type of the guild war.
type ServerToClientGuildWarType uint16

const (
	// ServerToClientGuildWarType_Normal A normal guild war.
	ServerToClientGuildWarType_Normal ServerToClientGuildWarType = 0
	// ServerToClientGuildWarType_Soccer A guild soccer match.
	ServerToClientGuildWarType_Soccer ServerToClientGuildWarType = 1
)

// ServerToClientGuildRelationshipType Describes the relationship type between guilds.
type ServerToClientGuildRelationshipType uint16

const (
	// ServerToClientGuildRelationshipType_Undefined The undefined relationship type.
	ServerToClientGuildRelationshipType_Undefined ServerToClientGuildRelationshipType = 0
	// ServerToClientGuildRelationshipType_Alliance The alliance relationship type.
	ServerToClientGuildRelationshipType_Alliance ServerToClientGuildRelationshipType = 1
	// ServerToClientGuildRelationshipType_Hostility The hostility relationship type.
	ServerToClientGuildRelationshipType_Hostility ServerToClientGuildRelationshipType = 2
)

// ServerToClientGuildRelationshipRequestType Describes the request type.
type ServerToClientGuildRelationshipRequestType uint16

const (
	// ServerToClientGuildRelationshipRequestType_Undefined The undefined request type.
	ServerToClientGuildRelationshipRequestType_Undefined ServerToClientGuildRelationshipRequestType = 0
	// ServerToClientGuildRelationshipRequestType_Join The join type.
	ServerToClientGuildRelationshipRequestType_Join ServerToClientGuildRelationshipRequestType = 1
	// ServerToClientGuildRelationshipRequestType_Leave The leave type.
	ServerToClientGuildRelationshipRequestType_Leave ServerToClientGuildRelationshipRequestType = 2
)

// ServerToClientCharacterStatus The status of a character.
type ServerToClientCharacterStatus uint16

const (
	// ServerToClientCharacterStatus_Normal The state of the character is normal.
	ServerToClientCharacterStatus_Normal ServerToClientCharacterStatus = 0
	// ServerToClientCharacterStatus_Banned The character is banned from the game.
	ServerToClientCharacterStatus_Banned ServerToClientCharacterStatus = 1
	// ServerToClientCharacterStatus_GameMaster The character is a game master.
	ServerToClientCharacterStatus_GameMaster ServerToClientCharacterStatus = 32
)

// ServerToClientConditionType Defines the type of the condition.
type ServerToClientConditionType uint16

const (
	// ServerToClientConditionType_None No condition is defined.
	ServerToClientConditionType_None ServerToClientConditionType = 0
	// ServerToClientConditionType_MonsterKills The condition is to kill a specified amount of specified monsters.
	ServerToClientConditionType_MonsterKills ServerToClientConditionType = 1
	// ServerToClientConditionType_Skill The condition is to learn a specified skill.
	ServerToClientConditionType_Skill ServerToClientConditionType = 2
	// ServerToClientConditionType_Item The condition is to find a specified item and to have it in the inventory.
	ServerToClientConditionType_Item ServerToClientConditionType = 4
	// ServerToClientConditionType_Level The condition is to reach the specified character level.
	ServerToClientConditionType_Level ServerToClientConditionType = 8
	// ServerToClientConditionType_ClientAction The condition is a client action. For example, this may be the completion of a tutorial.
	ServerToClientConditionType_ClientAction ServerToClientConditionType = 16
	// ServerToClientConditionType_RequestBuff The condition is to request a buff from an NPC.
	ServerToClientConditionType_RequestBuff ServerToClientConditionType = 32
	// ServerToClientConditionType_EventMapPlayerKills The condition is to kill a specific amount of players in an event.
	ServerToClientConditionType_EventMapPlayerKills ServerToClientConditionType = 64
	// ServerToClientConditionType_EventMapMonsterKills The condition is to kill a specific amount of monsters in an event.
	ServerToClientConditionType_EventMapMonsterKills ServerToClientConditionType = 65
	// ServerToClientConditionType_BloodCastleGate The condition is to destroy the blood castle gate.
	ServerToClientConditionType_BloodCastleGate ServerToClientConditionType = 66
	// ServerToClientConditionType_WinBloodCastle The condition is to win the blood castle event.
	ServerToClientConditionType_WinBloodCastle ServerToClientConditionType = 256
	// ServerToClientConditionType_WinChaosCastle The condition is to win the chaos castle.
	ServerToClientConditionType_WinChaosCastle ServerToClientConditionType = 257
	// ServerToClientConditionType_WinDevilSquare The condition is to win the devil square event.
	ServerToClientConditionType_WinDevilSquare ServerToClientConditionType = 258
	// ServerToClientConditionType_WinIllusionTemple The condition is to win the illusion temple event.
	ServerToClientConditionType_WinIllusionTemple ServerToClientConditionType = 259
	// ServerToClientConditionType_DevilSquarePoints The condition is to reach a specific amount of points in the devil square event.
	ServerToClientConditionType_DevilSquarePoints ServerToClientConditionType = 260
	// ServerToClientConditionType_Money The condition is to give a specific amount of zen.
	ServerToClientConditionType_Money ServerToClientConditionType = 261
	// ServerToClientConditionType_PvpPoints The condition is to reach a specific amount of PVP points.
	ServerToClientConditionType_PvpPoints ServerToClientConditionType = 262
	// ServerToClientConditionType_NpcTalk The condition is to talk to a specific NPC.
	ServerToClientConditionType_NpcTalk ServerToClientConditionType = 263
)

// ServerToClientConditionTypeExtended Defines the type of the condition.
type ServerToClientConditionTypeExtended uint16

const (
	// ServerToClientConditionTypeExtended_None No condition is defined.
	ServerToClientConditionTypeExtended_None ServerToClientConditionTypeExtended = 0
	// ServerToClientConditionTypeExtended_MonsterKills The condition is to kill a specified amount of specified monsters.
	ServerToClientConditionTypeExtended_MonsterKills ServerToClientConditionTypeExtended = 1
	// ServerToClientConditionTypeExtended_Skill The condition is to learn a specified skill.
	ServerToClientConditionTypeExtended_Skill ServerToClientConditionTypeExtended = 2
	// ServerToClientConditionTypeExtended_Item The condition is to find a specified item and to have it in the inventory.
	ServerToClientConditionTypeExtended_Item ServerToClientConditionTypeExtended = 3
	// ServerToClientConditionTypeExtended_Level The condition is to reach the specified character level.
	ServerToClientConditionTypeExtended_Level ServerToClientConditionTypeExtended = 4
	// ServerToClientConditionTypeExtended_ClientAction The condition is a client action. For example, this may be the completion of a tutorial.
	ServerToClientConditionTypeExtended_ClientAction ServerToClientConditionTypeExtended = 5
	// ServerToClientConditionTypeExtended_RequestBuff The condition is to request a buff from an NPC.
	ServerToClientConditionTypeExtended_RequestBuff ServerToClientConditionTypeExtended = 6
	// ServerToClientConditionTypeExtended_EventMapPlayerKills The condition is to kill a specific amount of players in an event.
	ServerToClientConditionTypeExtended_EventMapPlayerKills ServerToClientConditionTypeExtended = 7
	// ServerToClientConditionTypeExtended_EventMapMonsterKills The condition is to kill a specific amount of monsters in an event.
	ServerToClientConditionTypeExtended_EventMapMonsterKills ServerToClientConditionTypeExtended = 8
	// ServerToClientConditionTypeExtended_BloodCastleGate The condition is to destroy the blood castle gate.
	ServerToClientConditionTypeExtended_BloodCastleGate ServerToClientConditionTypeExtended = 9
	// ServerToClientConditionTypeExtended_WinBloodCastle The condition is to win the blood castle event.
	ServerToClientConditionTypeExtended_WinBloodCastle ServerToClientConditionTypeExtended = 10
	// ServerToClientConditionTypeExtended_WinChaosCastle The condition is to win the chaos castle.
	ServerToClientConditionTypeExtended_WinChaosCastle ServerToClientConditionTypeExtended = 11
	// ServerToClientConditionTypeExtended_WinDevilSquare The condition is to win the devil square event.
	ServerToClientConditionTypeExtended_WinDevilSquare ServerToClientConditionTypeExtended = 12
	// ServerToClientConditionTypeExtended_WinIllusionTemple The condition is to win the illusion temple event.
	ServerToClientConditionTypeExtended_WinIllusionTemple ServerToClientConditionTypeExtended = 13
	// ServerToClientConditionTypeExtended_DevilSquarePoints The condition is to reach a specific amount of points in the devil square event.
	ServerToClientConditionTypeExtended_DevilSquarePoints ServerToClientConditionTypeExtended = 14
	// ServerToClientConditionTypeExtended_Money The condition is to give a specific amount of zen.
	ServerToClientConditionTypeExtended_Money ServerToClientConditionTypeExtended = 15
	// ServerToClientConditionTypeExtended_PvpPoints The condition is to reach a specific amount of PVP points.
	ServerToClientConditionTypeExtended_PvpPoints ServerToClientConditionTypeExtended = 16
	// ServerToClientConditionTypeExtended_NpcTalk The condition is to talk to a specific NPC.
	ServerToClientConditionTypeExtended_NpcTalk ServerToClientConditionTypeExtended = 17
)

// ServerToClientRewardType Defines the reward which is given when the quest is completed.
type ServerToClientRewardType uint16

const (
	// ServerToClientRewardType_None No reward is defined.
	ServerToClientRewardType_None ServerToClientRewardType = 0
	// ServerToClientRewardType_Experience The reward is added experience to the character.
	ServerToClientRewardType_Experience ServerToClientRewardType = 1
	// ServerToClientRewardType_Money The reward is added money to the inventory.
	ServerToClientRewardType_Money ServerToClientRewardType = 2
	// ServerToClientRewardType_Item The reward is an item which is added to the inventory.
	ServerToClientRewardType_Item ServerToClientRewardType = 4
	// ServerToClientRewardType_GensContribution The reward is added gens contribution points.
	ServerToClientRewardType_GensContribution ServerToClientRewardType = 16
	// ServerToClientRewardType_Random The reward is random?.
	ServerToClientRewardType_Random ServerToClientRewardType = 32
)

// ServerToClientSocketOption Defines the possible socket options.
type ServerToClientSocketOption uint16

const (
	// ServerToClientSocketOption_FireAttackWizByLevelIncrease Fire((Level type)Attack/Wizardry increase +20)
	ServerToClientSocketOption_FireAttackWizByLevelIncrease ServerToClientSocketOption = 0
	// ServerToClientSocketOption_FireAttackSpeedIncrease Fire(Attack speed increase +7)
	ServerToClientSocketOption_FireAttackSpeedIncrease ServerToClientSocketOption = 1
	// ServerToClientSocketOption_FireMaxDmgIncrease Fire(Maximum attack/Wizardry increase +30)
	ServerToClientSocketOption_FireMaxDmgIncrease ServerToClientSocketOption = 2
	// ServerToClientSocketOption_FireMinDmgIncrease Fire(Minimum attack/Wizardry increase +20)
	ServerToClientSocketOption_FireMinDmgIncrease ServerToClientSocketOption = 3
	// ServerToClientSocketOption_FireAttackWizIncrease Fire(Attack/Wizardry increase +20)
	ServerToClientSocketOption_FireAttackWizIncrease ServerToClientSocketOption = 4
	// ServerToClientSocketOption_FireAgCostDecrease Fire(AG cost decrease +40)
	ServerToClientSocketOption_FireAgCostDecrease ServerToClientSocketOption = 5
	// ServerToClientSocketOption_WaterBlockRateIncrease Water(Block rating increase +10)
	ServerToClientSocketOption_WaterBlockRateIncrease ServerToClientSocketOption = 10
	// ServerToClientSocketOption_WaterDefenseIncrease Water(Defense increase +30)
	ServerToClientSocketOption_WaterDefenseIncrease ServerToClientSocketOption = 11
	// ServerToClientSocketOption_WaterShieldProtectionIncrease Water(Shield protection increase +7)
	ServerToClientSocketOption_WaterShieldProtectionIncrease ServerToClientSocketOption = 12
	// ServerToClientSocketOption_WaterDamageReduction4 Water(Damage reduction +4)
	ServerToClientSocketOption_WaterDamageReduction4 ServerToClientSocketOption = 13
	// ServerToClientSocketOption_WaterDamageReduction5 Water(Damage reduction +5)
	ServerToClientSocketOption_WaterDamageReduction5 ServerToClientSocketOption = 14
	// ServerToClientSocketOption_IceLifeIncrease Ice(Monster destruction for the Life increase +8)
	ServerToClientSocketOption_IceLifeIncrease ServerToClientSocketOption = 16
	// ServerToClientSocketOption_IceManaIncrease Ice(Monster destruction for the Mana increase +8)
	ServerToClientSocketOption_IceManaIncrease ServerToClientSocketOption = 17
	// ServerToClientSocketOption_IceSkillAttackIncrease Ice(Skill attack increase +37)
	ServerToClientSocketOption_IceSkillAttackIncrease ServerToClientSocketOption = 18
	// ServerToClientSocketOption_IceAttackRateIncrease Ice(Attack rating increase +25)
	ServerToClientSocketOption_IceAttackRateIncrease ServerToClientSocketOption = 19
	// ServerToClientSocketOption_IceDurabilityIncrease Ice(Item durability increase +30)
	ServerToClientSocketOption_IceDurabilityIncrease ServerToClientSocketOption = 20
	// ServerToClientSocketOption_WindAutoLifeRecoveryIncrease Wind(Automatic Life recovery increase +8)
	ServerToClientSocketOption_WindAutoLifeRecoveryIncrease ServerToClientSocketOption = 21
	// ServerToClientSocketOption_WindMaxHealthIncrease Wind(Maximum Life increase +4)
	ServerToClientSocketOption_WindMaxHealthIncrease ServerToClientSocketOption = 22
	// ServerToClientSocketOption_WindMaxManaIncrease Wind(Maximum Mana increase +4)
	ServerToClientSocketOption_WindMaxManaIncrease ServerToClientSocketOption = 23
	// ServerToClientSocketOption_WindAutoManaRecoverIncrease Wind(Automatic Mana recovery increase +7)
	ServerToClientSocketOption_WindAutoManaRecoverIncrease ServerToClientSocketOption = 24
	// ServerToClientSocketOption_WindMaxAgIncrease Wind(Maximum AG increase +25)
	ServerToClientSocketOption_WindMaxAgIncrease ServerToClientSocketOption = 25
	// ServerToClientSocketOption_WindAutoAgRecoverIncrease Wind(AG value increase +26)
	ServerToClientSocketOption_WindAutoAgRecoverIncrease ServerToClientSocketOption = 26
	// ServerToClientSocketOption_LightningExcDmgIncrease Lightning(Excellent damage increase +15)
	ServerToClientSocketOption_LightningExcDmgIncrease ServerToClientSocketOption = 29
	// ServerToClientSocketOption_LightningExcDmgRateIncrease Lightning(Excellent damage rate increase +10)
	ServerToClientSocketOption_LightningExcDmgRateIncrease ServerToClientSocketOption = 30
	// ServerToClientSocketOption_LightningCritDmgIncrease Lightning(Critical damage increase +30)
	ServerToClientSocketOption_LightningCritDmgIncrease ServerToClientSocketOption = 31
	// ServerToClientSocketOption_LightningCritDmgRateIncrease Lightning(Critical damage rate increase +8)
	ServerToClientSocketOption_LightningCritDmgRateIncrease ServerToClientSocketOption = 32
	// ServerToClientSocketOption_EarthHealhIncrease Earth(Health increase +30)
	ServerToClientSocketOption_EarthHealhIncrease ServerToClientSocketOption = 36
	// ServerToClientSocketOption_EmptySocket Empty Socket
	ServerToClientSocketOption_EmptySocket ServerToClientSocketOption = 254
	// ServerToClientSocketOption_NoSocket No Socket
	ServerToClientSocketOption_NoSocket ServerToClientSocketOption = 255
)

// ServerToClientCharacterCreationUnlockFlags The flags to unlock the specified character classes for the creation of new characters.
type ServerToClientCharacterCreationUnlockFlags uint16

const (
	// ServerToClientCharacterCreationUnlockFlags_None No unlocked class.
	ServerToClientCharacterCreationUnlockFlags_None ServerToClientCharacterCreationUnlockFlags = 0
	// ServerToClientCharacterCreationUnlockFlags_Summoner Unlocks the summoner class.
	ServerToClientCharacterCreationUnlockFlags_Summoner ServerToClientCharacterCreationUnlockFlags = 1
	// ServerToClientCharacterCreationUnlockFlags_DarkLord Unlocks the dark lord class.
	ServerToClientCharacterCreationUnlockFlags_DarkLord ServerToClientCharacterCreationUnlockFlags = 2
	// ServerToClientCharacterCreationUnlockFlags_MagicGladiator Unlocks the magic gladiator class.
	ServerToClientCharacterCreationUnlockFlags_MagicGladiator ServerToClientCharacterCreationUnlockFlags = 4
	// ServerToClientCharacterCreationUnlockFlags_RageFighter Unlocks the rage fighter class.
	ServerToClientCharacterCreationUnlockFlags_RageFighter ServerToClientCharacterCreationUnlockFlags = 8
)

// ServerToClientDamageKind Defines the kind of the damage.
type ServerToClientDamageKind uint16

const (
	// ServerToClientDamageKind_NormalRed Red color, used by normal damage.
	ServerToClientDamageKind_NormalRed ServerToClientDamageKind = 0
	// ServerToClientDamageKind_IgnoreDefenseCyan Cyan color, usually used by ignore defense damage.
	ServerToClientDamageKind_IgnoreDefenseCyan ServerToClientDamageKind = 1
	// ServerToClientDamageKind_ExcellentLightGreen Light green color, usually used by excellent damage.
	ServerToClientDamageKind_ExcellentLightGreen ServerToClientDamageKind = 2
	// ServerToClientDamageKind_CriticalBlue Blue color, usually used by critical damage.
	ServerToClientDamageKind_CriticalBlue ServerToClientDamageKind = 3
	// ServerToClientDamageKind_ReflectedLightPink Light pink color, usually used by reflected damage.
	ServerToClientDamageKind_ReflectedLightPink ServerToClientDamageKind = 4
	// ServerToClientDamageKind_PoisonDarkGreen Dark green color, usually used by poison damage.
	ServerToClientDamageKind_PoisonDarkGreen ServerToClientDamageKind = 5
	// ServerToClientDamageKind_DarkPink Dark pink color.
	ServerToClientDamageKind_DarkPink ServerToClientDamageKind = 6
	// ServerToClientDamageKind_White White color.
	ServerToClientDamageKind_White ServerToClientDamageKind = 7
)

// ServerToClientChatCommandParameterType The kind of value which a chat command parameter expects.
type ServerToClientChatCommandParameterType uint16

const (
	// ServerToClientChatCommandParameterType_Text The parameter expects a text.
	ServerToClientChatCommandParameterType_Text ServerToClientChatCommandParameterType = 0
	// ServerToClientChatCommandParameterType_Number The parameter expects a number.
	ServerToClientChatCommandParameterType_Number ServerToClientChatCommandParameterType = 1
	// ServerToClientChatCommandParameterType_Boolean The parameter expects a 0 or a 1.
	ServerToClientChatCommandParameterType_Boolean ServerToClientChatCommandParameterType = 2
)

// TradeButtonState The state of the trade button.
type TradeButtonState uint16

const (
	// TradeButtonState_Unchecked Trade button is not pressed. It means that the trade is not yet accepted by the trader.
	TradeButtonState_Unchecked TradeButtonState = 0
	// TradeButtonState_Checked Trade Button is pressed. It means that the trade is accepted by the trader.
	TradeButtonState_Checked TradeButtonState = 1
	// TradeButtonState_Red This state is only sent to the client. After some seconds the client is changing back to normal Unchecked.
	TradeButtonState_Red TradeButtonState = 2
)

// StorageType Describes the type of storage.
type StorageType uint16

const (
	// StorageType_Inventory The inventory of the player.
	StorageType_Inventory StorageType = 0
	// StorageType_Vault The vault of the player.
	StorageType_Vault StorageType = 1
	// StorageType_TradeOwn The own trading storage.
	StorageType_TradeOwn StorageType = 2
	// StorageType_TradeOther The trading storage of the other player.
	StorageType_TradeOther StorageType = 3
	// StorageType_Crafting The crafting storage of the player.
	StorageType_Crafting StorageType = 4
	// StorageType_PersonalShop The shop storage of another player.
	StorageType_PersonalShop StorageType = 5
	// StorageType_NpcShop The shop storage of an NPC (merchant).
	StorageType_NpcShop StorageType = 6
	// StorageType_InventoryPetSlot The inventory slot of the pet. That's used when a pet leveled up.
	StorageType_InventoryPetSlot StorageType = 254
)

// PetType Describes the type of pet.
type PetType uint16

const (
	// PetType_DarkRaven The dark raven pet.
	PetType_DarkRaven PetType = 0
	// PetType_DarkHorse The dark horse pet.
	PetType_DarkHorse PetType = 1
)

// PetCommandMode Describes the pet command mode.
type PetCommandMode uint16

const (
	// PetCommandMode_Normal The pet is in a normal mode, where it doesn't attack.
	PetCommandMode_Normal PetCommandMode = 0
	// PetCommandMode_AttackRandom The pet attacks random targets.
	PetCommandMode_AttackRandom PetCommandMode = 1
	// PetCommandMode_AttackWithOwner The pet attacks the same targets as the owner.
	PetCommandMode_AttackWithOwner PetCommandMode = 2
	// PetCommandMode_AttackTarget The pet attacks a specific target until it's dead.
	PetCommandMode_AttackTarget PetCommandMode = 3
)

// GensType Describes the gens type.
type GensType uint16

const (
	// GensType_Undefined The undefined gens type.
	GensType_Undefined GensType = 0
	// GensType_Duprian The Duprian gens.
	GensType_Duprian GensType = 1
	// GensType_Vanert The Vanert gens.
	GensType_Vanert GensType = 2
)

// GuildRelationshipType Describes the relationship type between guilds.
type GuildRelationshipType uint16

const (
	// GuildRelationshipType_Undefined The undefined relationship type.
	GuildRelationshipType_Undefined GuildRelationshipType = 0
	// GuildRelationshipType_Alliance The alliance relationship type.
	GuildRelationshipType_Alliance GuildRelationshipType = 1
	// GuildRelationshipType_Hostility The hostility relationship type.
	GuildRelationshipType_Hostility GuildRelationshipType = 2
)

// GuildRequestType Describes the request type.
type GuildRequestType uint16

const (
	// GuildRequestType_Undefined The undefined request type.
	GuildRequestType_Undefined GuildRequestType = 0
	// GuildRequestType_Join The join type.
	GuildRequestType_Join GuildRequestType = 1
	// GuildRequestType_Leave The leave type.
	GuildRequestType_Leave GuildRequestType = 2
)

// FruitUsage Defines how the fruit is used. Only applies, if the the item is a fruit.
type FruitUsage uint16

const (
	// FruitUsage_AddPoints Adds 1~3 stat points to the character.
	FruitUsage_AddPoints FruitUsage = 0
	// FruitUsage_RemovePoints Removes 1~9 stat points from the character.
	FruitUsage_RemovePoints FruitUsage = 1
)

// VaultMoneyMoveDirection Defines the moving direction of money between inventory and vault.
type VaultMoneyMoveDirection uint16

const (
	// VaultMoneyMoveDirection_InventoryToVault The money is moved from the inventory to the vault.
	VaultMoneyMoveDirection_InventoryToVault VaultMoneyMoveDirection = 0
	// VaultMoneyMoveDirection_VaultToInventory The money is moved from the vault to the inventory.
	VaultMoneyMoveDirection_VaultToInventory VaultMoneyMoveDirection = 1
)

// MixType Describes what kind of operation is requested.
type MixType uint16

const (
	// MixType_Mix The player wants to mix single jewels into a bundle.
	MixType_Mix MixType = 0
	// MixType_Unmix The player wants to disband a bundle into single jewels.
	MixType_Unmix MixType = 1
)

// StackSize Describes the size of a mixed stack.
type StackSize uint16

const (
	// StackSize_Ten A stack of 10 items.
	StackSize_Ten StackSize = 0
	// StackSize_Twenty A stack of 20 items.
	StackSize_Twenty StackSize = 1
	// StackSize_Thirty A stack of 30 items.
	StackSize_Thirty StackSize = 2
)

// ItemType Describes the type of item which is mixed or unmixed.
type ItemType uint16

const (
	// ItemType_JewelOfBless Jewel of Bless.
	ItemType_JewelOfBless ItemType = 0
	// ItemType_JewelOfSoul Jewel of Soul.
	ItemType_JewelOfSoul ItemType = 1
	// ItemType_JewelOfLife Jewel of Life.
	ItemType_JewelOfLife ItemType = 2
	// ItemType_JewelOfCreation Jewel of Creation.
	ItemType_JewelOfCreation ItemType = 3
	// ItemType_JewelOfGuardian Jewel of Guardian.
	ItemType_JewelOfGuardian ItemType = 4
	// ItemType_Gemstone The gemstone.
	ItemType_Gemstone ItemType = 5
	// ItemType_JewelOfHarmony Jewel of Harmony.
	ItemType_JewelOfHarmony ItemType = 6
	// ItemType_JewelOfChaos Jewel of Chaos.
	ItemType_JewelOfChaos ItemType = 7
	// ItemType_LowerRefineStone Lower refine stone.
	ItemType_LowerRefineStone ItemType = 8
	// ItemType_HigherRefineStone Higher refine stone.
	ItemType_HigherRefineStone ItemType = 9
)

// ChaosMachineMixType This enum describes the possible chaos machine mix type identifiers.
type ChaosMachineMixType uint16

const (
	// ChaosMachineMixType_ChaosWeapon Mixes the items to a chaos weapon.
	ChaosMachineMixType_ChaosWeapon ChaosMachineMixType = 1
	// ChaosMachineMixType_UpgradeItemLevelTo10 Upgrades an item to level 10.
	ChaosMachineMixType_UpgradeItemLevelTo10 ChaosMachineMixType = 3
	// ChaosMachineMixType_UpgradeItemLevelTo11 Upgrades an item to level 11.
	ChaosMachineMixType_UpgradeItemLevelTo11 ChaosMachineMixType = 4
	// ChaosMachineMixType_UpgradeItemLevelTo12 Upgrades an item to level 12.
	ChaosMachineMixType_UpgradeItemLevelTo12 ChaosMachineMixType = 22
	// ChaosMachineMixType_UpgradeItemLevelTo13 Upgrades an item to level 13.
	ChaosMachineMixType_UpgradeItemLevelTo13 ChaosMachineMixType = 23
	// ChaosMachineMixType_UpgradeItemLevelTo14 Upgrades an item to level 14.
	ChaosMachineMixType_UpgradeItemLevelTo14 ChaosMachineMixType = 49
	// ChaosMachineMixType_UpgradeItemLevelTo15 Upgrades an item to level 15.
	ChaosMachineMixType_UpgradeItemLevelTo15 ChaosMachineMixType = 50
	// ChaosMachineMixType_FruitCreation Mixes the items to a fruit.
	ChaosMachineMixType_FruitCreation ChaosMachineMixType = 6
	// ChaosMachineMixType_GemstoneRefinery Refines a gemstone to a jewel of harmony.
	ChaosMachineMixType_GemstoneRefinery ChaosMachineMixType = 41
	// ChaosMachineMixType_PotionOfBless Refines a Jewel Of Bless to a stack of potions of bless.
	ChaosMachineMixType_PotionOfBless ChaosMachineMixType = 15
	// ChaosMachineMixType_PotionOfSoul Refines a Jewel Of Soul to a stack of potions of bless.
	ChaosMachineMixType_PotionOfSoul ChaosMachineMixType = 16
)

// QuestProceedAction Describes how to proceed with the specified quest.
type QuestProceedAction uint16

const (
	// QuestProceedAction_Undefined Undefined action.
	QuestProceedAction_Undefined QuestProceedAction = 0
	// QuestProceedAction_AcceptQuest The quest is accepted and started.
	QuestProceedAction_AcceptQuest QuestProceedAction = 1
	// QuestProceedAction_RefuseQuest The quest is refused and not started.
	QuestProceedAction_RefuseQuest QuestProceedAction = 2
)
