// Code generated by muprotogen from MUnique.OpenMU.Network.Packets 0.9.10; DO NOT EDIT.

package c2s

// RouteKey 是包分发表的键，对应线上帧头。
type RouteKey struct {
	Header byte
	Code   byte
	HasSub bool
	Sub    byte
}

// PacketInfo 描述一个已注册包的静态信息。
type PacketInfo struct {
	Name      string
	Direction string
	Fixed     bool
	Length    int
}

type routeEntry struct {
	Key  RouteKey
	Info PacketInfo
}

var routes = []routeEntry{
	{RouteKey{0xC1, 0x00, false, 0x00}, PacketInfo{"PublicChatMessage", "ClientToServer", false, 0}},
	{RouteKey{0xC1, 0x02, false, 0x00}, PacketInfo{"WhisperMessage", "ClientToServer", false, 0}},
	{RouteKey{0xC1, 0x10, false, 0x00}, PacketInfo{"WalkRequest075", "ClientToServer", false, 0}},
	{RouteKey{0xC1, 0x11, false, 0x00}, PacketInfo{"HitRequest", "ClientToServer", true, 7}},
	{RouteKey{0xC1, 0x15, false, 0x00}, PacketInfo{"InstantMoveRequest", "ClientToServer", true, 5}},
	{RouteKey{0xC1, 0x18, false, 0x00}, PacketInfo{"AnimationRequest", "ClientToServer", true, 5}},
	{RouteKey{0xC1, 0x19, false, 0x00}, PacketInfo{"TargetedSkill075", "ClientToServer", true, 6}},
	{RouteKey{0xC1, 0x1B, false, 0x00}, PacketInfo{"MagicEffectCancelRequest", "ClientToServer", true, 7}},
	{RouteKey{0xC1, 0x1D, false, 0x00}, PacketInfo{"AreaSkillHit075", "ClientToServer", false, 0}},
	{RouteKey{0xC1, 0x1E, false, 0x00}, PacketInfo{"AreaSkill075", "ClientToServer", true, 7}},
	{RouteKey{0xC1, 0x22, false, 0x00}, PacketInfo{"PickupItemRequest075", "ClientToServer", true, 5}},
	{RouteKey{0xC1, 0x26, false, 0x00}, PacketInfo{"ConsumeItemRequest075", "ClientToServer", true, 5}},
	{RouteKey{0xC1, 0x31, false, 0x00}, PacketInfo{"CloseNpcRequest", "ClientToServer", true, 3}},
	{RouteKey{0xC1, 0x34, false, 0x00}, PacketInfo{"RepairItemRequest", "ClientToServer", true, 5}},
	{RouteKey{0xC1, 0x37, false, 0x00}, PacketInfo{"TradeRequestResponse", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0x3A, false, 0x00}, PacketInfo{"SetTradeMoney", "ClientToServer", true, 8}},
	{RouteKey{0xC1, 0x3C, false, 0x00}, PacketInfo{"TradeButtonStateChange", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0x3D, false, 0x00}, PacketInfo{"TradeCancel", "ClientToServer", true, 3}},
	{RouteKey{0xC1, 0x40, false, 0x00}, PacketInfo{"PartyInviteRequest", "ClientToServer", true, 5}},
	{RouteKey{0xC1, 0x41, false, 0x00}, PacketInfo{"PartyInviteResponse", "ClientToServer", true, 6}},
	{RouteKey{0xC1, 0x42, false, 0x00}, PacketInfo{"PartyListRequest", "ClientToServer", true, 3}},
	{RouteKey{0xC1, 0x43, false, 0x00}, PacketInfo{"PartyPlayerKickRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0x4B, false, 0x00}, PacketInfo{"RageAttackRangeRequest", "ClientToServer", true, 7}},
	{RouteKey{0xC1, 0x50, false, 0x00}, PacketInfo{"GuildJoinRequest", "ClientToServer", true, 5}},
	{RouteKey{0xC1, 0x51, false, 0x00}, PacketInfo{"GuildJoinResponse", "ClientToServer", true, 6}},
	{RouteKey{0xC1, 0x52, false, 0x00}, PacketInfo{"GuildListRequest", "ClientToServer", true, 3}},
	{RouteKey{0xC1, 0x53, false, 0x00}, PacketInfo{"GuildKickPlayerRequest", "ClientToServer", false, 0}},
	{RouteKey{0xC1, 0x54, false, 0x00}, PacketInfo{"GuildMasterAnswer", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0x55, false, 0x00}, PacketInfo{"GuildCreateRequest", "ClientToServer", true, 44}},
	{RouteKey{0xC1, 0x55, false, 0x00}, PacketInfo{"GuildCreateRequest075", "ClientToServer", true, 43}},
	{RouteKey{0xC1, 0x57, false, 0x00}, PacketInfo{"CancelGuildCreation", "ClientToServer", true, 3}},
	{RouteKey{0xC1, 0x61, false, 0x00}, PacketInfo{"GuildWarResponse", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0x66, false, 0x00}, PacketInfo{"GuildInfoRequest", "ClientToServer", true, 8}},
	{RouteKey{0xC1, 0x71, false, 0x00}, PacketInfo{"PingResponse", "ClientToServer", true, 3}},
	{RouteKey{0xC1, 0x81, false, 0x00}, PacketInfo{"VaultMoveMoneyRequest", "ClientToServer", true, 8}},
	{RouteKey{0xC1, 0x82, false, 0x00}, PacketInfo{"VaultClosed", "ClientToServer", true, 3}},
	{RouteKey{0xC1, 0x83, true, 0x00}, PacketInfo{"UnlockVault", "ClientToServer", true, 7}},
	{RouteKey{0xC1, 0x83, true, 0x01}, PacketInfo{"SetVaultPin", "ClientToServer", true, 27}},
	{RouteKey{0xC1, 0x83, true, 0x02}, PacketInfo{"RemoveVaultPin", "ClientToServer", true, 27}},
	{RouteKey{0xC1, 0x86, false, 0x00}, PacketInfo{"ChaosMachineMixRequest", "ClientToServer", true, 5}},
	{RouteKey{0xC1, 0x87, false, 0x00}, PacketInfo{"CraftingDialogCloseRequest", "ClientToServer", true, 3}},
	{RouteKey{0xC1, 0x8E, true, 0x02}, PacketInfo{"WarpCommandRequest", "ClientToServer", true, 10}},
	{RouteKey{0xC1, 0x90, false, 0x00}, PacketInfo{"DevilSquareEnterRequest", "ClientToServer", true, 5}},
	{RouteKey{0xC1, 0x91, false, 0x00}, PacketInfo{"MiniGameOpeningStateRequest", "ClientToServer", true, 5}},
	{RouteKey{0xC1, 0x95, false, 0x00}, PacketInfo{"EventChipRegistrationRequest", "ClientToServer", true, 5}},
	{RouteKey{0xC1, 0x96, false, 0x00}, PacketInfo{"MutoNumberRequest", "ClientToServer", true, 3}},
	{RouteKey{0xC1, 0x97, false, 0x00}, PacketInfo{"EventChipExitDialog", "ClientToServer", true, 3}},
	{RouteKey{0xC1, 0x98, false, 0x00}, PacketInfo{"EventChipExchangeRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0x9A, false, 0x00}, PacketInfo{"BloodCastleEnterRequest", "ClientToServer", true, 5}},
	{RouteKey{0xC1, 0x9D, false, 0x00}, PacketInfo{"LuckyNumberRequest", "ClientToServer", true, 18}},
	{RouteKey{0xC1, 0x9F, false, 0x00}, PacketInfo{"MiniGameEventCountRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xA0, false, 0x00}, PacketInfo{"LegacyQuestStateRequest", "ClientToServer", true, 3}},
	{RouteKey{0xC1, 0xA2, false, 0x00}, PacketInfo{"LegacyQuestStateSetRequest", "ClientToServer", true, 5}},
	{RouteKey{0xC1, 0xA7, false, 0x00}, PacketInfo{"PetCommandRequest", "ClientToServer", true, 7}},
	{RouteKey{0xC1, 0xA9, false, 0x00}, PacketInfo{"PetInfoRequest", "ClientToServer", true, 6}},
	{RouteKey{0xC1, 0xAF, true, 0x01}, PacketInfo{"ChaosCastleEnterRequest", "ClientToServer", true, 6}},
	{RouteKey{0xC1, 0xAF, true, 0x02}, PacketInfo{"ChaosCastlePositionSet", "ClientToServer", true, 6}},
	{RouteKey{0xC1, 0xB2, true, 0x00}, PacketInfo{"CastleSiegeStatusRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xB2, true, 0x01}, PacketInfo{"CastleSiegeRegistrationRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xB2, true, 0x02}, PacketInfo{"CastleSiegeUnregisterRequest", "ClientToServer", true, 5}},
	{RouteKey{0xC1, 0xB2, true, 0x03}, PacketInfo{"CastleSiegeRegistrationStateRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xB2, true, 0x04}, PacketInfo{"CastleSiegeMarkRegistration", "ClientToServer", true, 5}},
	{RouteKey{0xC1, 0xB2, true, 0x05}, PacketInfo{"CastleSiegeDefenseBuyRequest", "ClientToServer", true, 12}},
	{RouteKey{0xC1, 0xB2, true, 0x06}, PacketInfo{"CastleSiegeDefenseRepairRequest", "ClientToServer", true, 12}},
	{RouteKey{0xC1, 0xB2, true, 0x07}, PacketInfo{"CastleSiegeDefenseUpgradeRequest", "ClientToServer", true, 20}},
	{RouteKey{0xC1, 0xB2, true, 0x08}, PacketInfo{"CastleSiegeTaxInfoRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xB2, true, 0x09}, PacketInfo{"CastleSiegeTaxChangeRequest", "ClientToServer", true, 9}},
	{RouteKey{0xC1, 0xB2, true, 0x10}, PacketInfo{"CastleSiegeTaxMoneyWithdraw", "ClientToServer", true, 8}},
	{RouteKey{0xC1, 0xB2, true, 0x12}, PacketInfo{"ToggleCastleGateRequest", "ClientToServer", true, 7}},
	{RouteKey{0xC1, 0xB2, true, 0x1D}, PacketInfo{"CastleGuildCommand", "ClientToServer", true, 8}},
	{RouteKey{0xC1, 0xB2, true, 0x1F}, PacketInfo{"CastleSiegeHuntingZoneEntranceSetting", "ClientToServer", true, 5}},
	{RouteKey{0xC1, 0xB3, true, 0x01}, PacketInfo{"CastleSiegeGateListRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xB3, true, 0x02}, PacketInfo{"CastleSiegeStatueListRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xB4, false, 0x00}, PacketInfo{"CastleSiegeRegisteredGuildsListRequest", "ClientToServer", true, 3}},
	{RouteKey{0xC1, 0xB5, false, 0x00}, PacketInfo{"CastleOwnerListRequest", "ClientToServer", true, 3}},
	{RouteKey{0xC1, 0xB7, true, 0x01}, PacketInfo{"FireCatapultRequest", "ClientToServer", true, 7}},
	{RouteKey{0xC1, 0xB7, true, 0x04}, PacketInfo{"WeaponExplosionRequest", "ClientToServer", true, 6}},
	{RouteKey{0xC1, 0xB9, true, 0x02}, PacketInfo{"GuildLogoOfCastleOwnerRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xB9, true, 0x05}, PacketInfo{"CastleSiegeHuntingZoneEnterRequest", "ClientToServer", true, 8}},
	{RouteKey{0xC1, 0xBC, false, 0x00}, PacketInfo{"LahapJewelMixRequest", "ClientToServer", true, 7}},
	{RouteKey{0xC1, 0xBD, true, 0x00}, PacketInfo{"CrywolfInfoRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xBD, true, 0x03}, PacketInfo{"CrywolfContractRequest", "ClientToServer", true, 6}},
	{RouteKey{0xC1, 0xBD, true, 0x09}, PacketInfo{"CrywolfChaosRateBenefitRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xBF, true, 0x00}, PacketInfo{"IllusionTempleEnterRequest", "ClientToServer", true, 6}},
	{RouteKey{0xC1, 0xBF, true, 0x02}, PacketInfo{"IllusionTempleSkillRequest", "ClientToServer", true, 8}},
	{RouteKey{0xC1, 0xBF, true, 0x05}, PacketInfo{"IllusionTempleRewardRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xBF, true, 0x0B}, PacketInfo{"LuckyCoinCountRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xBF, true, 0x0C}, PacketInfo{"LuckyCoinRegistrationRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xBF, true, 0x0D}, PacketInfo{"LuckyCoinExchangeRequest", "ClientToServer", true, 8}},
	{RouteKey{0xC1, 0xBF, true, 0x0E}, PacketInfo{"DoppelgangerEnterRequest", "ClientToServer", true, 5}},
	{RouteKey{0xC1, 0xBF, true, 0x17}, PacketInfo{"EnterMarketPlaceRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xBF, true, 0x51}, PacketInfo{"MuHelperStatusChangeRequest", "ClientToServer", true, 5}},
	{RouteKey{0xC1, 0xC0, false, 0x00}, PacketInfo{"FriendListRequest", "ClientToServer", true, 3}},
	{RouteKey{0xC1, 0xC1, false, 0x00}, PacketInfo{"FriendAddRequest", "ClientToServer", true, 13}},
	{RouteKey{0xC1, 0xC2, false, 0x00}, PacketInfo{"FriendAddResponse", "ClientToServer", true, 14}},
	{RouteKey{0xC1, 0xC3, false, 0x00}, PacketInfo{"FriendDelete", "ClientToServer", true, 13}},
	{RouteKey{0xC1, 0xC4, false, 0x00}, PacketInfo{"SetFriendOnlineState", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xC7, false, 0x00}, PacketInfo{"LetterReadRequest", "ClientToServer", true, 6}},
	{RouteKey{0xC1, 0xC8, false, 0x00}, PacketInfo{"LetterDeleteRequest", "ClientToServer", true, 6}},
	{RouteKey{0xC1, 0xC9, false, 0x00}, PacketInfo{"LetterListRequest", "ClientToServer", true, 3}},
	{RouteKey{0xC1, 0xCA, false, 0x00}, PacketInfo{"ChatRoomCreateRequest", "ClientToServer", true, 13}},
	{RouteKey{0xC1, 0xCB, false, 0x00}, PacketInfo{"ChatRoomInvitationRequest", "ClientToServer", true, 19}},
	{RouteKey{0xC1, 0xD0, true, 0x03}, PacketInfo{"WhiteAngelItemRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xD0, true, 0x07}, PacketInfo{"EnterOnWerewolfRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xD0, true, 0x08}, PacketInfo{"EnterOnGatekeeperRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xD0, true, 0x09}, PacketInfo{"LeoHelperItemRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xD0, true, 0x0A}, PacketInfo{"MoveToDeviasBySnowmanRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xD0, true, 0x10}, PacketInfo{"SantaClausItemRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xD1, true, 0x00}, PacketInfo{"KanturuInfoRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xD1, true, 0x01}, PacketInfo{"KanturuEnterRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xD1, true, 0x10}, PacketInfo{"RaklionStateInfoRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xD2, true, 0x01}, PacketInfo{"CashShopPointInfoRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xD2, true, 0x02}, PacketInfo{"CashShopOpenState", "ClientToServer", true, 5}},
	{RouteKey{0xC1, 0xD2, true, 0x03}, PacketInfo{"CashShopItemBuyRequest", "ClientToServer", true, 23}},
	{RouteKey{0xC1, 0xD2, true, 0x04}, PacketInfo{"CashShopItemGiftRequest", "ClientToServer", true, 234}},
	{RouteKey{0xC1, 0xD2, true, 0x05}, PacketInfo{"CashShopStorageListRequest", "ClientToServer", true, 10}},
	{RouteKey{0xC1, 0xD2, true, 0x0A}, PacketInfo{"CashShopDeleteStorageItemRequest", "ClientToServer", true, 234}},
	{RouteKey{0xC1, 0xD2, true, 0x0B}, PacketInfo{"CashShopStorageItemConsumeRequest", "ClientToServer", true, 15}},
	{RouteKey{0xC1, 0xD2, true, 0x13}, PacketInfo{"CashShopEventItemListRequest", "ClientToServer", true, 8}},
	{RouteKey{0xC1, 0xD4, false, 0x00}, PacketInfo{"WalkRequest", "ClientToServer", false, 0}},
	{RouteKey{0xC1, 0xE1, false, 0x00}, PacketInfo{"GuildRoleAssignRequest", "ClientToServer", true, 15}},
	{RouteKey{0xC1, 0xE2, false, 0x00}, PacketInfo{"GuildTypeChangeRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xE5, false, 0x00}, PacketInfo{"GuildRelationshipChangeRequest", "ClientToServer", true, 7}},
	{RouteKey{0xC1, 0xE6, false, 0x00}, PacketInfo{"GuildRelationshipChangeResponse", "ClientToServer", true, 8}},
	{RouteKey{0xC1, 0xE9, false, 0x00}, PacketInfo{"RequestAllianceList", "ClientToServer", true, 3}},
	{RouteKey{0xC1, 0xEB, true, 0x01}, PacketInfo{"RemoveAllianceGuildRequest", "ClientToServer", true, 12}},
	{RouteKey{0xC1, 0xF2, true, 0x00}, PacketInfo{"ResetCharacterPointRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xF3, true, 0x00}, PacketInfo{"RequestCharacterList", "ClientToServer", true, 5}},
	{RouteKey{0xC1, 0xF3, true, 0x01}, PacketInfo{"CreateCharacter", "ClientToServer", true, 15}},
	{RouteKey{0xC1, 0xF3, true, 0x02}, PacketInfo{"DeleteCharacter", "ClientToServer", true, 24}},
	{RouteKey{0xC1, 0xF3, true, 0x03}, PacketInfo{"SelectCharacter", "ClientToServer", true, 14}},
	{RouteKey{0xC1, 0xF3, true, 0x06}, PacketInfo{"IncreaseCharacterStatPoint", "ClientToServer", true, 5}},
	{RouteKey{0xC1, 0xF3, true, 0x12}, PacketInfo{"ClientReadyAfterMapChange", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xF3, true, 0x15}, PacketInfo{"FocusCharacter", "ClientToServer", true, 14}},
	{RouteKey{0xC1, 0xF3, true, 0x30}, PacketInfo{"SaveKeyConfiguration", "ClientToServer", false, 0}},
	{RouteKey{0xC1, 0xF3, true, 0x52}, PacketInfo{"AddMasterSkillPoint", "ClientToServer", true, 6}},
	{RouteKey{0xC1, 0xF5, true, 0x00}, PacketInfo{"ChatCommandListRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xF6, true, 0x0A}, PacketInfo{"QuestSelectRequest", "ClientToServer", true, 9}},
	{RouteKey{0xC1, 0xF6, true, 0x0B}, PacketInfo{"QuestProceedRequest", "ClientToServer", true, 9}},
	{RouteKey{0xC1, 0xF6, true, 0x0D}, PacketInfo{"QuestCompletionRequest", "ClientToServer", true, 8}},
	{RouteKey{0xC1, 0xF6, true, 0x0F}, PacketInfo{"QuestCancelRequest", "ClientToServer", true, 8}},
	{RouteKey{0xC1, 0xF6, true, 0x10}, PacketInfo{"QuestClientActionRequest", "ClientToServer", true, 8}},
	{RouteKey{0xC1, 0xF6, true, 0x1A}, PacketInfo{"ActiveQuestListRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xF6, true, 0x1B}, PacketInfo{"QuestStateRequest", "ClientToServer", true, 8}},
	{RouteKey{0xC1, 0xF6, true, 0x21}, PacketInfo{"EventQuestStateListRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xF6, true, 0x30}, PacketInfo{"AvailableQuestsRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xF6, true, 0x31}, PacketInfo{"NpcBuffRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xF7, true, 0x01}, PacketInfo{"EnterEmpireGuardianEvent", "ClientToServer", true, 5}},
	{RouteKey{0xC1, 0xF8, true, 0x01}, PacketInfo{"GensJoinRequest", "ClientToServer", true, 5}},
	{RouteKey{0xC1, 0xF8, true, 0x03}, PacketInfo{"GensLeaveRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC1, 0xF8, true, 0x09}, PacketInfo{"GensRewardRequest", "ClientToServer", true, 5}},
	{RouteKey{0xC1, 0xF8, true, 0x0B}, PacketInfo{"GensRankingRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC2, 0xAE, false, 0x00}, PacketInfo{"MuHelperSaveDataRequest", "ClientToServer", true, 261}},
	{RouteKey{0xC3, 0x03, false, 0x00}, PacketInfo{"ChecksumResponse", "ClientToServer", true, 8}},
	{RouteKey{0xC3, 0x0E, true, 0x00}, PacketInfo{"Ping", "ClientToServer", true, 12}},
	{RouteKey{0xC3, 0x19, false, 0x00}, PacketInfo{"TargetedSkill", "ClientToServer", true, 7}},
	{RouteKey{0xC3, 0x19, false, 0x00}, PacketInfo{"TargetedSkill095", "ClientToServer", true, 6}},
	{RouteKey{0xC3, 0x1C, false, 0x00}, PacketInfo{"EnterGateRequest", "ClientToServer", true, 8}},
	{RouteKey{0xC3, 0x1C, false, 0x00}, PacketInfo{"EnterGateRequest075", "ClientToServer", true, 6}},
	{RouteKey{0xC3, 0x1D, false, 0x00}, PacketInfo{"AreaSkillHit095", "ClientToServer", false, 0}},
	{RouteKey{0xC3, 0x1E, false, 0x00}, PacketInfo{"AreaSkill", "ClientToServer", true, 13}},
	{RouteKey{0xC3, 0x1E, false, 0x00}, PacketInfo{"AreaSkill095", "ClientToServer", true, 7}},
	{RouteKey{0xC3, 0x22, false, 0x00}, PacketInfo{"PickupItemRequest", "ClientToServer", true, 5}},
	{RouteKey{0xC3, 0x23, false, 0x00}, PacketInfo{"DropItemRequest", "ClientToServer", true, 6}},
	{RouteKey{0xC3, 0x24, false, 0x00}, PacketInfo{"ItemMoveRequest", "ClientToServer", true, 19}},
	{RouteKey{0xC3, 0x24, false, 0x00}, PacketInfo{"ItemMoveRequestExtended", "ClientToServer", true, 7}},
	{RouteKey{0xC3, 0x26, false, 0x00}, PacketInfo{"ConsumeItemRequest", "ClientToServer", true, 6}},
	{RouteKey{0xC3, 0x30, false, 0x00}, PacketInfo{"TalkToNpcRequest", "ClientToServer", true, 5}},
	{RouteKey{0xC3, 0x32, false, 0x00}, PacketInfo{"BuyItemFromNpcRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC3, 0x33, false, 0x00}, PacketInfo{"SellItemToNpcRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC3, 0x34, false, 0x00}, PacketInfo{"ItemRepair", "ClientToServer", true, 4}},
	{RouteKey{0xC3, 0x36, false, 0x00}, PacketInfo{"TradeRequest", "ClientToServer", true, 5}},
	{RouteKey{0xC3, 0x3F, true, 0x01}, PacketInfo{"PlayerShopSetItemPrice", "ClientToServer", true, 9}},
	{RouteKey{0xC3, 0x3F, true, 0x02}, PacketInfo{"PlayerShopOpen", "ClientToServer", true, 30}},
	{RouteKey{0xC3, 0x3F, true, 0x03}, PacketInfo{"PlayerShopClose", "ClientToServer", true, 4}},
	{RouteKey{0xC3, 0x3F, true, 0x05}, PacketInfo{"PlayerShopItemListRequest", "ClientToServer", true, 16}},
	{RouteKey{0xC3, 0x3F, true, 0x06}, PacketInfo{"PlayerShopItemBuyRequest", "ClientToServer", true, 17}},
	{RouteKey{0xC3, 0x3F, true, 0x07}, PacketInfo{"PlayerShopCloseOther", "ClientToServer", true, 16}},
	{RouteKey{0xC3, 0x4A, false, 0x00}, PacketInfo{"RageAttackRequest", "ClientToServer", true, 8}},
	{RouteKey{0xC3, 0x99, false, 0x00}, PacketInfo{"ServerImmigrationRequest", "ClientToServer", false, 0}},
	{RouteKey{0xC3, 0xAA, true, 0x01}, PacketInfo{"DuelStartRequest", "ClientToServer", true, 16}},
	{RouteKey{0xC3, 0xAA, true, 0x02}, PacketInfo{"DuelStartResponse", "ClientToServer", true, 17}},
	{RouteKey{0xC3, 0xAA, true, 0x03}, PacketInfo{"DuelStopRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC3, 0xAA, true, 0x07}, PacketInfo{"DuelChannelJoinRequest", "ClientToServer", true, 5}},
	{RouteKey{0xC3, 0xAA, true, 0x09}, PacketInfo{"DuelChannelQuitRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC3, 0xB0, false, 0x00}, PacketInfo{"TeleportTarget", "ClientToServer", true, 7}},
	{RouteKey{0xC3, 0xB1, true, 0x01}, PacketInfo{"ServerChangeAuthentication", "ClientToServer", true, 69}},
	{RouteKey{0xC3, 0xDB, false, 0x00}, PacketInfo{"AreaSkillHit", "ClientToServer", false, 0}},
	{RouteKey{0xC3, 0xF1, true, 0x01}, PacketInfo{"LoginLongPassword", "ClientToServer", true, 60}},
	{RouteKey{0xC3, 0xF1, true, 0x01}, PacketInfo{"LoginShortPassword", "ClientToServer", true, 50}},
	{RouteKey{0xC3, 0xF1, true, 0x01}, PacketInfo{"Login075", "ClientToServer", true, 48}},
	{RouteKey{0xC3, 0xF1, true, 0x02}, PacketInfo{"LogOut", "ClientToServer", true, 5}},
	{RouteKey{0xC3, 0xF1, true, 0x03}, PacketInfo{"LogOutByCheatDetection", "ClientToServer", true, 6}},
	{RouteKey{0xC3, 0xF3, true, 0x10}, PacketInfo{"InventoryRequest", "ClientToServer", true, 4}},
	{RouteKey{0xC4, 0xC5, false, 0x00}, PacketInfo{"LetterSendRequest", "ClientToServer", false, 0}},
}

// Lookup 按精确键查包；重复键返回最先注册的条目。
func Lookup(key RouteKey) (PacketInfo, bool) {
	for _, e := range routes {
		if e.Key == key {
			return e.Info, true
		}
	}
	return PacketInfo{}, false
}

// LookupPacket 直接从一帧原始字节判定路由（C1/C3 的 Code 在偏移2，C2/C4 在偏移3）。
// 同时存在带/不带 SubCode 的条目时，优先匹配带 SubCode 的精确键。
func LookupPacket(buf []byte) (PacketInfo, bool) {
	if len(buf) < 3 {
		return PacketInfo{}, false
	}
	header := buf[0]
	codeIdx := 2
	if header == 0xC2 || header == 0xC4 {
		codeIdx = 3
	}
	if len(buf) <= codeIdx {
		return PacketInfo{}, false
	}
	code := buf[codeIdx]
	if len(buf) > codeIdx+1 {
		if info, ok := Lookup(RouteKey{header, code, true, buf[codeIdx+1]}); ok {
			return info, true
		}
	}
	return Lookup(RouteKey{header, code, false, 0})
}
