// Code generated by muprotogen from MUnique.OpenMU.Network.Packets 0.9.10; DO NOT EDIT.

package c2s

// TargetData Contains the data of the target
type TargetData struct{ d []byte }

const TargetDataLength = 3

func AsTargetData(buf []byte) *TargetData { return &TargetData{d: buf} }
func (s *TargetData) Bytes() []byte       { return s.d }
func (s *TargetData) Len() int            { return len(s.d) }

func (s *TargetData) TargetId() uint16         { return getU16BE(s.d[0:]) }
func (s *TargetData) SetTargetId(value uint16) { setU16BE(s.d[0:], value) }

func (s *TargetData) AnimationCounter() byte         { return s.d[2] }
func (s *TargetData) SetAnimationCounter(value byte) { s.d[2] = byte(value) }

// TargetData2 Contains the data of the target
type TargetData2 struct{ d []byte }

const TargetData2Length = 2

func AsTargetData2(buf []byte) *TargetData2 { return &TargetData2{d: buf} }
func (s *TargetData2) Bytes() []byte        { return s.d }
func (s *TargetData2) Len() int             { return len(s.d) }

func (s *TargetData2) TargetId() uint16         { return getU16BE(s.d[0:]) }
func (s *TargetData2) SetTargetId(value uint16) { setU16BE(s.d[0:], value) }

// TargetData3 Contains the data of the target
type TargetData3 struct{ d []byte }

const TargetData3Length = 2

func AsTargetData3(buf []byte) *TargetData3 { return &TargetData3{d: buf} }
func (s *TargetData3) Bytes() []byte        { return s.d }
func (s *TargetData3) Len() int             { return len(s.d) }

func (s *TargetData3) TargetId() uint16         { return getU16BE(s.d[0:]) }
func (s *TargetData3) SetTargetId(value uint16) { setU16BE(s.d[0:], value) }
