// Code generated by muprotogen from MUnique.OpenMU.Network.Packets 0.9.10; DO NOT EDIT.

package c2s

// PacketsVersion 与 MuMain 引用的 MUnique.OpenMU.Network.Packets NuGet 包版本一致。
const PacketsVersion = "0.9.10"
